---
title: "Footing"
author: "Greg Sanders"
date: "July 16, 2018"
output: html_document
---
## Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(csis360)
```



```{r import}




load(file = file.path("../Cleaning Data/FPDS/FPDS_datapull_all_v3.Rda"))
load(file = file.path("../Cleaning Data/FPDS/FPDS_cleaned_unique_wtotalobligations.Rda"))

file.exists("Raw Data/FPDS/Vendor.SP_DunsnumberNewEntrants_all.txt")
dir.exists("Cleaning Data/")
dir.exists("Analysis")
file.exists("New Entrants.Rproj")
list.files("../")
FPDS_data <- read.delim(file.path("../Raw Data/FPDS","Vendor.SP_DunsnumberNewEntrants_all.txt"), fill = TRUE, header=TRUE,  na.strings = c("", "NULL"))

# setwd("K:/2018-01 NPS New Entrants/Data/Data/Raw Data/FPDS")
# FPDS_data <- read.delim("Vendor.SP_DunsnumberNewEntrants_all.txt", fill = TRUE, header=TRUE,  na.strings = c("", "NULL"))

FPDS_data<-as.data.frame(FPDS_data)

```


## Prepare the raw data
```{r prepare}

FPDS_data<-csis360::remove_bom(FPDS_data)
# FPDS_data<-subset(FPDS_data,fiscal_year>=2000)

FPDS_data<-csis360::deflate(FPDS_data,money_var="obligatedAmount",
                            fy_var="fiscal_year", deflator_var = "GDPdeflator2017")
#Calculate first_year
FPDS_data<-FPDS_data %>%
  group_by(Dunsnumber) %>%
  dplyr::mutate(first_year=min(fiscal_year),
    entrant=ifelse(min(fiscal_year)==fiscal_year,TRUE,FALSE))

#Calculate annual spend and presence.
FPDS_duns_fyear<-FPDS_data %>%
  group_by(Dunsnumber,fiscal_year,entrant,first_year) %>%
  dplyr::summarize(obligatedAmount.2017=sum(obligatedAmount_GDPdeflator2017,na.rm=TRUE),
  # dplyr::summarize(obligatedAmount.Deflator.2016=sum(obligatedAmount.Deflator.2016,na.rm=TRUE),
                   present=max(obligatedAmount_GDPdeflator2017,na.rm=TRUE))
FPDS_duns_fyear$present<-ifelse(FPDS_duns_fyear$present>0,1,0)
summary(FPDS_duns_fyear$present)


#Check if dunsnumber is present in previous year
FPDS_duns_prev_fyear<-subset(FPDS_duns_fyear,select=c(fiscal_year,Dunsnumber,present))
FPDS_duns_prev_fyear$fiscal_year<-FPDS_duns_prev_fyear$fiscal_year+1
colnames(FPDS_duns_prev_fyear)[colnames(FPDS_duns_prev_fyear)=="present"]<-"prev_present"
FPDS_duns_fyear<-left_join(FPDS_duns_fyear,FPDS_duns_prev_fyear)
#Label NAs with 0, except when at start or end of series.
FPDS_duns_fyear$prev_present[is.na(FPDS_duns_fyear$prev_present) & FPDS_duns_fyear$fiscal_year!=2000]<-0
summary(FPDS_duns_fyear$prev_present)
rm(FPDS_duns_prev_fyear)

#Check if dunsnumber is present in next year
FPDS_duns_next_fyear<-subset(FPDS_duns_fyear,select=c(fiscal_year,Dunsnumber,present))
FPDS_duns_next_fyear$fiscal_year<-FPDS_duns_next_fyear$fiscal_year-1
colnames(FPDS_duns_next_fyear)[colnames(FPDS_duns_next_fyear)=="present"]<-"next_present"
FPDS_duns_fyear<-left_join(FPDS_duns_fyear,FPDS_duns_next_fyear)
#Label NAs with 0, except when at start or end of series.
FPDS_duns_fyear$next_present[is.na(FPDS_duns_fyear$next_present) & FPDS_duns_fyear$fiscal_year<2017]<-0
summary(FPDS_duns_fyear$next_present)
rm(FPDS_duns_next_fyear)
  

FPDS_duns_fyear$sample_year<-FPDS_duns_fyear$first_year
FPDS_duns_fyear$sample_year[FPDS_duns_fyear$sample_year<2001 | FPDS_duns_fyear$sample_year>2006]<-"Not in sample"
FPDS_duns_fyear$sample_year<-factor(FPDS_duns_fyear$sample_year,levels=c("Not in sample","2001","2002","2003","2004","2005","2006"))



FPDS_duns_fyear$status<-NA
FPDS_duns_fyear$status[FPDS_duns_fyear$present==0]<-"No net payments"
FPDS_duns_fyear$status[is.na(FPDS_duns_fyear$status) & FPDS_duns_fyear$prev_present==0 & FPDS_duns_fyear$next_present==0]<-"Blip"
FPDS_duns_fyear$status[is.na(FPDS_duns_fyear$status) & FPDS_duns_fyear$prev_present==0 & !is.na(FPDS_duns_fyear$next_present)]<-"Enter"
FPDS_duns_fyear$status[is.na(FPDS_duns_fyear$status) & FPDS_duns_fyear$next_present==0 & !is.na(FPDS_duns_fyear$prev_present)]<-"Exit"
FPDS_duns_fyear$status[is.na(FPDS_duns_fyear$status) & FPDS_duns_fyear$prev_present==1 & FPDS_duns_fyear$next_present==1]<-"Steady"
FPDS_duns_fyear$status<-factor(FPDS_duns_fyear$status)
summary(FPDS_duns_fyear$status)

FPDS_duns_fyear<-subset(FPDS_duns_fyear,fiscal_year>=2000)

save(file="../Cleaning Data/footing.rda",FPDS_data,FPDS_duns_fyear)
# load(file="../Cleaning Data/footing.rda")

```

## Count

First lets look at the total number of vendors.

```{r count, echo=FALSE, fig.width=6.5, fig.height=9}
##counting the number of new entrants and incumbent firms##
build_plot(
  data=FPDS_summary, ##where is FPDS summary?
  chart_geom = "Line Chart",
  share = TRUE,
  x_var="fiscal_year",
  y_var="count", #Name of variable to plot on y-axis
  color_var="entrant",       # name of coloration variable, as string
  # facet_var="entrant",        # name of facet variable, as string
  legend=TRUE, #Include a legend
  caption=TRUE, #Include a source caption
  labels_and_colors=NULL,
  column_key=NULL
)

##counting the number of new entrants and incumbent firms stacked##
build_plot(
  data=FPDS_duns_fyear,
  chart_geom = "Histogram",
  # share = FALSE,
  x_var="fiscal_year",
  # y_var="obligatedAmount.2017", #Name of variable to plot on y-axis
  color_var="status",       # name of coloration variable, as string
  facet_var="status",        # name of facet variable, as string
  legend=TRUE, #Include a legend
  caption=TRUE, #Include a source caption
  labels_and_colors=NULL,
  column_key=NULL
)


#*****#
##SRC##
#*****#
#number of new entrants vs incumbent firms
#drop years before 2001 and after 2016
FPDS_duns_fyear_op <- FPDS_duns_fyear[!(FPDS_duns_fyear$fiscal_year<2001), ]
FPDS_duns_fyear_op <- FPDS_duns_fyear_op[!(FPDS_duns_fyear_op$fiscal_year>2016), ]

ggplot(FPDS_duns_fyear_op, aes(x = fiscal_year, fill = factor(entrant))) +
  geom_histogram(position = "stack", binwidth = 1) +
  scale_x_continuous(breaks = c(2001:2016)) +
  xlab("Fiscal Year") +
  ylab("Number of Vendors") +
  scale_fill_manual(name = "New Entrants Types", values = c("darkslategray1", "cadetblue4"), labels = c("Incumbent", "New Entrant")) 
#******************************#
#******************************#

##counting the number of new entrant and incumbent firms on two separate graphs##
build_plot(
  data=FPDS_duns_fyear,
  chart_geom = "Histogram",
  # share = FALSE,
  x_var="fiscal_year",
  # y_var="obligatedAmount.2017", #Name of variable to plot on y-axis
  color_var="entrant",       # name of coloration variable, as string
  facet_var="entrant",        # name of facet variable, as string
  legend=TRUE, #Include a legend
  caption=TRUE, #Include a source caption
  labels_and_colors=NULL,
  column_key=NULL
)+facet_wrap(~entrant,scales="free_y",ncol=1)


build_plot(
  data=FPDS_duns_fyear,
  chart_geom = "Histogram",
  # share = FALSE,
  x_var="fiscal_year",
  # y_var="obligatedAmount.2017", #Name of variable to plot on y-axis
  color_var="status",       # name of coloration variable, as string
  facet_var="entrant",        # name of facet variable, as string
  legend=TRUE, #Include a legend
  caption=TRUE, #Include a source caption
  labels_and_colors=NULL,
  column_key=NULL
)+facet_wrap(~entrant,scales="free_y",ncol=1)


#number of vendors from each sample over time#
#I think i want drop the "not included in sample" --> use FPDS_duns_fyear_op
build_plot(
  data=FPDS_duns_fyear,
  chart_geom = "Histogram",
  # share = FALSE,
  x_var="fiscal_year",
  # y_var="obligatedAmount.2017", #Name of variable to plot on y-axis
  color_var="sample_year",       # name of coloration variable, as string
  # facet_var="sample_year",        # name of facet variable, as string
  legend=TRUE, #Include a legend
  caption=TRUE, #Include a source caption
  labels_and_colors=NULL,
  column_key=NULL
)+labs(x="Fiscal Year of Transaction",y="Number of Contractors") #what do you mean by fiscal year of transaction







build_plot(
  data=subset(FPDS_duns_fyear,sample_year!="Not in sample"),
  chart_geom = "Histogram",
  # share = FALSE,
  x_var="fiscal_year",
  # y_var="obligatedAmount.2017", #Name of variable to plot on y-axis
  color_var="sample_year",       # name of coloration variable, as string
  # facet_var="sample_year",        # name of facet variable, as string
  legend=TRUE, #Include a legend
  caption=TRUE, #Include a source caption
  labels_and_colors=NULL,
  column_key=NULL
)+labs(x="Fiscal Year of Transaction",y="Number of Contractors") #what do you mean by fiscal year of transaction


#*******#
#**SRC**#
#*******#
##drop those not in sample 
#1. make not in sample binary
table(FPDS_duns_fyear$sample_year)
FPDS_duns_fyear$sample_year_bin <- revalue(FPDS_duns_fyear$sample_year, c("Not in sample"="0", "2001"="1", "2002"="2", "2003"="3", "2004"="4", "2005"="5", "2006"="6"))
str(FPDS_duns_fyear$sample_year_bin)
table(FPDS_duns_fyear$sample_year_bin)
FPDS_duns_fyear$sample_year_bin <- as.numeric(as.character(FPDS_duns_fyear$sample_year_bin))
str(FPDS_duns_fyear$sample_year_bin)
table(FPDS_duns_fyear$sample_year_bin)

FPDS_duns_fyear_samples <- FPDS_duns_fyear[!(FPDS_duns_fyear$sample_year_bin<1), ]
FPDS_duns_fyear_samples_op <- FPDS_duns_fyear_samples[!(FPDS_duns_fyear_samples$fiscal_year<2001), ]
FPDS_duns_fyear_samples_op <- FPDS_duns_fyear_samples_op[!(FPDS_duns_fyear_samples_op$fiscal_year>2016), ]


ggplot(FPDS_duns_fyear_samples_op, aes(x = fiscal_year, fill = factor(sample_year))) +
  geom_histogram(position = "stack", binwidth = .5)
#*****************************************************************************************#
#*****************************************************************************************#


build_plot(
  data=FPDS_duns_fyear,
  chart_geom = "Histogram",
  # share = FALSE,
  x_var="fiscal_year",
  # y_var="obligatedAmount.2017", #Name of variable to plot on y-axis
  color_var="sample_year",       # name of coloration variable, as string
  facet_var="sample_year",        # name of facet variable, as string
  legend=TRUE, #Include a legend
  caption=TRUE, #Include a source caption
  labels_and_colors=NULL,
  column_key=NULL
)+facet_wrap(~sample_year,scales="fixed",ncol=1)+
  labs(x="Fiscal Year of Transaction",y="Number of Contractors")

#GSS2018-07-30 Start year faceted, but only vendors in sample, x is fiscal year
sample<-subset(FPDS_duns_fyear,sample_year!="Not in sample")
build_plot(
  data=sample,
  chart_geom = "Histogram",
  # share = FALSE,
  x_var="fiscal_year",
  # y_var="obligatedAmount.2017", #Name of variable to plot on y-axis
  color_var="sample_year",       # name of coloration variable, as string
  facet_var="sample_year",        # name of facet variable, as string
  legend=TRUE, #Include a legend
  caption=TRUE, #Include a source caption
  labels_and_colors=NULL,
  column_key=NULL
)+facet_wrap(~sample_year,scales="fixed",ncol=1)+
  labs(x="Fiscal Year of Transaction",y="Number of Contractors")

#GSS2018-07-30 Start year faceted, but only vendors in sample, x is number of years since entry

sample$years_in_sample<-sample$fiscal_year-sample$first_year
build_plot(
  data=sample,
  chart_geom = "Histogram",
  # share = FALSE,
  x_var="years_in_sample",
  # y_var="obligatedAmount.2017", #Name of variable to plot on y-axis
  color_var="sample_year",       # name of coloration variable, as string
  facet_var="sample_year",        # name of facet variable, as string
  legend=TRUE, #Include a legend
  caption=TRUE, #Include a source caption
  labels_and_colors=NULL,
  column_key=NULL
)+facet_wrap(~sample_year,scales="fixed",ncol=1)+
  labs(x="Years Since Vendor Became New Entrant",y="Number of Contractors")





build_plot(
  data=FPDS_duns_fyear,
  chart_geom = "Histogram",
  # share = FALSE,
  x_var="fiscal_year",
  # y_var="obligatedAmount.2017", #Name of variable to plot on y-axis
  color_var="status",       # name of coloration variable, as string
  facet_var="sample_year",        # name of facet variable, as string
  legend=TRUE, #Include a legend
  caption=TRUE, #Include a source caption
  labels_and_colors=NULL,
  column_key=NULL
)+facet_wrap(~sample_year,scales="fixed",ncol=1)+
  labs(x="Fiscal Year of Transaction",y="Number of Contractors")




build_plot(
  data=FPDS_cleaned_unique,
  chart_geom = "Histogram",
  # share = FALSE,
  x_var="FYear",
  # y_var="obligatedAmount.2017", #Name of variable to plot on y-axis
  # color_var="entrant",       # name of coloration variable, as string
  # facet_var="entrant",        # name of facet variable, as string
  legend=TRUE, #Include a legend
  caption=TRUE, #Include a source caption
  labels_and_colors=NULL,
  column_key=NULL
)+labs(x="Fiscal Year of Contractor First Appearance",y="Number of Contractors")#+facet_wrap(~entrant,scales="free_y",ncol=1)


```
# Dollars
Then the vendor spend.

```{r dollars, fig.width=7, fig.height=7}

build_plot(
  data=FPDS_summary,
  chart_geom = "Bar Chart",
  # share = FALSE,
  x_var="fiscal_year",
  y_var="obligatedAmount.2017", #Name of variable to plot on y-axis
  color_var="entrant",       # name of coloration variable, as string
  # facet_var="entrant",        # name of facet variable, as string
  legend=TRUE, #Include a legend
  caption=TRUE, #Include a source caption
  labels_and_colors=NULL,
  column_key=NULL
)+labs(x="Fiscal Year of Transaction",y="Obligations 2017 $")


##fiscal year of transaction
build_plot(
  data=FPDS_summary,
  chart_geom = "Bar Chart",
  # share = FALSE,
  x_var="fiscal_year",
  y_var="obligatedAmount.2017", #Name of variable to plot on y-axis
  color_var="entrant",       # name of coloration variable, as string
  facet_var="entrant",        # name of facet variable, as string
  legend=TRUE, #Include a legend
  caption=TRUE, #Include a source caption
  labels_and_colors=NULL,
  column_key=NULL
)+facet_wrap(~entrant,scales="free_y",ncol=1)+labs(x="Fiscal Year of Transaction",y="Obligations 2017 $")


build_plot(
  data=FPDS_summary,
  chart_geom = "Bar Chart",
  # share = FALSE,
  x_var="fiscal_year",
  y_var="obligatedAmount.2017", #Name of variable to plot on y-axis
  color_var="sample_year",       # name of coloration variable, as string
  # facet_var="sample_year",        # name of facet variable, as string
  legend=TRUE, #Include a legend
  caption=TRUE, #Include a source caption
  labels_and_colors=NULL,
  column_key=NULL
)+labs(x="Fiscal Year of Transaction",y="Obligations 2017 $")


build_plot(
  data=FPDS_summary,
  chart_geom = "Bar Chart",
  # share = FALSE,
  x_var="fiscal_year",
  y_var="obligatedAmount.2017", #Name of variable to plot on y-axis
  color_var="sample_year",       # name of coloration variable, as string
  facet_var="sample_year",        # name of facet variable, as string
  legend=TRUE, #Include a legend
  caption=TRUE, #Include a source caption
  labels_and_colors=NULL,
  column_key=NULL
)+facet_wrap(~sample_year,scales="free_y",space="free_y",ncol=1)+
  labs(x="Fiscal Year of Transaction",y="Obligations 2017 $")



build_plot(
  data=FPDS_cleaned_unique,
  chart_geom = "Bar Chart",
  # share = FALSE,
  x_var="FYear",
  y_var="total_obligations", #Name of variable to plot on y-axis
  # color_var="entrant",       # name of coloration variable, as string
  # facet_var="entrant",        # name of facet variable, as string
  legend=TRUE, #Include a legend
  caption=TRUE, #Include a source caption
  labels_and_colors=NULL,
  column_key=NULL
)labs(x="Fiscal Year of Contractor First Appearance",y="Obligations 2017 $")


```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
