---
title: "Footing"
author: "Greg Sanders"
date: "July 16, 2018"
output: html_document
---
# Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(tidyverse)
library(ggplot2)
library(csis360)
load(file="../data/clean/FPDS_eid_fyear.rda")
eid_lc<-prepare_labels_and_colors(FPDS_eid_fyear)


summary(factor(FPDS_eid_fyear$IsEntityAbove2018constant10ThousandThreshold))

summary(factor(FPDS_eid_fyear$EntitySizeText))
summary(factor(FPDS_eid_fyear$EntitySizeGlitch))
summary(FPDS_eid_fyear$ObligatedAmountIsSmall)
summary(FPDS_eid_fyear$MajorityNotSmall)
FPDS_eid_fyear$count<-1
FPDS_eid_fyear<-csis360::read_and_join_experiment(FPDS_eid_fyear,
                        "EntitySizeCode.csv",
                        by=c("EntitySizeCode"),
                        add_var=c("EntitySmall"),
                        path="https://raw.githubusercontent.com/CSISdefense/Lookup-Tables/master/",
                        dir="vendor/"
)

FPDS_eid_fyear$EntitySmall[FPDS_eid_fyear$EntitySizeGlitch==TRUE |FPDS_eid_fyear$EntitySmall=="Unlabeled Vendor" ]<-"Unlabeled"
summary(factor(FPDS_eid_fyear$EntitySmall))
FPDS_eid_fyear$EntitySmall<-factor(FPDS_eid_fyear$EntitySmall,rev(c("Always Small Vendor","Sometimes Small Vendor","Other Than Small","Unlabeled")))
```
# Overall Vendor
```{r overall}


(
all_10k_small_bar<-build_plot(
  data=FPDS_eid_fyear %>% dplyr::filter(IsEntityAbove2018constant10ThousandThreshold==1), ##where is FPDS summary?
  chart_geom = "Bar Chart",
  share = FALSE,
  x_var="fiscal_year",
  y_var="count", #Name of variable to plot on y-axis
  color_var="EntitySmall",       # name of coloration variable, as string
  # facet_var="EntitySizeText",        # name of facet variable, as string
  legend=TRUE, #Include a legend
  caption=TRUE, #Include a source caption
  # labels_and_colors=eid_lc,
  column_key=NULL,
  format=TRUE
)
)
(
all_small_bar<-build_plot(
  data=FPDS_eid_fyear,# %>% dplyr::filter(IsEntityAbove2018constant10ThousandThreshold==0), ##where is FPDS summary?
  chart_geom = "Bar Chart",
  share = FALSE,
  x_var="fiscal_year",
  y_var="count", #Name of variable to plot on y-axis
  color_var="EntitySmall",       # name of coloration variable, as string
  # facet_var="EntitySizeText",        # name of facet variable, as string
  legend=TRUE, #Include a legend
  caption=TRUE, #Include a source caption
  # labels_and_colors=eid_lc,
  column_key=NULL,
  format=TRUE
)
)

write.csv(all_10k_small_bar$data %>% pivot_wider(id_cols="EntitySmall",names_from="fiscal_year",values_from="count"),file.path("..","output","all_10k_small.csv"))


write.csv(all_small_bar$data %>% pivot_wider(id_cols="EntitySmall",names_from="fiscal_year",values_from="count"),file.path("..","output","all_small.csv"))

ggsave(all_10k_small_bar+labs(title="Federal Contractor Count",x="Fiscal Year",y="Number of Entities with contracts\nvalued over $10k threshold (in 2018 constant dollars)"),file=file.path("..","output","all_10k_small.png"))

```

# New Entrant Count

First lets look at the total number of vendors.

```{r count, echo=FALSE, fig.width=6.5, fig.height=9}
##counting the number of new entrants and incumbent firms##



build_plot(
  data=FPDS_eid_fyear, ##where is FPDS summary?
  chart_geom = "Line Chart",
  share = TRUE,
  x_var="fiscal_year",
  y_var="count", #Name of variable to plot on y-axis
  color_var="entrant",       # name of coloration variable, as string
  # facet_var="entrant",        # name of facet variable, as string
  legend=TRUE, #Include a legend
  caption=TRUE, #Include a source caption
  labels_and_colors=eid_lc,
  column_key=NULL,
  format=TRUE
)


build_plot(
  data=FPDS_eid_fyear %>% filter(first_year_2018T==2007), ##where is FPDS summary?
  chart_geom = "Bar Chart",
  share = FALSE,
  x_var="fiscal_year",
  y_var="count", #Name of variable to plot on y-axis
  color_var="last_year_2018T",       # name of coloration variable, as string
  # facet_var="entrant",        # name of facet variable, as string
  legend=TRUE, #Include a legend
  caption=TRUE, #Include a source caption
  labels_and_colors=NULL,
  column_key=NULL,
  format=TRUE
)

  ##counting the number of new entrants and incumbent firms stacked##
  build_plot(
    data=FPDS_eid_fyear,
    chart_geom = "Histogram",
    # share = FALSE,
    x_var="fiscal_year",
    # y_var="obligatedAmount.2017", #Name of variable to plot on y-axis
    color_var="status",       # name of coloration variable, as string
    facet_var="status",        # name of facet variable, as string
    legend=TRUE, #Include a legend
    caption=TRUE, #Include a source caption
    labels_and_colors=NULL,
    column_key=NULL
  )

  ##counting the number of new entrants and incumbent firms stacked##
  build_plot(
    data=FPDS_eid_fyear %>% filter(first_year_2018T==2007),
    chart_geom = "Histogram",
    # share = FALSE,
    x_var="fiscal_year",
    # y_var="obligatedAmount.2017", #Name of variable to plot on y-axis
    color_var="status",       # name of coloration variable, as string
    facet_var="status",        # name of facet variable, as string
    legend=TRUE, #Include a legend
    caption=TRUE, #Include a source caption
    labels_and_colors=NULL,
    column_key=NULL
  )
```

### SRC Count
```{r srccount}
#*****#
##SRC##
#*****#
#number of new entrants vs incumbent firms
#drop years before 2001 and after 2016
FPDS_eid_fyear_op <- FPDS_eid_fyear[!(FPDS_eid_fyear$fiscal_year<2001), ]
FPDS_eid_fyear_op <- FPDS_eid_fyear_op[!(FPDS_eid_fyear_op$fiscal_year>2016), ]

ggplot(FPDS_eid_fyear_op, aes(x = fiscal_year, fill = factor(entrant))) +
  geom_histogram(position = "stack", binwidth = 1) +
  scale_x_continuous(breaks = c(2001:2016)) +
  xlab("Fiscal Year") +
  ylab("Number of Vendors") +
  scale_fill_manual(name = "New Entrants Types", values = c("darkslategray1", "cadetblue4"), labels = c("Incumbent", "New Entrant")) 
#******************************#
#******************************#

##counting the number of new entrant and incumbent firms on two separate graphs##
build_plot(
  data=FPDS_eid_fyear,
  chart_geom = "Histogram",
  # share = FALSE,
  x_var="fiscal_year",
  # y_var="obligatedAmount.2017", #Name of variable to plot on y-axis
  color_var="entrant",       # name of coloration variable, as string
  facet_var="entrant",        # name of facet variable, as string
  legend=TRUE, #Include a legend
  caption=TRUE, #Include a source caption
  labels_and_colors=eid_lc,
  column_key=NULL
)+facet_wrap(~entrant,scales="free_y",ncol=1)


build_plot(
  data=FPDS_eid_fyear,
  chart_geom = "Histogram",
  # share = FALSE,
  x_var="fiscal_year",
  # y_var="obligatedAmount.2017", #Name of variable to plot on y-axis
  color_var="status",       # name of coloration variable, as string
  facet_var="entrant",        # name of facet variable, as string
  legend=TRUE, #Include a legend
  caption=TRUE, #Include a source caption
  labels_and_colors=eid_lc,
  column_key=NULL
)+facet_wrap(~entrant,scales="free_y",ncol=1)


#number of vendors from each sample over time#
#I think i want drop the "not included in sample" --> use FPDS_eid_fyear_op
build_plot(
  data=FPDS_eid_fyear,
  chart_geom = "Histogram",
  # share = FALSE,
  x_var="fiscal_year",
  # y_var="obligatedAmount.2017", #Name of variable to plot on y-axis
  color_var="sample_year",       # name of coloration variable, as string
  # facet_var="sample_year",        # name of facet variable, as string
  legend=TRUE, #Include a legend
  caption=TRUE, #Include a source caption
  labels_and_colors=eid_lc,
  column_key=NULL
)+labs(x="Fiscal Year of Transaction",y="Number of Contractors") #what do you mean by fiscal year of transaction







build_plot(
  data=subset(FPDS_eid_fyear,sample_year!="Not in sample"),
  chart_geom = "Histogram",
  # share = FALSE,
  x_var="fiscal_year",
  # y_var="obligatedAmount.2017", #Name of variable to plot on y-axis
  color_var="sample_year",       # name of coloration variable, as string
  # facet_var="sample_year",        # name of facet variable, as string
  legend=TRUE, #Include a legend
  caption=TRUE, #Include a source caption
  labels_and_colors=eid_lc,
  column_key=NULL
)+labs(x="Fiscal Year of Transaction",y="Number of Contractors") #what do you mean by fiscal year of transaction


#*******#
#**SRC**#
#*******#
##drop those not in sample 
#1. make not in sample binary
table(FPDS_eid_fyear$sample_year)
FPDS_eid_fyear$sample_year_bin <- revalue(FPDS_eid_fyear$sample_year, c("Not in sample"="0", "2001"="1", "2002"="2", "2003"="3", "2004"="4", "2005"="5", "2006"="6"))
str(FPDS_eid_fyear$sample_year_bin)
table(FPDS_eid_fyear$sample_year_bin)
FPDS_eid_fyear$sample_year_bin <- as.numeric(as.character(FPDS_eid_fyear$sample_year_bin))
str(FPDS_eid_fyear$sample_year_bin)
table(FPDS_eid_fyear$sample_year_bin)

FPDS_eid_fyear_samples <- FPDS_eid_fyear[!(FPDS_eid_fyear$sample_year_bin<1), ]
FPDS_eid_fyear_samples_op <- FPDS_eid_fyear_samples[!(FPDS_eid_fyear_samples$fiscal_year<2001), ]
FPDS_eid_fyear_samples_op <- FPDS_eid_fyear_samples_op[!(FPDS_eid_fyear_samples_op$fiscal_year>2016), ]


ggplot(FPDS_eid_fyear_samples_op, aes(x = fiscal_year, fill = factor(sample_year))) +
  geom_histogram(position = "stack", binwidth = .5)
#*****************************************************************************************#
#*****************************************************************************************#


build_plot(
  data=FPDS_eid_fyear,
  chart_geom = "Histogram",
  # share = FALSE,
  x_var="fiscal_year",
  # y_var="obligatedAmount.2017", #Name of variable to plot on y-axis
  color_var="sample_year",       # name of coloration variable, as string
  facet_var="sample_year",        # name of facet variable, as string
  legend=TRUE, #Include a legend
  caption=TRUE, #Include a source caption
  labels_and_colors=eid_lc,
  column_key=NULL
)+facet_wrap(~sample_year,scales="fixed",ncol=1)+
  labs(x="Fiscal Year of Transaction",y="Number of Contractors")

#GSS2018-07-30 Start year faceted, but only vendors in sample, x is fiscal year
sample<-subset(FPDS_eid_fyear,sample_year!="Not in sample")
build_plot(
  data=sample,
  chart_geom = "Histogram",
  # share = FALSE,
  x_var="fiscal_year",
  # y_var="obligatedAmount.2017", #Name of variable to plot on y-axis
  color_var="sample_year",       # name of coloration variable, as string
  facet_var="sample_year",        # name of facet variable, as string
  legend=TRUE, #Include a legend
  caption=TRUE, #Include a source caption
  labels_and_colors=eid_lc,
  column_key=NULL
)+facet_wrap(~sample_year,scales="fixed",ncol=1)+
  labs(x="Fiscal Year of Transaction",y="Number of Contractors")

#GSS2018-07-30 Start year faceted, but only vendors in sample, x is number of years since entry

sample$years_in_sample<-sample$fiscal_year-sample$first_year_2018T
build_plot(
  data=sample,
  chart_geom = "Histogram",
  # share = FALSE,
  x_var="years_in_sample",
  # y_var="obligatedAmount.2017", #Name of variable to plot on y-axis
  color_var="sample_year",       # name of coloration variable, as string
  facet_var="sample_year",        # name of facet variable, as string
  legend=TRUE, #Include a legend
  caption=TRUE, #Include a source caption
  labels_and_colors=eid_lc,
  column_key=NULL
)+facet_wrap(~sample_year,scales="fixed",ncol=1)+
  labs(x="Years Since Vendor Became New Entrant",y="Number of Contractors")





build_plot(
  data=FPDS_eid_fyear,
  chart_geom = "Histogram",
  # share = FALSE,
  x_var="fiscal_year",
  # y_var="obligatedAmount.2017", #Name of variable to plot on y-axis
  color_var="status",       # name of coloration variable, as string
  facet_var="sample_year",        # name of facet variable, as string
  legend=TRUE, #Include a legend
  caption=TRUE, #Include a source caption
  labels_and_colors=eid_lc,
  column_key=NULL
)+facet_wrap(~sample_year,scales="fixed",ncol=1)+
  labs(x="Fiscal Year of Transaction",y="Number of Contractors")




build_plot(
  data=FPDS_cleaned_unique,
  chart_geom = "Histogram",
  # share = FALSE,
  x_var="FYear",
  # y_var="obligatedAmount.2017", #Name of variable to plot on y-axis
  # color_var="entrant",       # name of coloration variable, as string
  # facet_var="entrant",        # name of facet variable, as string
  legend=TRUE, #Include a legend
  caption=TRUE, #Include a source caption
  labels_and_colors=eid_lc,
  column_key=NULL
)+labs(x="Fiscal Year of Contractor First Appearance",y="Number of Contractors")#+facet_wrap(~entrant,scales="free_y",ncol=1)


```
# Dollars
Then the vendor spend.

```{r dollars, fig.width=7, fig.height=7}

build_plot(
  data=FPDS_eid_fyear,
  chart_geom = "Bar Chart",
  # share = FALSE,
  x_var="fiscal_year",
  y_var="obligatedAmount.2017", #Name of variable to plot on y-axis
  color_var="entrant",       # name of coloration variable, as string
  # facet_var="entrant",        # name of facet variable, as string
  legend=TRUE, #Include a legend
  caption=TRUE, #Include a source caption
  labels_and_colors=eid_lc,
  column_key=NULL
)+labs(x="Fiscal Year of Transaction",y="Obligations 2017 $")


##fiscal year of transaction
build_plot(
  data=FPDS_eid_fyear,
  chart_geom = "Bar Chart",
  # share = FALSE,
  x_var="fiscal_year",
  y_var="obligatedAmount.2017", #Name of variable to plot on y-axis
  color_var="entrant",       # name of coloration variable, as string
  facet_var="entrant",        # name of facet variable, as string
  legend=TRUE, #Include a legend
  caption=TRUE, #Include a source caption
  labels_and_colors=eid_lc,
  column_key=NULL
)+facet_wrap(~entrant,scales="free_y",ncol=1)+labs(x="Fiscal Year of Transaction",y="Obligations 2017 $")


build_plot(
  data=FPDS_eid_fyear,
  chart_geom = "Bar Chart",
  # share = FALSE,
  x_var="fiscal_year",
  y_var="obligatedAmount.2017", #Name of variable to plot on y-axis
  color_var="sample_year",       # name of coloration variable, as string
  # facet_var="sample_year",        # name of facet variable, as string
  legend=TRUE, #Include a legend
  caption=TRUE, #Include a source caption
  labels_and_colors=eid_lc,
  column_key=NULL
)+labs(x="Fiscal Year of Transaction",y="Obligations 2017 $")


build_plot(
  data=FPDS_eid_fyear,
  chart_geom = "Bar Chart",
  # share = FALSE,
  x_var="fiscal_year",
  y_var="obligatedAmount.2017", #Name of variable to plot on y-axis
  color_var="sample_year",       # name of coloration variable, as string
  facet_var="sample_year",        # name of facet variable, as string
  legend=TRUE, #Include a legend
  caption=TRUE, #Include a source caption
  labels_and_colors=eid_lc,
  column_key=NULL
)+facet_wrap(~sample_year,scales="free_y",space="free_y",ncol=1)+
  labs(x="Fiscal Year of Transaction",y="Obligations 2017 $")



build_plot(
  data=FPDS_cleaned_unique,
  chart_geom = "Bar Chart",
  # share = FALSE,
  x_var="FYear",
  y_var="total_obligations", #Name of variable to plot on y-axis
  # color_var="entrant",       # name of coloration variable, as string
  # facet_var="entrant",        # name of facet variable, as string
  legend=TRUE, #Include a legend
  caption=TRUE, #Include a source caption
  labels_and_colors=eid_lc,
  column_key=NULL
)labs(x="Fiscal Year of Contractor First Appearance",y="Obligations 2017 $")


```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

