select nyt.NYjudgement, ccid.ContractLabelID,clid.ContractLabelText, count(ccid.csiscontractid)
from dbo.NYK20250414 nyt
inner join contract.contract_award_unique_key cau
on nyt.contract_award_unique_key=cau.contract_award_unique_key
inner join contract.CSIScontractID ccid
on cau.CSIScontractID=ccid.CSIScontractID
left outer join contract.ContractLabelID clid
on ccid.ContractLabelID=clid.ContractLabelid
group by nyt.NYjudgement, ccid.ContractLabelID,clid.ContractLabelText

select *
from contract.ContractLabelID

update ccid
set ccid.ContractLabelID=1072
from dbo.NYK20250414 nyt
inner join contract.contract_award_unique_key cau
on nyt.contract_award_unique_key=cau.contract_award_unique_key
inner join contract.CSIScontractID ccid
on cau.CSIScontractID=ccid.CSIScontractID
left outer join contract.ContractLabelID clid
on ccid.ContractLabelID=clid.ContractLabelid
where NYjudgement='X' and clid.IsPerformanceBasedLogistics is null
--clid.ContractLabelID=6 and nyt.NYjudgement='PBLO'

--Finding contradictions
select nyt.contract_award_unique_key, nyt.NYjudgement, ccid.ContractLabelID,clid.ContractLabelText
from dbo.NYK20250414 nyt
inner join contract.contract_award_unique_key cau
on nyt.contract_award_unique_key=cau.contract_award_unique_key
inner join contract.CSIScontractID ccid
on cau.CSIScontractID=ccid.CSIScontractID
left outer join contract.ContractLabelID clid
on ccid.ContractLabelID=clid.ContractLabelid
where NYjudgement='X' and clid.IsPerformanceBasedLogistics=1



--7h26m
--103,648 rows
SET QUERY_GOVERNOR_COST_LIMIT 0
SET ANSI_WARNINGS OFF;
SET NOCOUNT ON;
EXEC	[Contract].[SP_PBLcompetitionContractSizeHistorySubCustomer]
		@Customer = N'Defense'




		--8h49m
		SELECT [fiscal_year]
      --,[fiscal_quarter]
      --,[fiscal_quarter_YTD]
      ,[contract_transaction_unique_key]
      ,[contract_award_unique_key]
      ,[parent_contract_award_unique_key]
      --,[parent_cau_isderived]
      --,[grand_parent_contract_award_unique_key]
      --,[grand_parent_cau_isderived]
      --,[CSIScontractID]
      --,[CSISidvpiidid]
      --,[CSISidvmodificationID]
      ,[ContractLabelID]
      ,[ContractLabelText]
      ,[IsPerformanceBasedLogistics]
      ,[IsOrganicPBL]
      --,[unique_transaction_id]
      ,[transaction_status]
      ,[signeddate]
      ,[effectivedate]
      ,[currentcompletiondate]
      ,[UnmodifiedUltimateDurationCategory]
      ,[CurrentDurationCategory]
      ,[CurrentDuration]
      ,[ultimatecompletiondate]
      ,[lastdatetoorder]
      ,[solicitation_date]
      --,[Query_Run_Date]
      ,[CurrentEndFYear]
      ,[UnmodifiedUltimateEndFYear]
      ,[obligatedAmount]
      ,[GrossObligatedAmount]
      ,[baseandexercisedoptionsvalue]
      ,[baseandalloptionsvalue]
      ,[total_dollars_obligated]
      ,[current_total_value_of_award]
      ,[potential_total_value_of_award]
      ,[numberOfActions]
      --,[CIDIsAbove2016constantArbitrary1000k]
      --,[CIDIsAbove1990constantMTAthreshold]
      --,[CIDIsAbove2016constantMTAthreshold]
      --,[CIDIsAbove2018constantMTAthreshold]
      --,[CIDIsAbove2018constantCostAccounting2000kThreshold]
      --,[CIDIsAbove2018constantSimplifedAcquisition250kThreshold]
      --,[CIDIsAbove2018constantCommercialItem7500k]
      --,[IsAbove2016constantArbitrary1000k]
      --,[IsAbove1990constantMTAthreshold]
      --,[IsAbove2016constantMTAthreshold]
      --,[IsAbove2018constantMTAthreshold]
      --,[IsAbove2018constantCostAccounting2000kThreshold]
      --,[IsAbove2018constantSimplifedAcquisition250kThreshold]
      --,[IsAbove2018constantCommercialItem7500k]
      ,[typeofcontractpricing]
      ,[TypeOfContractPricing5Category]
      ,[PricingFee]
      ,[PricingUCA]
      ,[priceevaluationpercentdifference]
      ,[subcontractplan]
      ,[lettercontract]
      ,[multiyearcontract]
      ,[performancebasedservicecontract]
      ,[majorprogramcode]
      ,[contractfinancing]
      ,[costorpricingdata]
      ,[costaccountingstandardsclause]
      ,[transaction_description]
      ,[purchasecardaspaymentmethod]
      ,[progsourceagency]
      ,[progsourceaccount]
      ,[progsourcesubacct]
      ,[account_title]
      ,[rec_flag]
      ,[typeofidc]
      ,[programacronym]
      ,[vendorname]
      ,[vendoralternatename]
      ,[vendorlegalorganizationname]
      ,[vendordoingasbusinessname]
      ,[recipient_uei]
      ,[recipient_parent_uei]
      ,[EntityID]
      ,[IsEntityTraditional]
      ,[ParentID]
      --,[AllVendor]
      ,[parentheadquarterscountrycode]
      ,[parentheadquartersisForeign]
      ,[divisionname]
      ,[divisionnumberorofficecode]
      ,[streetaddress]
      ,[streetaddress2]
      ,[streetaddress3]
      ,[city]
      ,[zipcode]
      ,[vendorcountrycode]
      ,[vendor_state_code]
      ,[prime_award_transaction_recipient_cd_original]
      ,[prime_award_transaction_recipient_cd_current]
      ,[vendorsitecode]
      ,[vendoralternatesitecode]
      ,[dunsnumber]
      ,[parentdunsnumber]
      --,[ParentPlatformPortfolio]
      --,[HasParentDunsnumber]
      --,[HasParentDunsnumberImputed]
      --,[SelfParentDunsnumber]
      --,[SelfParentDunsnumberImputed]
      --,[ParentDunsChildCount]
      --,[ParentDunsImputedChildCount]
      --,[DunsChildCount]
      ,[phoneno]
      ,[faxno]
      ,[registrationdate]
      ,[renewaldate]
      ,[mod_parent]
      ,[locationcode]
      ,[statecode]
      ,[pop_state_code]
      ,[placeofperformancecountrycode]
      ,[placeofperformancezipcode]
      ,[prime_award_transaction_place_of_performance_cd_original]
      ,[prime_award_transaction_place_of_performance_cd_current]
      ,[IsSiliconValley]
      ,[IsTraditionalSiliconValley]
      ,[psc_cat]
      ,[systemequipmentcode]
      ,[dod_acquisition_program_description]
      ,[ProjectID]
      ,[ProjectAbbreviation]
      ,[ProjectName]
      ,[IncludesMOSA]
      ,[ProjectPlatform]
      ,[IsRemotelyOperated]
      ,[PlatformPortfolioRemote]
      ,[IsEOsensor]
      ,[IsF35]
      ,[claimantprogramcode]
      ,[ClaimantProgramCodeText]
      ,[principalnaicscode]
      ,[principalnaicscodeText]
      ,[NAICS_ShortHand]
      --,[NASbioEconomy]
      --,[NASbioEconomypt]
      ,[gfe_gfp_code]
      ,[useofepadesignatedproducts]
      ,[recoveredmaterialclauses]
      ,[recoveredmaterialclausesText]
      ,[BioBased]
      ,[EnergyEfficient]
      ,[EnvironmentallyPreferable]
      ,[seatransportation]
      ,[contractbundling]
      ,[consolidatedcontract]
      ,[countryoforigin]
      ,[placeofmanufacture]
      ,[manufacturingorganizationtype]
      ,[agencyid]
      ,[piid]
      ,[modnumber]
      ,[transactionnumber]
      ,[idvagencyid]
      ,[idvpiid]
      ,[idvmodificationnumber]
      ,[solicitationid]
      ,[extentcompeted]
      ,[reasonnotcompeted]
      ,[commercialitemacquisitionprocedures]
      ,[commercialitemacquisitionproceduresText]
      ,[IsCommercialProcedures]
      ,[IsCommercialSimilar]
      ,[informationtechnologycommercialitemcategory]
      ,[informationtechnologycommercialitemcategoryText]
      ,[IsCommercialIT]
      ,[IsNonDevelopmental]
      ,[simplified_procedures_for_certain_commercial_items_code]
      ,[IsCommercialTest]
      ,[AnyCommercial]
      ,[smallbusinesscompetitivenessdemonstrationprogram]
      ,[a76action]
      ,[solicitationprocedures]
      ,[typeofsetaside]
      ,[evaluatedpreference]
      ,[fedbizopps]
      ,[research_code]
      ,[statutoryexceptiontofairopportunity]
      ,[firm8aflag]
      ,[hubzoneflag]
      ,[sdbflag]
      ,[issbacertifiedsmalldisadvantagedbusiness]
      ,[shelteredworkshopflag]
      ,[hbcuflag]
      ,[educationalinstitutionflag]
      ,[womenownedflag]
      ,[veteranownedflag]
      ,[srdvobflag]
      ,[localgovernmentflag]
      ,[minorityinstitutionflag]
      ,[aiobflag]
      ,[stategovernmentflag]
      ,[federalgovernmentflag]
      ,[minorityownedbusinessflag]
      ,[apaobflag]
      ,[tribalgovernmentflag]
      ,[baobflag]
      ,[naobflag]
      ,[saaobflag]
      ,[nonprofitorganizationflag]
      ,[isothernotforprofitorganization]
      ,[isforprofitorganization]
      ,[isfoundation]
      ,[haobflag]
      ,[ishispanicservicinginstitution]
      ,[emergingsmallbusinessflag]
      ,[hospitalflag]
      ,[contractingofficerbusinesssizedetermination]
      ,[is1862landgrantcollege]
      ,[is1890landgrantcollege]
      ,[is1994landgrantcollege]
      ,[isveterinarycollege]
      ,[isveterinaryhospital]
      ,[isprivateuniversityorcollege]
      ,[isschoolofforestry]
      ,[isstatecontrolledinstitutionofhigherlearning]
      ,[receivescontracts]
      ,[receivesgrants]
      ,[receivescontractsandgrants]
      ,[isairportauthority]
      ,[iscouncilofgovernments]
      ,[ishousingauthoritiespublicortribal]
      ,[isinterstateentity]
      ,[isplanningcommission]
      ,[isportauthority]
      ,[istransitauthority]
      ,[issubchapterscorporation]
      ,[islimitedliabilitycorporation]
      ,[isarchitectureandengineering]
      ,[isdotcertifieddisadvantagedbusinessenterprise]
      ,[iscitylocalgovernment]
      ,[iscommunitydevelopedcorporationownedfirm]
      ,[iscommunitydevelopmentcorporation]
      ,[isconstructionfirm]
      ,[ismanufacturerofgoods]
      ,[iscorporateentitynottaxexempt]
      ,[iscountylocalgovernment]
      ,[isdomesticshelter]
      ,[isfederalgovernmentagency]
      ,[isfederallyfundedresearchanddevelopmentcorp]
      ,[isindiantribe]
      ,[isintermunicipallocalgovernment]
      ,[islaborsurplusareafirm]
      ,[islocalgovernmentowned]
      ,[ismunicipalitylocalgovernment]
      ,[isnativehawaiianownedorganizationorfirm]
      ,[isotherbusinessororganization]
      ,[isotherminorityowned]
      ,[ispartnershiporlimitedliabilitypartnership]
      ,[isschooldistrictlocalgovernment]
      ,[issmallagriculturalcooperative]
      ,[issoleproprietorship]
      ,[istownshiplocalgovernment]
      ,[istriballyownedfirm]
      ,[istribalcollege]
      ,[isalaskannativeownedcorporationorfirm]
      ,[iscorporateentitytaxexempt]
      ,[iswomenownedsmallbusiness]
      ,[isecondisadvwomenownedsmallbusiness]
      ,[isjointventurewomenownedsmallbusiness]
      ,[isjointventureecondisadvwomenownedsmallbusiness]
      ,[walshhealyact]
      ,[servicecontractact]
      ,[davisbaconact]
      ,[clingercohenact]
      ,[otherstatutoryauthority]
      ,[interagencycontractingauthority]
      ,[CSISCreatedDate]
      ,[CSISModifiedDate]
      ,[numberofemployees]
      ,[annualrevenue]
      ,[CSIStransactionID]
      ,[PlaceofPerformanceCity]
      ,[prime_awardee_executive1]
      ,[prime_awardee_executive2]
      ,[prime_awardee_executive3]
      ,[prime_awardee_executive4]
      ,[prime_awardee_executive5]
      ,[prime_awardee_executive5_compensation]
      ,[prime_awardee_executive2_compensation]
      ,[prime_awardee_executive3_compensation]
      ,[prime_awardee_executive4_compensation]
      ,[prime_awardee_executive1_compensation]
      ,[last_modified_date]
      ,[TypeOfBusiness]
      ,[ContractActionTypeDD350]
      ,[headquartercode]
      ,[CAGE]
      ,[ContractNumber]
      ,[parent_award_type_code]
      ,[parent_award_single_or_multiple_code]
      ,[primary_place_of_performance_county_name]
      ,[indian_tribe_federally_recognized]
      ,[other_minority_owned_business]
      ,[community_developed_corporation_owned_firm]
      ,[labor_surplus_area_firm]
      ,[city_local_government]
      ,[county_local_government]
      ,[inter_municipal_local_government]
      ,[local_government_owned]
      ,[corporate_entity_not_tax_exempt]
      ,[international_organization]
      ,[us_government_entity]
      ,[community_development_corporation]
      ,[domestic_shelter]
      ,[manufacturer_of_goods]
      ,[alaskan_native_servicing_institution]
      ,[native_hawaiian_servicing_institution]
      ,[sba_certified_8a_joint_venture]
      ,[dot_certified_disadvantage]
      ,[award_or_idv_flag]
      ,[inherently_governmental_functions]
      ,[treasury_accounts_funding_this_award]
      ,[federal_accounts_funding_this_award]
      ,[usaspending_permalink]
      ,[awarding_agency_code]
      ,[maj_agency_cat]
      ,[mod_agency]
      ,[maj_fund_agency_cat]
      ,[contractingofficeagencyid]
      ,[fundingrequestingagencyid]
      ,[fundingrequestingofficeid]
      ,[fundedbyforeignentity]
      ,[ContractingCustomer]
      ,[ContractingIsDefense]
      ,[ContractingSubCustomer]
      ,[SubCustomer]
      ,[ContractingAgencyText]
      ,[ContractingAgencyID]
      ,[FundingAgency]
      ,[FundingSubAgency]
      ,[FundingAgencyText]
      ,[FundingAgencyID]
      ,[MajorCommandID]
      ,[ContractingOfficeID]
      ,[ContractingOfficeName]
      ,[ContractingOfficeCity]
      ,[ContractingOfficeState]
      ,[ContractingOfficeCountry]
      ,[ContractingOfficeStartDate]
      ,[ContractingOfficeEndDate]
      ,[ServicesCategory]
      ,[IsService]
      ,[Simple]
      ,[ProductOrServiceArea]
      ,[ProductServiceOrRnDarea]
      ,[DoDportfolio]
      ,[ProductOrServiceCode]
      ,[ProductOrServiceCodeText]
      ,[HostNation3Category]
      ,[IsPossibleSoftwareEngineering]
      ,[PlatformPortfolio]
      ,[foreign_owned]
      ,[isforeigngovernment]
      ,[isinternationalorganization]
      ,[organizationaltype]
      ,[PlaceIsInternational]
      ,[PlaceIsoAlpha3]
      ,[PlaceCountryText]
      ,[CrisisFundingTheater]
      ,[OriginIsoAlpha3]
      ,[OriginIsInternational]
      ,[OriginCountryText]
      ,[VendorIsoAlpha3]
      ,[VendorIsInternational]
      ,[VendorCountryText]
      ,[placeofmanufactureText]
      ,[IsManufacturedInUS]
      ,[IsForeignOrganization]
      ,[ManufacturingOrganizationText]
      ,[OriginUSAIDregion]
      ,[VendorUSAIDregion]
      ,[PlaceUSAIDregion]
      --,[GuessUSAIDregion]
      ,[VendorPlaceType]
      ,[VendorSize]
      ,[Small]
      ,[contractactiontype]
      ,[reasonformodification]
      ,[TypeofContractPricingtext]
      ,[ReasonNotIsfollowontocompetedaction]
      ,[is6_302_1exception]
      ,[reasonnotcompetedText]
      ,[isfollowontocompetedaction]
      ,[ExtentIsFullAndOpen]
      ,[ExtentIsSomeCompetition]
      ,[ExtentIsonlyonesource]
      ,[ExtentIsfollowontocompetedaction]
      ,[FairIsfollowontocompetedaction]
      ,[FairIsonlyonesource]
      ,[FairIsSomeCompetition]
      ,[statutoryexceptiontofairopportunityText]
      ,[FairIsUrgency]
      ,[typeofsetaside2category]
      ,[NumberOfOffersReceived]
      ,[CompetitionClassification]
      ,[VehicleClassification]
      ,[ClassifyNumberOfOffers]
      ,[IsUrgency]
      ,[UseFairOpportunity]
      ,[multipleorsingleawardidc]
      ,[Award_Type_Code]
      ,[idv_type_code]
      ,[Award_Type_Name]
      ,[Award_Type_Abbreviation]
      ,[idv_type_Name]
      ,[idv_type_Abbreviation]
      ,[PCAUidv_type_code]
      ,[GPCAUidv_type_code]
      ,[PCAUparent_award_single_or_multiple_code]
      ,[GPCAUparent_award_single_or_multiple_code]
      ,[IDVtypeofIDC]
      ,[IsModified]
      ,[IsUndefinitizedAction]
      ,[IsLetterContract]
      ,[ContingencyHumanitarianPeacekeepingOperation]
      ,[ContingencyHumanitarianPeacekeepingOperationText]
      --,[ConHumIsOCOcrisisFunding]
      ,[ContractCrisisFunding]
      ,[nationalinterestactioncode]
      ,[national_interest_action_name]
      --,[IsHurricane]
      --,[IsDisease]
      --,[NIAcrisisFunding]
      --,[RFisARRA]
      --,[CrisisFunding]
      ,[localareasetaside]
      ,[CCRexception]
      --,[pscOCOcrisisScore]
      --,[placeOCOcrisisScore]
      ,[IsOMBocoList]
      ,[isforeign]
      --,[pscOCOcrisisPercent]
      --,[pscOCOcrisisPoint]
      --,[PercentFundingAccountOCO]
      --,[FundingAccountOCOpoint]
      --,[OfficeOCOcrisisScore]
      --,[OfficeOCOcrisisPercent]
      --,[OfficeOCOcrisisPoint]
      ,[OMBagencycode]
      ,[OMBbureaucode]
      ,[OMBaccountName]
      ,[treasuryagencycode]
      ,[mainaccountcode]
      ,[subaccountcode]
      ,[AccountTitle]
      ,[MainAccountTitle]
      ,[SubAccountTitle]
      ,[foreign_funding_description]
      ,[IsFMS]
      ,[IsFMSmac]
      ,[IsFMSml]
      ,[disaster_emergency_fund_codes_for_overall_award]
      ,[object_classes_funding_this_award]
      ,[program_activities_funding_this_award]
      ,[obligated_amount_funded_by_COVID19_supplementals_for_overall_award]
      ,[outlayed_amount_funded_by_COVID19_supplementals_for_overall_award]
  FROM [Contract].[FPDSpartial]
  where IsPerformanceBasedLogistics=1