---
title: "UEI Graphing"
author: "Greg Sanders"
date: "November 21, 2025"
output: html_document
---
# Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(tidyverse)
library(ggplot2)
library(csis360)
library(readr)
load(file=file.path("..","data","clean","RecipientUEI.rda"))
# 
# online_path<-file.path(get_local_sharepoint_path("DIIG Teamsite - Shared Documents"),"2024 - Acquisition Trends","Data and Figures")

```


# NTDC
### Using Parent UEI
```{r def_rpuh}

  (
  ntdc_count_bar<-build_plot(
    data=def_rpuh %>% dplyr::filter(IsEntityAbove2018constantMTAthreshold==1
                                          & Fiscal_Year>=2007& Fiscal_Year<=2025), ##where is FPDS summary?
    chart_geom = "Bar Chart",
    share = FALSE,
    x_var="dFYear",alpha_var="YTD",
    y_var="count", #Name of variable to plot on y-axis
    color_var="LargestContract2018dollars",       # name of coloration variable, as string
    facet_var="IsEntityTraditionalLabel",        # name of facet variable, as string
    legend=TRUE, #Include a legend
    caption=TRUE, #Include a source caption
        labels_and_colors=rpuh_lc,
    column_key=rpuh_ck,
    format=TRUE
  )+labs(y="Count of Vendors with\nContracts Above $10 K",x="Fiscal Year",
         title="DOD Contractor Count by Small Business Status\nand Size of Largest Federal Contract",
         caption="Note: Threshold values are adjusted for inflation (in 2018 $s).\nSource: FPDS Unique Entities (UEI) and CSIS analysis. YTD through 90 days prior to 8/8/2025.")+
    date_x_year_breaks(2007,2022,3,partial_year=2025,partial_label="\nYTD")+date_x_year_breaks(2007,2022,3,partial_year=2025,partial_label="\nYTD")+facet_wrap(~IsEntityTraditionalLabel, scales="free_y")
  )


  (
  ntdc_count_bar_tall<-build_plot(
    data=def_rpuh %>% dplyr::filter(IsEntityAbove2018constantMTAthreshold==1
                                          & Fiscal_Year>=2007& Fiscal_Year<=2025), ##where is FPDS summary?
    chart_geom = "Bar Chart",
    share = FALSE,
    x_var="dFYear",alpha_var="YTD",
    y_var="count", #Name of variable to plot on y-axis
    color_var="LargestContract2018dollars",       # name of coloration variable, as string
    facet_var="IsEntityTraditionalLabel",        # name of facet variable, as string
    legend=TRUE, #Include a legend
    caption=TRUE, #Include a source caption
        labels_and_colors=rpuh_lc,
    column_key=rpuh_ck,
    format=TRUE
  )+labs(y="Count of Vendors with\nContracts Above $10 K",x="Fiscal Year",
         title="DOD Contractor Count by Small Business Status\nand Size of Largest Federal Contract, FY 2007-FY 2025 YTD",
         caption="Note: Threshold values are adjusted for inflation (in 2018 $s).\nSource: FPDS Unique Entities (UEI) and CSIS analysis. YTD through 90 days prior to 8/8/2025.")+
    date_x_year_breaks(2007,2022,3,partial_year=2025,partial_label="\nYTD")+date_x_year_breaks(2007,2022,3,partial_year=2025,partial_label="\nYTD")+facet_wrap(~IsEntityTraditionalLabel, scales="free_y")+
      facet_grid(IsEntityTraditionalLabel~.,space="free_y",scale="free_y")+theme(strip.text.y = element_text(angle=0))
  )

# log_plot(plot=ntdc_count_bar, df=def_rpuh %>% dplyr::filter(IsEntityAbove2018constantMTAthreshold==1
#                                           & Fiscal_Year>=2007& Fiscal_Year<=2025),#%>% filter(Fiscal_YQ<=2023.2)
#                      filename="def_vendor_count",xlsx="DoD_2025_NPS.xlsx",
#                      sheet="DIB count",path="../output/AcqTrends/NPS2025/", 
#          second_path=online_path,
#          height=3.5,
#          csv_then_year=FALSE  ,excel_then_year=FALSE,excel_y_var=TRUE,
#            output_doc_png = TRUE,
#          excel_formulas = TRUE,
#                      startRow=1,format=TRUE,#,var_list=c("SimpleArea","Competition.multisum"),
#          output_doc_png = TRUE,
#          include_YTD = FALSE,
#          num_format = "0.00,\"K\""
#          )

(
  ntdc_count_line<-build_plot(
    data=def_rpuh %>% dplyr::filter(IsEntityAbove2018constantMTAthreshold==1
                                          & Fiscal_Year>=2007& Fiscal_Year<=2025), ##where is FPDS summary?
    chart_geom = "Line Chart",
    share = FALSE,
    x_var="dFYear",alpha_var="YTD",
    y_var="count", #Name of variable to plot on y-axis
    color_var="LargestContract2018dollars",       # name of coloration variable, as string
    facet_var="IsEntityTraditionalLabel",        # name of facet variable, as string
    legend=TRUE, #Include a legend
    caption=TRUE, #Include a source caption
    labels_and_colors=rpuh_lc,
    column_key=rpuh_ck,
    format=TRUE
  )+labs(y="Count of Vendors with\nContracts Above $10 K",x="Fiscal Year",
         title="DOD Contractor Count by Small Business Status\n and Size of Largest Federal Contract",
         caption="Note: Threshold values are adjusted for inflation (in 2018 $s).\nSource: FPDS Unique Entities (UEI) and CSIS analysis. YTD through 90 days prior to 8/8/2025.")+date_x_year_breaks(2007,2022,3,partial_year=2025,partial_label="\nYTD")
  )




  (
  all_10k_small_bar<-build_plot(
    data=def_rpuh %>% dplyr::filter(IsEntityAbove2018constantMTAthreshold==1
                                          & Fiscal_Year>=2007& Fiscal_Year<=2025), ##where is FPDS summary?
    chart_geom = "Bar Chart",
    share = FALSE,
    x_var="Fiscal_Year",
    y_var="count", #Name of variable to plot on y-axis
    color_var="LargestContract2018dollars",       # name of coloration variable, as string
    facet_var="AlwaysIsSmallLabel",        # name of facet variable, as string
    second_var="IsEntityTraditionalLabel",
    legend=TRUE, #Include a legend
    caption=TRUE, #Include a source caption
    labels_and_colors=rpuh_lc,
    column_key=rpuh_ck,
    format=TRUE
  )+labs(y="Count of vendors with contracts above $10k in 2018 $s",x="Fiscal Year")
  )



def_rpuh<-def_rpuh %>% mutate(
  ntdc_label=case_when(
    AlwaysIsSmall==1 | IsEntityAbove2018constantCommercialItem7500k==0
    ~ "Consistently Small or\nLargest Contract\nUnder $7.5 M",
    TRUE ~ "Variably Small / Larger\nand Largest Contract\nOver $7.5 M"
  )
)
summary(factor(def_rpuh$ntdc_label))

rpuh_lc<-prepare_labels_and_colors(def_rpuh)
rpuh_ck<-get_column_key(def_rpuh)


  (
  ntdc<-build_plot(
    data=def_rpuh %>% dplyr::filter( Fiscal_Year>=2007 & Fiscal_Year<=2025), ##where is FPDS summary?
    
    chart_geom = "Bar Chart",
    share = FALSE,
    x_var="Fiscal_Year",
    y_var="DefenseObligated_OMB25_GDP23", #Name of variable to plot on y-axis
    color_var="ntdc_label",       # name of coloration variable, as string
    facet_var="IsEntityTraditionalLabel",        # name of facet variable, as string
    # second_var="IsEntityTraditionalLabel",
    legend=TRUE, #Include a legend
    caption=TRUE, #Include a source caption
    labels_and_colors=rpuh_lc,
    column_key=rpuh_ck,
    format=TRUE
  )+labs(y="Obligations (2023 $s)",x="Fiscal Year")#+
      # facet_grid(IsEntityTraditionalLabel~ntdc_label)
  )



  # log_plot(plot=ntdc+labs(title=NULL)+theme(legend.position = "right"),
  #          df=def_rpuh %>% dplyr::filter(
  #                                           Fiscal_Year>=2007& Fiscal_Year<=2025),#%>% filter(Fiscal_YQ<=2023.2)
  #          second_path=online_path,
  #                      filename="nps_fig8_ntdc_obl",xlsx="DoD_2025_NPS.xlsx",
  #                      sheet="8 NTDC",path="../output/AcqTrends/NPS2025/",
  #          height=3.5,
  #          excel_formulas=TRUE,
  #                      startRow=1,format=TRUE,#,var_list=c("SimpleArea","Competition.multisum"),
  #          output_doc_png = TRUE
  #          )
```


### Using CAU
#### NTDC investigting CAS
```{r NTDC_cas}
  (
  build_plot(
    data=cas, #%>% dplyr::filter(IsEntityAbove2018constantMTAthreshold==1
                                          # & Fiscal_Year>=2007& Fiscal_Year<=2025), ##where is FPDS summary?
    chart_geom = "Bar Chart",
    share = FALSE,
    x_var="Fiscal_Year",
    y_var="Action_Obligation_OMB25_GDP23", #Name of variable to plot on y-axis
    color_var="costorpricingdata",       # name of coloration variable, as string
    facet_var="CostAccountingStandardsClause",        # name of facet variable, as string
    # second_var="CASexemption",
    legend=TRUE, #Include a legend
    caption=TRUE, #Include a source caption
    # labels_and_colors=rpuh_lc,
    # column_key=rpuh_ck,
    format=TRUE,
    first_color_on_bottom=FALSE
  ))+labs(title="costorpricingdata")+facet_wrap(~CostAccountingStandardsClause,scale="free_y")


colnames(cas)

  (
  build_plot(
    data=cas, #%>% dplyr::filter(IsEntityAbove2018constantMTAthreshold==1
                                          # & Fiscal_Year>=2007& Fiscal_Year<=2025), ##where is FPDS summary?
    chart_geom = "Bar Chart",
    share = FALSE,
    x_var="Fiscal_Year",
    y_var="Action_Obligation_OMB25_GDP23", #Name of variable to plot on y-axis
    color_var="AlwaysCAUisCASexemptOrWaived",       # name of coloration variable, as string
    facet_var="CostAccountingStandardsClause",        # name of facet variable, as string
    # second_var="CASexemption",
    legend=TRUE, #Include a legend
    caption=TRUE, #Include a source caption
    # labels_and_colors=rpuh_lc,
    # column_key=rpuh_ck,
    format=TRUE,
    first_color_on_bottom=FALSE
  ))+labs(title="AlwaysCAUisCASexemptOrWaived")+facet_wrap(~CostAccountingStandardsClause,scale="free_y")


  (
  build_plot(
    data=cas, #%>% dplyr::filter(IsEntityAbove2018constantMTAthreshold==1
                                          # & Fiscal_Year>=2007& Fiscal_Year<=2025), ##where is FPDS summary?
    chart_geom = "Bar Chart",
    share = FALSE,
    x_var="Fiscal_Year",
    y_var="Action_Obligation_OMB25_GDP23", #Name of variable to plot on y-axis
    color_var="AlwaysIsSmall",       # name of coloration variable, as string
    facet_var="CostAccountingStandardsClause",        # name of facet variable, as string
    # second_var="CASexemption",
    legend=TRUE, #Include a legend
    caption=TRUE, #Include a source caption
    # labels_and_colors=rpuh_lc,
    # column_key=rpuh_ck,
    format=TRUE,
    first_color_on_bottom=FALSE
  ))+labs(title="AlwaysIsSmall")+facet_wrap(~CostAccountingStandardsClause,scale="free_y")


  (
  build_plot(
    data=cas, #%>% dplyr::filter(IsEntityAbove2018constantMTAthreshold==1
                                          # & Fiscal_Year>=2007& Fiscal_Year<=2025), ##where is FPDS summary?
    chart_geom = "Bar Chart",
    share = FALSE,
    x_var="Fiscal_Year",
    y_var="Action_Obligation_OMB25_GDP23", #Name of variable to plot on y-axis
    color_var="IsAbove2018constantCostAccounting2000kThreshold",       # name of coloration variable, as string
    facet_var="CostAccountingStandardsClause",        # name of facet variable, as string
    # second_var="CASexemption",
    legend=TRUE, #Include a legend
    caption=TRUE, #Include a source caption
    # labels_and_colors=rpuh_lc,
    # column_key=rpuh_ck,
    format=TRUE,
    first_color_on_bottom=FALSE
  ))+labs(title="IsAbove2018constantCostAccounting2000kThreshold")+facet_wrap(~CostAccountingStandardsClause,scale="free_y")


```

#### NTDC confident
```{r NTDC_confident}
  
  (
  build_plot(
    data=cas, #%>% dplyr::filter(IsEntityAbove2018constantMTAthreshold==1
                                          # & Fiscal_Year>=2007& Fiscal_Year<=2025), ##where is FPDS summary?
    chart_geom = "Bar Chart",
    share = FALSE,
    x_var="Fiscal_Year",
    y_var="Action_Obligation_OMB25_GDP23", #Name of variable to plot on y-axis
    color_var="isforeigngovernment",       # name of coloration variable, as string
    facet_var="CostAccountingStandardsClause",        # name of facet variable, as string
    # second_var="CASexemption",
    legend=TRUE, #Include a legend
    caption=TRUE, #Include a source caption
    # labels_and_colors=rpuh_lc,
    # column_key=rpuh_ck,
    format=TRUE,
    first_color_on_bottom=FALSE
  ))+labs(title="isforeigngovernment")



  (
  build_plot(
    data=cas, #%>% dplyr::filter(IsEntityAbove2018constantMTAthreshold==1
                                          # & Fiscal_Year>=2007& Fiscal_Year<=2025), ##where is FPDS summary?
    chart_geom = "Bar Chart",
    share = FALSE,
    x_var="Fiscal_Year",
    y_var="Action_Obligation_OMB25_GDP23", #Name of variable to plot on y-axis
    color_var="IsSealedBid",       # name of coloration variable, as string
    facet_var="CostAccountingStandardsClause",        # name of facet variable, as string
    # second_var="CASexemption",
    legend=TRUE, #Include a legend
    caption=TRUE, #Include a source caption
    # labels_and_colors=rpuh_lc,
    # column_key=rpuh_ck,
    format=TRUE,
    first_color_on_bottom=FALSE
  ))+labs(title="IsSealedBid")



  (
  build_plot(
    data=cas, #%>% dplyr::filter(IsEntityAbove2018constantMTAthreshold==1
                                          # & Fiscal_Year>=2007& Fiscal_Year<=2025), ##where is FPDS summary?
    chart_geom = "Bar Chart",
    share = FALSE,
    x_var="Fiscal_Year",
    y_var="Action_Obligation_OMB25_GDP23", #Name of variable to plot on y-axis
    color_var="IsAbove2018constantCommercialItem7500k",       # name of coloration variable, as string
    facet_var="CostAccountingStandardsClause",        # name of facet variable, as string
    # second_var="CASexemption",
    legend=TRUE, #Include a legend
    caption=TRUE, #Include a source caption
    # labels_and_colors=rpuh_lc,
    # column_key=rpuh_ck,
    format=TRUE,
    first_color_on_bottom=FALSE
  ))+labs(title="IsAbove2018constantCommercialItem7500k")

  (
  build_plot(
    data=cas, #%>% dplyr::filter(IsEntityAbove2018constantMTAthreshold==1
                                          # & Fiscal_Year>=2007& Fiscal_Year<=2025), ##where is FPDS summary?
    chart_geom = "Bar Chart",
    share = FALSE,
    x_var="Fiscal_Year",
    y_var="Action_Obligation_OMB25_GDP23", #Name of variable to plot on y-axis
    color_var="FixedPriceEffective",       # name of coloration variable, as string
    facet_var="CostAccountingStandardsClause",        # name of facet variable, as string
    # second_var="CASexemption",
    legend=TRUE, #Include a legend
    caption=TRUE, #Include a source caption
    # labels_and_colors=rpuh_lc,
    # column_key=rpuh_ck,
    format=TRUE,
    first_color_on_bottom=FALSE
  ))+labs(title="FixedPriceEffective")



colnames(cas)

  (
  build_plot(
    data=cas, #%>% dplyr::filter(IsEntityAbove2018constantMTAthreshold==1
                                          # & Fiscal_Year>=2007& Fiscal_Year<=2025), ##where is FPDS summary?
    chart_geom = "Bar Chart",
    share = FALSE,
    x_var="Fiscal_Year",
    y_var="Action_Obligation_OMB25_GDP23", #Name of variable to plot on y-axis
    color_var="IsCommercialitemacquisitionprocedures",       # name of coloration variable, as string
    facet_var="CostAccountingStandardsClause",        # name of facet variable, as string
    # second_var="CASexemption",
    legend=TRUE, #Include a legend
    caption=TRUE, #Include a source caption
    # labels_and_colors=rpuh_lc,
    # column_key=rpuh_ck,
    format=TRUE,
    first_color_on_bottom=FALSE
  ))+labs(title="IsCommercialitemacquisitionprocedures")


```

#### NTDC label
```{r NTDC_label}

(
  ntdc_size_label<-build_plot(
    data=cas %>% filter (Fiscal_Year>=2007& Fiscal_Year<=2025), #%>% dplyr::filter(IsEntityAbove2018constantMTAthreshold==1
                                          # & Fiscal_Year>=2007& Fiscal_Year<=2025), ##where is FPDS summary?
    chart_geom = "Bar Chart",
    share = FALSE,
    x_var="dFYear",alpha_var="YTD",
    y_var="Action_Obligation_OMB25_GDP23", #Name of variable to plot on y-axis
    color_var="cas_label",       # name of coloration variable, as string
    facet_var="ntdc_label",        # name of facet variable, as string
    second_var="IsEntityTraditionalLabel",
    legend=TRUE, #Include a legend
    caption=TRUE, #Include a source caption
    labels_and_colors=cas_lc,
    column_key=cas_ck,
    format=TRUE,
    first_color_on_bottom=FALSE
  )+date_x_year_breaks(2007,2022,3,partial_year=2025,partial_label="\nYTD")+
    theme(legend.position = "right")+
      facet_grid(IsEntityTraditionalLabel~ntdc_label)+
  labs(title="AlwaysCAUisCASexemptOrWaived",
                                          y="Obligations (2023 $s)",x="Fiscal Year"))



(
  ntdc_label<-build_plot(
    data=cas %>% filter (Fiscal_Year>=2007& Fiscal_Year<=2025), #%>% dplyr::filter(IsEntityAbove2018constantMTAthreshold==1
                                          # & Fiscal_Year>=2007& Fiscal_Year<=2025), ##where is FPDS summary?
    chart_geom = "Bar Chart",
    share = FALSE,
    x_var="dFYear",alpha_var="YTD",
    y_var="Action_Obligation_OMB25_GDP23", #Name of variable to plot on y-axis
    color_var="cas_label",       # name of coloration variable, as string
    facet_var="IsEntityTraditionalLabel",        # name of facet variable, as string
    # second_var="ntdc_label",
    legend=TRUE, #Include a legend
    caption=TRUE, #Include a source caption
    labels_and_colors=cas_lc,
    column_key=cas_ck,
    format=TRUE,
    first_color_on_bottom=FALSE
  )+theme(legend.position = "right")+
  labs(title="DOD Contract Obligations by Non-Traditional Status and\nCost Accounting Standards Exemption, FY 2007-FY 2025 YTD",y="Obligations (2023 $s)",x="Fiscal Year")+date_x_year_breaks(2007,2022,3,partial_year=2025,partial_label="\nYTD"))



  log_plot(plot=ntdc_label+theme(legend.position = "right"),
           df=cas %>% dplyr::filter(
                                            Fiscal_Year>=2007& Fiscal_Year<=2025),#%>% filter(Fiscal_YQ<=2023.2)
           # second_path=online_path,
                       filename="nps_fig11_ntdc_obl",xlsx="DoD_2025_NPS.xlsx",
                       sheet="11 NTDC",path="../output/AcqTrends/NPS2025/",
           height=3.5,
           excel_formulas=TRUE,excel_y_var = TRUE,
           
             suppress_doc_svg_text="title",output_slide_png=TRUE,
                       startRow=1,format=TRUE,#,var_list=c("SimpleArea","Competition.multisum"),
           output_doc_png = TRUE
           )
  
if(nrow(cas %>% filter((IsEntityTraditional==0) & CostAccountingStandardsClause=="Y"))>0){
  View(cas %>% filter(IsEntityTraditional==0 & CostAccountingStandardsClause=="Y"))
  warning("CAS contraction, CAS applied to non-traditional")
}
  
  
    

```

