---
title: "Defense Acquisition Trends"
output:
  html_document:
    keep_md: yes
    toc: yes
date: "Thursday, March 4, 2031"
---

# Setup
First we load the data. The dataset used is a U.S. Defense Contracting dataset derived from   FPDS.

```{r Libraries, echo = FALSE}
library(csis360)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(scales)

axis.text.size<-10
strip.text.size<-10
legend.text.size<-8
# table.text.size<-5.75
title.text.size<-12
geom.text.size<-12

main.text.size<-1
note.text.size<-1.40
if(!exists("full_data"))
  load(file="FPDS_chart_maker//unaggregated_FPDS.Rda")

```

# Topline

## Topline Product/Service/R&D
```{r ToplinePSR}

(
ToplinePSR<-build_plot(
  data=full_data,
  chart_geom = "Bar Chart",
  share = FALSE,
  labels_and_colors=labels_and_colors,
  # NA, #VAR.ncol
  x_var="fiscal_year", #x_var
  y_var="Action_Obligation_OMB19_19", #VAR.y.variable
  color_var="ProductServiceOrRnDarea.sum", #color_var
  # facet_var="Competition.sum", #facet_var
  column_key=column_key,
  format=TRUE,
  ytextposition=FALSE
)+
  # theme(strip.text.y = element_text(angle=0))+
 # theme(axis.text.x = element_text(angle=90))+
 #    scale_y_continuous("Percent of Obligations", labels = percent_format(accuracy=1))+
 #      facet_grid(.~Competition.sum ,scales="free_x", space="free_x"
 #             )+labs(title=NULL,
  # x="Fiscal Year",
  # y="Percent of Obligations",
  # color="Competition")+
  theme(legend.position = "right")+
  labs(y="Obligations (Constant 2019 $s)")
)

ggsave600dpi("..//Output//topline_psr.png", ToplinePSR, 
             width=6.5, height= 4, units="in",size=11
             )

```

## Topline Competition
```{r ToplineComp}

(
ToplineComp<-build_plot(
  data=full_data,
  chart_geom = "Bar Chart",
  share = FALSE,
  labels_and_colors=labels_and_colors,
  # NA, #VAR.ncol
  x_var="fiscal_year", #x_var
  y_var="Action_Obligation_OMB19_19", #VAR.y.variable
  color_var="Competition.sum", #color_var
  # facet_var="Competition.sum", #facet_var
  column_key=column_key,
  format=TRUE,
  ytextposition=FALSE
)+
  # theme(strip.text.y = element_text(angle=0))+
 # theme(axis.text.x = element_text(angle=90))+
 #    scale_y_continuous("Percent of Obligations", labels = percent_format(accuracy=1))+
 #      facet_grid(.~Competition.sum ,scales="free_x", space="free_x"
 #             )+labs(title=NULL,
  # x="Fiscal Year",
  # y="Percent of Obligations",
  # color="Competition")+
  theme(legend.position = "right")+
  labs(y="Obligations (Constant 2019 $s)")
)

ggsave600dpi("..//Output//topline_comp.png", ToplineComp, 
             width=6.5, height= 4, units="in",size=11
             )

```


## Topline Vendor Size
```{r ToplineComp}

(
ToplineVendor<-build_plot(
  data=full_data,
  chart_geom = "Bar Chart",
  share = FALSE,
  labels_and_colors=labels_and_colors,
  # NA, #VAR.ncol
  x_var="dFYear", #x_var
  y_var="Action_Obligation_OMB19_19", #VAR.y.variable
  color_var="Shiny.VendorSize", #color_var
  # facet_var="Competition.sum", #facet_var
  column_key=column_key,
  format=TRUE,
  ytextposition=FALSE
)+scale_x_date("Fiscal Year",labels = date_format("'%y"))+
  # theme(strip.text.y = element_text(angle=0))+
 # theme(axis.text.x = element_text(angle=90))+
 #    scale_y_continuous("Percent of Obligations", labels = percent_format(accuracy=1))+
 #      facet_grid(.~Competition.sum ,scales="free_x", space="free_x"
 #             )+labs(title=NULL,
  # x="Fiscal Year",
  # y="Percent of Obligations",
  # color="Competition")+
  theme(legend.position = "right")+
  labs(y="Obligations (Constant 2019 $s)")
)

ggsave600dpi("..//Output//topline_vendor.png", ToplineVendor, 
             width=6.5, height= 4, units="in",size=11
             )

```
## Topline Vehicle
```{r ToplineVehicle}

(
ToplineVehicle<-build_plot(
  data=full_data,
  chart_geom = "Bar Chart",
  share = FALSE,
  labels_and_colors=labels_and_colors,
  # NA, #VAR.ncol
  x_var="dFYear", #x_var
  y_var="Action_Obligation_OMB19_19", #VAR.y.variable
  color_var="Shiny.VendorSize", #color_var
  facet_var="Vehicle", #facet_var
  column_key=column_key,
  format=TRUE,
  ytextposition=FALSE
)+scale_x_date("Fiscal Year",labels = date_format("'%y"))+
  # theme(strip.text.y = element_text(angle=0))+
 # theme(axis.text.x = element_text(angle=90))+
 #    scale_y_continuous("Percent of Obligations", labels = percent_format(accuracy=1))+
 #      facet_grid(.~Competition.sum ,scales="free_x", space="free_x"
 #             )+labs(title=NULL,
  # x="Fiscal Year",
  # y="Percent of Obligations",
  # color="Competition")+
  theme(legend.position = "right")+
  labs(y="Obligations (Constant 2019 $s)")
)

ggsave600dpi("..//Output//topline_vehicle.png", ToplineVehicle, 
             width=13, height= 4.5, units="in",size=11
             )

```


## Topline Pricing
```{r ToplinePricing}

(
ToplinePricing<-build_plot(
  data=full_data,
  chart_geom = "Bar Chart",
  share = FALSE,
  labels_and_colors=labels_and_colors,
  # NA, #VAR.ncol
  x_var="dFYear", #x_var
  y_var="Action_Obligation_OMB19_19", #VAR.y.variable
  color_var="PricingUCA", #color_var
  facet_var="PricingUCA.sum", #facet_var
  column_key=column_key,
  format=TRUE,
  ytextposition=FALSE
)+scale_x_date("Fiscal Year",labels = date_format("'%y"))+
  # theme(strip.text.y = element_text(angle=0))+
 # theme(axis.text.x = element_text(angle=90))+
 #    scale_y_continuous("Percent of Obligations", labels = percent_format(accuracy=1))+
 #      facet_grid(.~Competition.sum ,scales="free_x", space="free_x"
 #             )+labs(title=NULL,
  # x="Fiscal Year",
  # y="Percent of Obligations",
  # color="Competition")+
  theme(legend.position = "right")+
  labs(y="Obligations (Constant 2019 $s)")
)

ggsave600dpi("..//Output//topline_pricing.png", ToplinePricing, 
             width=6.5, height= 4, units="in",size=11
             )

```

# SubCustomer
## SubCustomer Product/Service/R&D
```{r SubCustomerPSR}

(
SubCustomerPSR<-build_plot(
  data=full_data,
  chart_geom = "Bar Chart",
  share = FALSE,
  labels_and_colors=labels_and_colors,
  # NA, #VAR.ncol
  x_var="fiscal_year", #x_var
  y_var="Action_Obligation_OMB19_19", #VAR.y.variable
  color_var="ProductServiceOrRnDarea.sum", #color_var
  facet_var="SubCustomer.sum", #facet_var
  column_key=column_key,
  format=TRUE,
  ytextposition=FALSE
)+
  # theme(strip.text.y = element_text(angle=0))+
 # theme(axis.text.x = element_text(angle=90))+
 #    scale_y_continuous("Percent of Obligations", labels = percent_format(accuracy=1))+
 #      facet_grid(.~Competition.sum ,scales="free_x", space="free_x"
 #             )+labs(title=NULL,
  # x="Fiscal Year",
  # y="Percent of Obligations",
  # color="Competition")+
  theme(legend.position = "bottom")+
  labs(y="Obligations (Constant 2019 $s)")
)

# ggsave600dpi("..//Output//subcustomer_PSR.png", SubCustomerPSR, 
#              width=6.5, height= 4, units="in",size=11
#              )
ggsave600dpi("..//Output//subcustomer_PSR.png", Platform, 
             width=12, height= 6, units="in",size=11,lineheight = 1.2
             )
```



# Platform
## Platform
```{r Platform}

(
Platform<-build_plot(
  data=full_data,
  chart_geom = "Line Chart",
  share = FALSE,
  labels_and_colors=labels_and_colors,
  # NA, #VAR.ncol
  x_var="dFYear", #x_var
  y_var="Action_Obligation_OMB19_19", #VAR.y.variable
  color_var="PlatformPortfolio", #color_var
  facet_var="PlatformPortfolio", #facet_var
  column_key=column_key,
  format=TRUE,
  ytextposition=FALSE
)+scale_x_date("Fiscal Year",labels = date_format("'%y"))+
  # theme(strip.text.y = element_text(angle=0))+
 # theme(axis.text.x = element_text(angle=90))+
 #    scale_y_continuous("Percent of Obligations", labels = percent_format(accuracy=1))+
 #      facet_grid(.~Competition.sum ,scales="free_x", space="free_x"
 #             )+labs(title=NULL,
  # x="Fiscal Year",
  # y="Percent of Obligations",
  # color="Competition")+
  theme(legend.position = "none")+
  labs(y="Obligations (Constant 2019 $s)")
)

ggsave600dpi("..//Output//platform.png", Platform, 
             width=12, height= 6, units="in",size=11,lineheight = 1.2
             )

```



## Platform SubCustomer
```{r PlatformSubCustomer}

(
PlatformSubCustomer<-build_plot(
  data=full_data,
  chart_geom = "Bar Chart",
  share = FALSE,
  labels_and_colors=labels_and_colors,
  # NA, #VAR.ncol
  x_var="dFYear", #x_var
  y_var="Action_Obligation_OMB19_19", #VAR.y.variable
  color_var="SubCustomer.platform", #color_var
  facet_var="PlatformPortfolio", #facet_var
  column_key=column_key,
  format=TRUE,
  ytextposition=FALSE
)+scale_x_date("Fiscal Year",labels = date_format("'%y"))+
  # theme(strip.text.y = element_text(angle=0))+
 # theme(axis.text.x = element_text(angle=90))+
 #    scale_y_continuous("Percent of Obligations", labels = percent_format(accuracy=1))+
 #      facet_grid(.~Competition.sum ,scales="free_x", space="free_x"
 #             )+labs(title=NULL,
  # x="Fiscal Year",
  # y="Percent of Obligations",
  # color="Competition")+
  theme(legend.position = "bottom")+
  labs(y="Obligations (Constant 2019 $s)")
)

ggsave600dpi("..//Output//platform_subcustomer.png", PlatformSubCustomer, 
             width=6.5, height= 4, units="in",size=11,lineheight = 0.75
             )

```

## Platform PSR
```{r PlatformPSR}

(
PlatformPSR<-build_plot(
  data=full_data,
  chart_geom = "Bar Chart",
  share = FALSE,
  labels_and_colors=labels_and_colors,
  # NA, #VAR.ncol
  x_var="dFYear", #x_var
  y_var="Action_Obligation_OMB19_19", #VAR.y.variable
  color_var="ProductServiceOrRnDarea.sum", #color_var
  facet_var="PlatformPortfolio", #facet_var
  column_key=column_key,
  format=TRUE,
  ytextposition=FALSE
)+scale_x_date("Fiscal Year",labels = date_format("'%y"))+
  # theme(strip.text.y = element_text(angle=0))+
 # theme(axis.text.x = element_text(angle=90))+
 #    scale_y_continuous("Percent of Obligations", labels = percent_format(accuracy=1))+
 #      facet_grid(.~Competition.sum ,scales="free_x", space="free_x"
 #             )+labs(title=NULL,
  # x="Fiscal Year",
  # y="Percent of Obligations",
  # color="Competition")+
  theme(legend.position = "bottom")+
  labs(y="Obligations (Constant 2019 $s)")
)

ggsave600dpi("..//Output//platform_PSR.png", PlatformPSR, 
             width=6.5, height= 4, units="in",size=11,lineheight = 0.75
             )

```





## Platform Vendor
```{r PlatformPSR}

(
PlatformVendor<-build_plot(
  data=full_data %>% filter(PlatformPortfolio!="Unlabeled" ) ,
  chart_geom = "Bar Chart",
  share = TRUE,
  labels_and_colors=labels_and_colors,
  # NA, #VAR.ncol
  x_var="dFYear", #x_var
  y_var="Action_Obligation_OMB19_19", #VAR.y.variable
  color_var="Shiny.VendorSize", #color_var
  facet_var="PlatformPortfolio", #facet_var
  column_key=column_key,
  format=TRUE,
  ytextposition=FALSE
)+scale_x_date("Fiscal Year",labels = date_format("'%y"))+
  # theme(strip.text.y = element_text(angle=0))+
 # theme(axis.text.x = element_text(angle=90))+
 #    scale_y_continuous("Percent of Obligations", labels = percent_format(accuracy=1))+
 #      facet_grid(.~Competition.sum ,scales="free_x", space="free_x"
 #             )+labs(title=NULL,
  # x="Fiscal Year",
  # y="Percent of Obligations",
  # color="Competition")+
  theme(legend.position = "bottom")+
  labs(y="Obligations (Constant 2019 $s)")
)

ggsave600dpi("..//Output//platform_vendor.png", PlatformVendor, 
             width=6.5, height= 4, units="in",size=11,lineheight = 0.75
             )

```



## Platform Comp
```{r PlatformPSR}

(
PlatformComp<-build_plot(
  data=full_data %>% filter(PlatformPortfolio!="Unlabeled" ),
  chart_geom = "Bar Chart",
  share = TRUE,
  labels_and_colors=labels_and_colors,
  # NA, #VAR.ncol
  x_var="dFYear", #x_var
  y_var="Action_Obligation_OMB19_19", #VAR.y.variable
  color_var="Competition.multisum", #color_var
  facet_var="PlatformPortfolio", #facet_var
  column_key=column_key,
  format=TRUE,
  ytextposition=FALSE
)+scale_x_date("Fiscal Year",labels = date_format("'%y"))+
  # theme(strip.text.y = element_text(angle=0))+
 # theme(axis.text.x = element_text(angle=90))+
 #    scale_y_continuous("Percent of Obligations", labels = percent_format(accuracy=1))+
 #      facet_grid(.~Competition.sum ,scales="free_x", space="free_x"
 #             )+labs(title=NULL,
  # x="Fiscal Year",
  # y="Percent of Obligations",
  # color="Competition")+
  theme(legend.position = "bottom")+
  labs(y="Obligations (Constant 2019 $s)")
)

ggsave600dpi("..//Output//platform_comp.png", PlatformComp, 
             width=6.5, height= 4, units="in",size=11,lineheight = 0.75
             )

```