---
title: "Alternate Financing Results Summary"
output:
  html_document:
    keep_md: yes
    toc: yes
date: "Wednesday, February 8, 2017"
---

#Setup
First we load the data. The dataset used is a U.S. Defense Contracting dataset derived from   FPDS.


```{r setup, echo = FALSE}
library(csis360)
library(ggplot2)
library(dplyr)
library(arm)
library(knitr)
library(foreign)
library(stargazer)
library(texreg)
library(reshape2)

library(svglite)
source("..\\scripts\\DIIGstat.r")

axis.text.size<-10
strip.text.size<-10
legend.text.size<-8
# table.text.size<-5.75
title.text.size<-12
geom.text.size<-12

main.text.size<-1
note.text.size<-1.40

load("..\\Data\\semi_clean\\OSC\\SelectedLoanDataSet.rda")

```



## Data Exploration
### USA spending
#### CFDA
```{r CFDS}


 cfda<-loanSelected %>% group_by(awarding_agency_name,cfda_num,cfda_title,assistance_type_code) %>% 
      summarise(n=length(assistance_type_code),
            total_outlayed_amount_for_overall_award=sum(total_outlayed_amount_for_overall_award,na.rm=TRUE),
            face_value_of_loan=sum(face_value_of_loan,na.rm=TRUE)) 
  # write_csv(cfda,file="../../output/OSC/selected_cfda.csv")


loan_lc<-prepare_labels_and_colors(loanSelected)
loan_ck<-get_column_key(loanSelected)

(
CFDAoblgiation<-build_plot(
  data=loanSelected,
  chart_geom = "Bar Chart",
  share = FALSE,
  labels_and_colors=loan_lc,
  column_key=loan_ck,
  # NA, #VAR.ncol
  x_var="dFYear", 
  alpha_var="YTD",  #x_var 
  y_var="federal_action_obligation", #VAR.y.variable
  color_var="cfda_num", #color_var
  facet_var="awarding_agency_name", #facet_var
  format=TRUE,
  ytextposition=FALSE
)+date_x_year_breaks(2000,2020,3,partial_year=2023,partial_label="\nQ1-Q2")+scale_alpha_ordinal(range=c(1,0.5))+
  theme(legend.position = "right")+
  labs(y="Obligations")# (Constant 2022 $s)
)



(
ToplineCFDA<-build_plot(
  data=loanSelected,
  chart_geom = "Bar Chart",
  share = FALSE,
  labels_and_colors=loan_lc,
  column_key=loan_ck,
  # NA, #VAR.ncol
  x_var="dFYear", 
  alpha_var="YTD",  #x_var 
  y_var="face_value_of_loan", #VAR.y.variable
  color_var="cfda_num", #color_var
  facet_var="awarding_agency_name", #facet_var
  format=TRUE,
  ytextposition=FALSE
)+date_x_year_breaks(2000,2020,3,partial_year=2023,partial_label="\nQ1-Q2")+scale_alpha_ordinal(range=c(1,0.5))+
  theme(legend.position = "right")+
  labs(y="Original Loan Face Value")# (Constant 2022 $s)
)



(
ToplineCFDA<-build_plot(
  data=loanSelected,
  chart_geom = "Bar Chart",
  share = FALSE,
  labels_and_colors=loan_lc,
  column_key=loan_ck,
  # NA, #VAR.ncol
  x_var="dFYear", 
  alpha_var="YTD",  #x_var 
  y_var="original_loan_subsidy_cost", #VAR.y.variable
  color_var="cfda_num", #color_var
  facet_var="awarding_agency_name", #facet_var
  format=TRUE,
  ytextposition=FALSE
)+date_x_year_breaks(2000,2020,3,partial_year=2023,partial_label="\nQ1-Q2")+scale_alpha_ordinal(range=c(1,0.5))+
  theme(legend.position = "right")+
  labs(y="Original Loan Subsidy Cost")# (Constant 2022 $s)
)

  
```
### SBA secondary sources
#### Sources
```{r sba}


```

### Economic
#### Award Summary
```{r award_summary}


award_summary<-function(df){
  minmax<-function(x){
    ifelse(min(x)==max(x),min(x),NA)
  }
  minmod<-function(x,mod){
    min(ifelse(is.na(mod) | mod==min(mod,na.rm=FALSE),x,NA),na.rm = TRUE)
  }
  
  latest<-function(x,date){
    min(ifelse(date==max(date),x,NA),na.rm = TRUE)
  }
  
  df<-df %>% group_by(assistance_award_unique_key) %>%
    summarise(
      # assistance_transaction_unique_key=minmax(assistance_transaction_unique_key),
      assistance_award_unique_key=minmax(assistance_award_unique_key),
      recipient_name=minmax(recipient_name),
      transaction_count=length(assistance_award_unique_key),
      cfda_num=minmax(cfda_num),
      cfda_title=minmax(cfda_title),
      # sai_number=minmax(sai_number),
      assistance_type_code=minmax(assistance_type_code),
      assistance_type_description=minmax(assistance_type_description),
      prime_award_base_transaction_description=minmax(prime_award_base_transaction_description),
      period_of_performance_start_date=minmod(period_of_performance_start_date,modification_number),
      initial_period_of_performance_current_end_date=minmod(period_of_performance_current_end_date,modification_number),
      # federal_action_obligation=sum(federal_action_obligation,na.rm=TRUE),
      original_loan_subsidy_cost=sum(original_loan_subsidy_cost,na.rm=TRUE),
      # latest_total_outlayed_amount_for_overall_award=latest(total_outlayed_amount_for_overall_award,action_date),
      face_value_of_loan=sum(face_value_of_loan,na.rm=TRUE),
      non_federal_funding_amount=sum(non_federal_funding_amount,na.rm=TRUE),
      indirect_cost_federal_share_amount=sum(indirect_cost_federal_share_amount,na.rm=TRUE),
      # latest_transaction_description=latest(transaction_description,action_date),
      max_last_modified_date=max(last_modified_date),
      award_id_fain=minmax(award_id_fain),
      # modification_number=minmax(modification_number),
      award_id_uri=minmax(award_id_uri),
      sai_number=minmax(sai_number),
      federal_action_obligation=minmax(federal_action_obligation),
      total_obligated_amount=minmax(total_obligated_amount),
      # total_outlayed_amount_for_overall_award=minmax(total_outlayed_amount_for_overall_award),
      indirect_cost_federal_share_amount=minmax(indirect_cost_federal_share_amount),
      non_federal_funding_amount=minmax(non_federal_funding_amount),
      total_non_federal_funding_amount=minmax(total_non_federal_funding_amount),
      face_value_of_loan=minmax(face_value_of_loan),
      original_loan_subsidy_cost=minmax(original_loan_subsidy_cost),
      total_face_value_of_loan=minmax(total_face_value_of_loan),
      total_loan_subsidy_cost=minmax(total_loan_subsidy_cost),
      # disaster_emergency_fund_codes_for_overall_award=minmax(disaster_emergency_fund_codes_for_overall_award),
      # outlayed_amount_from_COVID.19_supplementals_for_overall_award=minmax(outlayed_amount_from_COVID.19_supplementals_for_overall_award),
      # obligated_amount_from_COVID.19_supplementals_for_overall_award=minmax(obligated_amount_from_COVID.19_supplementals_for_overall_award),
      # outlayed_amount_from_IIJA_supplemental_for_overall_award=minmax(outlayed_amount_from_IIJA_supplemental_for_overall_award),
      # obligated_amount_from_IIJA_supplemental_for_overall_award=minmax(obligated_amount_from_IIJA_supplemental_for_overall_award),
      action_date=minmax(action_date),
      action_date_fiscal_year=minmax(action_date_fiscal_year),
      period_of_performance_start_date=minmax(period_of_performance_start_date),
      period_of_performance_current_end_date=minmax(period_of_performance_current_end_date),
      awarding_agency_code=minmax(awarding_agency_code),
      awarding_agency_name=minmax(awarding_agency_name),
      awarding_sub_agency_code=minmax(awarding_sub_agency_code),
      awarding_sub_agency_name=minmax(awarding_sub_agency_name),
      awarding_office_code=minmax(awarding_office_code),
      awarding_office_name=minmax(awarding_office_name),
      funding_agency_code=minmax(funding_agency_code),
      # Funding_Agency_Name=minmax(Funding_Agency_Name),
      funding_sub_agency_code=minmax(funding_sub_agency_code),
      funding_sub_agency_name=minmax(funding_sub_agency_name),
      funding_office_code=minmax(funding_office_code),
      funding_office_name=minmax(funding_office_name),
      # treasury_accounts_funding_this_award=minmax(treasury_accounts_funding_this_award),
      # federal_accounts_funding_this_award=minmax(federal_accounts_funding_this_award),
      # object_classes_funding_this_award=minmax(object_classes_funding_this_award),
      # program_activities_funding_this_award=minmax(program_activities_funding_this_award),
      recipient_uei=minmax(recipient_uei),
      recipient_duns=minmax(recipient_duns),
      recipient_name=minmax(recipient_name),
      recipient_name_raw=minmax(recipient_name_raw),
      recipient_parent_uei=minmax(recipient_parent_uei),
      recipient_parent_duns=minmax(recipient_parent_duns),
      recipient_parent_name=minmax(recipient_parent_name),
      recipient_parent_name_raw=minmax(recipient_parent_name_raw),
      recipient_country_code=minmax(recipient_country_code),
      recipient_country_name=minmax(recipient_country_name),
      recipient_address_line_1=minmax(recipient_address_line_1),
      recipient_address_line_2=minmax(recipient_address_line_2),
      recipient_city_code=minmax(recipient_city_code),
      recipient_city_name=minmax(recipient_city_name),
      prime_award_transaction_recipient_county_fips_code=minmax(prime_award_transaction_recipient_county_fips_code),
      recipient_county_name=minmax(recipient_county_name),
      prime_award_transaction_recipient_state_fips_code=minmax(prime_award_transaction_recipient_state_fips_code),
      recipient_state_code=minmax(recipient_state_code),
      recipient_state_name=minmax(recipient_state_name),
      recipient_zip_code=minmax(recipient_zip_code),
      recipient_zip_last_4_code=minmax(recipient_zip_last_4_code),
      prime_award_transaction_recipient_cd_original=minmax(prime_award_transaction_recipient_cd_original),
      prime_award_transaction_recipient_cd_current=minmax(prime_award_transaction_recipient_cd_current),
      # recipient_foreign_city_name=minmax(recipient_foreign_city_name),
      # recipient_foreign_province_name=minmax(recipient_foreign_province_name),
      # recipient_foreign_postal_code=minmax(recipient_foreign_postal_code),
      primary_place_of_performance_scope=minmax(primary_place_of_performance_scope),
      primary_place_of_performance_country_code=minmax(primary_place_of_performance_country_code),
      primary_place_of_performance_country_name=minmax(primary_place_of_performance_country_name),
      primary_place_of_performance_code=minmax(primary_place_of_performance_code),
      primary_place_of_performance_city_name=minmax(primary_place_of_performance_city_name),
      prime_award_transaction_place_of_performance_county_fips_code=minmax(prime_award_transaction_place_of_performance_county_fips_code),
      primary_place_of_performance_county_name=minmax(primary_place_of_performance_county_name),
      prime_award_transaction_place_of_performance_state_fips_code=minmax(prime_award_transaction_place_of_performance_state_fips_code),
      primary_place_of_performance_state_name=minmax(primary_place_of_performance_state_name),
      primary_place_of_performance_zip_4=minmax(primary_place_of_performance_zip_4),
      prime_award_transaction_place_of_performance_cd_original=minmax(prime_award_transaction_place_of_performance_cd_original),
      prime_award_transaction_place_of_performance_cd_current=minmax(prime_award_transaction_place_of_performance_cd_current),
      # primary_place_of_performance_foreign_location=minmax(primary_place_of_performance_foreign_location),
      cfda_number=minmax(cfda_number),
      cfda_title=minmax(cfda_title),
      # funding_opportunity_number=minmax(funding_opportunity_number),
      # funding_opportunity_goals_text=minmax(funding_opportunity_goals_text),
      assistance_type_code=minmax(assistance_type_code),
      transaction_description=minmax(transaction_description),
      prime_award_base_transaction_description=minmax(prime_award_base_transaction_description),
      business_funds_indicator_code=minmax(business_funds_indicator_code),
      business_funds_indicator_description=minmax(business_funds_indicator_description),
      business_types_code=minmax(business_types_code),
      business_types_description=minmax(business_types_description),
      correction_delete_indicator_code=minmax(correction_delete_indicator_code),
      correction_delete_indicator_description=minmax(correction_delete_indicator_description),
      action_type_code=minmax(action_type_code),
      action_type_description=minmax(action_type_description),
      record_type_code=minmax(record_type_code),
      record_type_description=minmax(record_type_description),
      # highly_compensated_officer_1_name=minmax(highly_compensated_officer_1_name),
      # highly_compensated_officer_1_amount=minmax(highly_compensated_officer_1_amount),
      # highly_compensated_officer_2_name=minmax(highly_compensated_officer_2_name),
      # highly_compensated_officer_2_amount=minmax(highly_compensated_officer_2_amount),
      # highly_compensated_officer_3_name=minmax(highly_compensated_officer_3_name),
      # highly_compensated_officer_3_amount=minmax(highly_compensated_officer_3_amount),
      # highly_compensated_officer_4_name=minmax(highly_compensated_officer_4_name),
      # highly_compensated_officer_4_amount=minmax(highly_compensated_officer_4_amount),
      # highly_compensated_officer_5_name=minmax(highly_compensated_officer_5_name),
      # highly_compensated_officer_5_amount=minmax(highly_compensated_officer_5_amount),
      usaspending_permalink=minmax(usaspending_permalink),
      last_modified_date=minmax(last_modified_date),
      USAspending_file_name=minmax(USAspending_file_name),
      cfda_num=minmax(cfda_num),
      assistance_type_description=minmax(assistance_type_description),
    )
  df
}
```


#### NAICS 2

```{r grouped percent frequency/obligation barplot for all NAICS2, 21 in total}
#Prepare data for plot
NAICS2_Freq <- as.data.frame(table(def$NAICS2))
NAICS2_Freq$Percent_Freq <- round(NAICS2_Freq$Freq/sum(NAICS2_Freq$Freq),4)*100
colnames(NAICS2_Freq) <- c("NAICS_Code", "Count_Freq", "Percent_Freq")

#Get detail description for NAICS2 code
summary(NAICS2_Freq$NAICS_Code)
NAICS2_Freq<-read_and_join_experiment(NAICS2_Freq,
                                           lookup_file = "Lookup_PrincipalNAICScode.csv",
                                      # path="https://raw.githubusercontent.com/CSISdefense/Lookup-Tables/master/",
                                      path="C:\\Users\\gsand\\Repositories\\Lookup-Tables\\",
                                      dir="economic\\",
                                      by=c("NAICS_Code"="principalnaicscode"),
                                      add_var = "principalnaicscodeText",
                                      guess_max=5000
                                      )

Percent_Obli <- c()
Total_Obli <- sum(def$Action_Obligation_Then_Year, na.rm = TRUE)
for (i in NAICS2_Freq$NAICS_Code) {
  Percent_Obligation <- round(sum(def$Action_Obligation_Then_Year[def$NAICS2 == i], na.rm = TRUE)/Total_Obli,5)
  Percent_Obli <- c(Percent_Obli, Percent_Obligation)
}

NAICS2_Freq$Percent_Obli <- Percent_Obli * 100
NAICS2_Freq <- NAICS2_Freq[order(-NAICS2_Freq$Percent_Obli),]
NAICS2_Freq[,c(1,3)] <- lapply(NAICS2_Freq[,c(1,3)], function(x) as.character(x))
NAICS2_Freq$principalnaicscodeText <- paste(NAICS2_Freq$NAICS_Code, " - ", NAICS2_Freq$principalnaicscodeText)
NAICS2_Freq$principalnaicscodeText <- factor(NAICS2_Freq$principalnaicscodeText, levels = rev(NAICS2_Freq$principalnaicscodeText))
NAICS2_Freq <- melt(NAICS2_Freq, id = c("NAICS_Code", "Count_Freq","principalnaicscodeText"))
NAICS2_Freq$value <- as.numeric(NAICS2_Freq$value)

NAICS2_barplot <- ggplot(data = NAICS2_Freq,
                          aes(x = principalnaicscodeText, 
                              y = value,
                              fill = factor(variable))) +
                   geom_bar(stat = "identity", 
                            position = "dodge", 
                            width = 0.8) + 
                   coord_flip() +
                   xlab("") + 
                   ylab("") + 
                   theme_grey() + 
                   scale_fill_grey(labels = c("% records", "% obligation"),
                                  guide = guide_legend(reverse = TRUE)) + 
                   ggtitle("Percent of Frequency and obligation for NAICS2") +
                   theme(text = element_text(size = 10), 
                         legend.title = element_blank(),
                         legend.position = "bottom",
                         legend.margin = margin(t=-0.8, r=0, b=0.5, l=0, unit = "cm"),
                         legend.text = element_text(margin = margin(r=0.5, unit = "cm")),
                         plot.margin = margin(t=0.3, r=0.5, b=0, l=0.5, unit = "cm"))
NAICS2_barplot

```

#### NAICS 3

```{r NAICS3_Summary, fig.width=7.5 , fig.height=3}
NAICS_summary<-def %>% group_by(NAICS3,StartCY,def3_HHI_lag1,def3_obl_lag1,def3_ratio_lag1,US3_avg_sal_lag1) %>%
  dplyr::summarise(annual_action_obligation=sum(Action_Obligation_Then_Year),
                   annual_count=length(StartCY)) 
xlabel<-paste("Calendar Year (",min(NAICS_summary$CY),"-",max(NAICS_summary$CY),")",sep="")

top_NAICS <- NAICS_summary %>% group_by(NAICS3) %>% 
  dplyr::summarise(naics_action_obligation=sum(annual_action_obligation),
                   naics_count=sum(annual_count)) 
top_NAICS$naics_dollar_rank<-rank(-top_NAICS$naics_action_obligation)
top_NAICS$naics_count_rank<-rank(-top_NAICS$naics_count)

#If statement there to prevent adding it a second time in  reruns.
if(!"naics_dollar_rank" %in% colnames(NAICS_summary))
  NAICS_summary<-left_join(NAICS_summary,top_NAICS, by="NAICS3")




NAICS_summary<-as.data.frame(NAICS_summary)
NAICS_summary$NAICS3<-as.character(NAICS_summary$NAICS3)
NAICS_summary<-read_and_join_experiment(NAICS_summary,
                                      lookup_file = "Lookup_PrincipalNAICScode.csv",
                                      path="https://raw.githubusercontent.com/CSISdefense/Lookup-Tables/master/",
                                      dir="economic\\",
                                      by=c("NAICS3"="principalnaicscode"),
                                      skip_check_var=c("principalnaicscodeText",
                                                       "NAICS_shorthand",
                                                       "NAICS_unabbreviated",
                                                       "principalNAICS4DigitCode"),
                                      guess_max = 5000
                                      )

# https://stackoverflow.com/questions/37174316/how-to-fit-long-text-into-ggplot2-facet-titles



# Helper function for string wrapping. 
#  20 character target width.

summary(NAICS_summary$NAICS_unabbreviated)

# View(NAICS_summary)
NAICS_summary$NAICS_shorthand<-factor_wrap(NAICS_summary$NAICS_shorthand,nwrap = 25)
NAICS_summary$CY<-NAICS_summary$StartCY-1 #Removing the prior year adjustment
NAICS3top<-ggplot(subset(NAICS_summary,naics_dollar_rank<=4 |
                          naics_count_rank<=4),
       aes(x=CY,y=def3_HHI_lag1))+#color=NAICS_Code
  geom_line()+
  scale_y_continuous(label=scales::comma)+ 
  # scale_x_continuous(breaks=c(2006,2009,2011,2014))+
  labs(x=xlabel,y="Herfindahl-Herschman Index")+ 
  geom_hline(yintercept=c(1500,2500),linetype="dotted")

NAICS3top_paper<-NAICS3top+ facet_wrap(~NAICS_shorthand,ncol=2)
ggsave(NAICS3top_paper,file="..//Output\\NAICS3top.png",width=4,height=8,dpi=600)
ggsave(NAICS3top_paper,file="..//Output\\NAICS3top.eps",width=4,height=8,dpi=600)

NAICS3top_pp<-NAICS3top+ facet_wrap(~NAICS_shorthand,ncol=4)
NAICS3top_pp
ggsave(NAICS3top_pp,file="..//Output\\NAICS3top_pp.png",width=10.5,height=5.5,dpi=600)
ggsave(NAICS3top_pp,file="..//Output\\NAICS3top_pp.eps",width=10.5,height=5.5,dpi=600)

summary(NAICS_summary$naics_count_rank)


NAICS_summary$NAICS_unabbreviated<-factor_wrap(NAICS_summary$NAICS_unabbreviated,nwrap = 14)
NAICS_summary$NAICS_shorthand<-factor_wrap(NAICS_summary$NAICS_shorthand,nwrap = 14)
# NAICS_summary$CY<-factor(paste("'",substring(as.character(NAICS_summary$CY),3,4),sep=""))




NAICS3top8<-ggplot(subset(NAICS_summary,naics_dollar_rank<=8),
       aes(x=CY,y=def3_HHI_lag1))+#color=NAICS_Code
  geom_line()+
  scale_y_continuous(label=scales::comma)+ 
  scale_x_continuous(breaks=c(2007,2012))+
  labs(x=xlabel,y="Herfindahl-Herschman Index")+ 
  geom_hline(yintercept=c(1500,2500),linetype="dotted")

NAICS3top8_wide<-NAICS3top8+ facet_grid(.~NAICS_unabbreviated)
ggsave(NAICS3top8_wide,file="..//Output\\NAICS3top8.png",width=9.5,height=4,dpi=600)
ggsave(NAICS3top8_wide,file="..//Output\\NAICS3top8.eps",width=9.5,height=4,dpi=600)

colnames(NAICS_summary)
NAICS_long<-NAICS_summary[,colnames(NAICS_summary) %in% c( "NAICS3",
                                                    "def3_HHI_lag1",
                                                    "def3_obl_lag1",
                                                    "def3_ratio_lag1",
                                                    # "US3_avg_sal_lag1",
                                                    "naics_dollar_rank" ,
                                                    "naics_count_rank",
                                                    "principalnaicscodeText",
                                                     "NAICS_unabbreviated",
                                                    "CY")]
NAICS_long<-melt(NAICS_long, id=c("NAICS3","naics_dollar_rank","naics_count_rank","principalnaicscodeText","CY", "NAICS_unabbreviated"))



#Drop the ratios and average salaries w/ unique values
# NAICS_long<-NAICS_long[NAICS_long$variable %in% c(),]

NAICS_long$value[NAICS_long$variable=="def3_obl_lag1"]<-NAICS_long$value[NAICS_long$variable=="def3_obl_lag1"]/1e9
NAICS_long$value[NAICS_long$variable=="def3_ratio_lag1"]<-NAICS_long$value[NAICS_long$variable=="def3_ratio_lag1"]*1e2

levels(NAICS_long$variable)<- list("Herfindahl-\nHerschman Index"=c("def3_HHI_lag1"),
                                   "Defense Obligations\n(Billions)"=c("def3_obl_lag1"),
                                   "Defense Obligations\nto U.S. Revenue\nRatio (Percent)"=c("def3_ratio_lag1"))

NAICS_long$high<-2500
NAICS_long$high[NAICS_long$variable!="Herfindahl-\nHerschman Index"]<-NA
NAICS_long$low<-1500
NAICS_long$low[NAICS_long$variable!="Herfindahl-\nHerschman Index"]<-NA

(
NAICS3long_wide<-ggplot(subset(NAICS_long,naics_dollar_rank<=8),
       aes(x=CY,y=value))+#color=NAICS_Code
  geom_line()+
  scale_y_continuous(label=scales::comma)+ 
  scale_x_continuous(breaks=c(2007,2012))+
  labs(x=xlabel,y="Detailed Industry Metric (Varies Between Rows)")+
  geom_hline(aes(
           yintercept=high),linetype="dotted")+
  geom_hline(aes(
           yintercept=low),linetype="dotted") + 
  facet_grid(variable~NAICS_unabbreviated,scales="free_y")   
)

ggsave(NAICS3long_wide+theme(text=element_text(size=13)),file="..//Output\\JSCAN\\Figure2.png",width=9.5,height=6.5,dpi=600)
ggsave(NAICS3long_wide+theme(text=element_text(size=13)),file="..//Output\\JSCAN\\Figure2.eps",width=9.5,height=6.5,dpi=600)
ggsave(NAICS3long_wide+theme(text=element_text(size=13)),file="..//Output\\JSCAN\\Figure2.svg",width=9.5,height=6.5,dpi=600)

write.csv(NAICS_summary,file="..//Output/NAICS3_summary.csv",row.names = FALSE)
```







#### NAICS 6



```{r NAICS6_Summary, fig.width=7.5 , fig.height=3}
NAICS_summary<-def %>% group_by(NAICS,StartCY,def6_HHI_lag1,def6_obl_lag1,def6_ratio_lag1,US6_avg_sal_lag1) %>%
  dplyr::summarise(annual_action_obligation=sum(Action_Obligation_Then_Year),
                   annual_count=length(StartCY)) 

top_NAICS <- NAICS_summary %>% group_by(NAICS) %>% 
  dplyr::summarise(naics_action_obligation=sum(annual_action_obligation),
                   naics_count=sum(annual_count)) 
top_NAICS$naics_dollar_rank<-rank(-top_NAICS$naics_action_obligation)
top_NAICS$naics_count_rank<-rank(-top_NAICS$naics_count)


NAICS_summary<-left_join(NAICS_summary,top_NAICS, by="NAICS")

colnames(NAICS_summary)[colnames(NAICS_summary)=="NAICS"]<-"principalnaicscode"

NAICS_summary$principalnaicscode<-as.character(NAICS_summary$principalnaicscode)
NAICS_summary<-as.data.frame(NAICS_summary)

NAICS_summary<-read_and_join_experiment(NAICS_summary,
                        lookup_file = "Lookup_PrincipalNAICScode.csv",
                        path="https://raw.githubusercontent.com/CSISdefense/Lookup-Tables/master/",
                                      dir="economic\\",
                        by="principalnaicscode",
                        skip_check_var=c("principalnaicscodeText",
                                         "NAICS_shorthand",
                                         "NAICS_unabbreviated"),
                        guess_max=5000
               )




summary(NAICS_summary$NAICS_shorthand)

# View(NAICS_summary)

NAICS_summary$NAICS_shorthand<-factor_wrap(NAICS_summary$NAICS_shorthand,nwrap = 25)
NAICS_summary$CY<-NAICS_summary$StartCY-1
NAICS6top<-ggplot(subset(NAICS_summary,naics_dollar_rank<=4 |
                          naics_count_rank<=4),
       aes(x=CY,y=def6_HHI_lag1))+#color=NAICS_Code
  geom_line()+
  scale_y_continuous(label=scales::comma)+ 
  # scale_x_continuous(breaks=c(2006,2009,2011,2014))+
  labs(x=xlabel,y="Herfindahl-Herschman Index")+ 
  geom_hline(yintercept=c(1500,2500),linetype="dotted")

(NAICS6top_paper<-NAICS6top+ facet_wrap(~NAICS_shorthand,ncol=2))
ggsave(NAICS6top_paper,file="..//Output\\NAICS6top.png",width=4,height=8,dpi=600)
ggsave(NAICS6top_paper,file="..//Output\\NAICS6top.eps",width=4,height=8,dpi=600)

(NAICS6top_pp<-NAICS6top+ facet_wrap(~NAICS_shorthand,ncol=4))
ggsave(NAICS6top_pp,file="..//Output\\NAICS6top_pp.png",width=10.5,height=5.5,dpi=600)
ggsave(NAICS6top_pp,file="..//Output\\NAICS6top_pp.eps",width=10.5,height=5.5,dpi=600)

summary(NAICS_summary$naics_count_rank)


NAICS_summary$NAICS_shorthand<-factor_wrap(NAICS_summary$NAICS_shorthand,nwrap = 14)
NAICS_summary$NAICS_unabbreviated<-factor_wrap(NAICS_summary$NAICS_unabbreviated,nwrap = 14)
# NAICS_summary$CY<-factor(paste("'",substring(as.character(NAICS_summary$CY),3,4),sep=""))

NAICS6top8<-ggplot(subset(NAICS_summary,naics_dollar_rank<=8),
       aes(x=CY,y=def6_HHI_lag1))+#color=NAICS_Code
  geom_line()+
  scale_y_continuous(label=scales::comma)+ 
  scale_x_continuous(breaks=c(2007,2012))+
  labs(x=xlabel,y="Herfindahl-Herschman Index")+ 
  geom_hline(yintercept=c(1500,2500),linetype="dotted")

NAICS6top8_wide<-NAICS6top8+ facet_grid(.~NAICS_shorthand)
ggsave(NAICS6top8_wide,file="..//Output\\NAICS6top8.png",width=9.5,height=4,dpi=600)
ggsave(NAICS6top8_wide,file="..//Output\\NAICS6top8.eps",width=9.5,height=4,dpi=600)


colnames(NAICS_summary)
NAICS_long<-NAICS_summary[,colnames(NAICS_summary) %in% c( "principalnaicscode",
                                                    "def6_HHI_lag1",
                                                    "def6_obl_lag1",
                                                    "def6_ratio_lag1",
                                                    # "US6_avg_sal_lag1",
                                                    "naics_dollar_rank" ,
                                                    "naics_count_rank",
                                                    "principalnaicscodeText",
                                                     "NAICS_unabbreviated",
                                                    "CY")]
NAICS_long<-melt(NAICS_long, id=c("principalnaicscode","naics_dollar_rank","naics_count_rank","principalnaicscodeText","CY", "NAICS_unabbreviated"))



#Drop the ratios and average salaries w/ unique values
# NAICS_long<-NAICS_long[NAICS_long$variable %in% c(),]
NAICS_long$value[NAICS_long$variable=="def6_obl_lag1"]<-NAICS_long$value[NAICS_long$variable=="def6_obl_lag1"]/1e9
NAICS_long$value[NAICS_long$variable=="def6_ratio_lag1"]<-NAICS_long$value[NAICS_long$variable=="def6_ratio_lag1"]*1e2


levels(NAICS_long$variable)<- list("Herfindahl-\nHerschman Index"=c("def6_HHI_lag1"),
                                   "Defense Obligations\n(Billions)"=c("def6_obl_lag1"),
                                   "Defense Obligations\nto U.S. Revenue\nRatio (Percent)"=c("def6_ratio_lag1"))

NAICS_long$high<-2500
NAICS_long$high[NAICS_long$variable!="Herfindahl-\nHerschman Index"]<-NA
NAICS_long$low<-1500
NAICS_long$low[NAICS_long$variable!="Herfindahl-\nHerschman Index"]<-NA

(

NAICS6long_wide<-ggplot(subset(NAICS_long,naics_dollar_rank<=8),
       aes(x=CY,y=value))+#color=NAICS_Code
  geom_line()+
  scale_y_continuous(label=scales::comma)+ 
  scale_x_continuous(breaks=c(2007,2012))+
  labs(x=xlabel,y="Detailed Industry Metric (Varies Between Rows)",caption="Note: 54171* combines codes 541710, 541711, and 541712 to include this significant industry despite a change in codes over the period.")+
  geom_hline(aes(
           yintercept=high),linetype="dotted")+
  geom_hline(aes(
           yintercept=low),linetype="dotted")    + 
    facet_grid(variable~NAICS_unabbreviated,scales="free_y")

)

ggsave(NAICS6long_wide+theme(text=element_text(size=13)),file="..//Output\\JSCAN\\Figure3.png",width=9.5,height=6.5,dpi=600)
ggsave(NAICS6long_wide+theme(text=element_text(size=13)),file="..//Output\\JSCAN\\Figure3.eps",width=9.5,height=6.5,dpi=600)
ggsave(NAICS6long_wide+theme(text=element_text(size=13)),file="..//Output\\JSCAN\\Figure3.svg",width=9.5,height=6.5,dpi=600)
write.csv(NAICS_summary,file="..//Output/NAICS6_summary.csv",row.names = FALSE)
```






### Office
```{r grouped percent frequency/obligation barplot for all Office}
#grouped bar plot for variable Office
#Perpare data for plot
Office_Freq <- def %>% group_by(Agency, Office) %>%
  dplyr::summarise(
    Count_Freq=length(CSIScontractID),
    Action_Obligation_Then_Year=sum(Action_Obligation_Then_Year,na.rm=TRUE)
  )

Office_Freq$Percent_Obligation <- Office_Freq$Action_Obligation_Then_Year/
                                          sum(Office_Freq$Action_Obligation_Then_Year,na.rm=TRUE)

Office_Freq$Percent_Freq <- Office_Freq$Count_Freq/
                                          sum(Office_Freq$Count_Freq,na.rm=TRUE)

#get the detailed desceription for Office by AgencyID and OfficeID

Office_Freq<-read_and_join_experiment(Office_Freq,
                                      lookup_file = "Office.ContractingOfficeCode.txt",
                                      path="https://raw.githubusercontent.com/CSISdefense/Lookup-Tables/master/",
                                      dir="office/",
                                      by=c("Agency"="AgencyID",
                                       "Office"="ContractingOfficeCode"   
                                      ),
                                      add_var = "ContractingOfficeName",
                                      skip_check_var = "ContractingOfficeName")


colnames(Office_Freq)[colnames(Office_Freq)=="ContractingOfficeName"] <- "OfficeName"

# Office_Freq[,1:2] <- lapply(Office_Freq[,1:2], function(x) as.character(x))
#Generate a new name column by Combining Office and officeName
Office_Freq$Office_Full <- ifelse(is.na(Office_Freq$OfficeName), Office_Freq$Office, 
                                  paste(Office_Freq$Office, 
                                            sep=" - ", Office_Freq$OfficeName))


# Office_Freq$Percent_Obli <- Percent_Obli * 100

Office_Freq_top10Freq <- Office_Freq[order(-Office_Freq$Percent_Freq),]
Office_Freq_top10Freq <- Office_Freq_top10Freq[1:10, ]  #including NULL category
Office_Freq_top10Obli <- Office_Freq[order(-Office_Freq$Percent_Obligation),]
Office_Freq_top10Obli <- Office_Freq_top10Obli[1:10, ]  #including NULL category

Office_Freq_TOP <- rbind(Office_Freq_top10Obli, Office_Freq_top10Freq)
Office_Freq_TOP <- unique(Office_Freq_TOP)  #17 records in total

Office_Freq_TOP$Office_Full <- factor(Office_Freq_TOP$Office_Full, 
                                      levels = rev(Office_Freq_TOP$Office_Full))
Office_Freq_TOP <- melt(Office_Freq_TOP, 
                        id = c("Agency","Office", "OfficeName", "Office_Full", "Count_Freq", "Action_Obligation_Then_Year"))

Office_barplot <- ggplot(data = Office_Freq_TOP,
                         aes(x = Office_Full, 
                             y = value,
                             fill = factor(variable))) +
                  geom_bar(stat = "identity", 
                  position = "dodge", 
                  width = 0.8) + 
                  coord_flip() +
                  xlab("") + 
                  ylab("") + 
                  theme_grey() + 
                  scale_fill_grey(labels = c("% of records", "% of obligation"),
                                  guide = guide_legend(reverse = TRUE)) + 
                  ggtitle("Percent of Frequency and obligation for Office") +
                  theme(text = element_text(size = 10), 
                        legend.title = element_blank(),
                        legend.position = "bottom",
                        legend.margin = margin(t=-0.8, r=0, b=0.5, l=0, unit = "cm"),
                        legend.text = element_text(margin = margin(r=0.5, unit = "cm")), 
                        plot.margin = margin(t=0.3, r=0.5, b=0, l=0.5, unit = "cm"))
Office_barplot
```



### Variable examination
```{r VarGraph}


HH1plot<-freq_continuous_plot(def,"def6_HHI_lag1",bins=50)
HH1plot<-HH1plot+geom_vline(xintercept=c(1500,2500))+labs(x="Annual Herfindahl-Hirschman Index (HHI) for NAICS-6 Sector",y="Contract or Task Order Count")
HH1plot
ggsave(HH1plot,file="..//Output//HH1freq.png",width=5.5,height=5.5,dpi=600)
ggsave(HH1plot,file="..//Output//HH1freq.eps",width=5.5,height=5.5,dpi=600)

sum(def$Action_Obligation_Then_Year[def$EffComp=="No Comp."],na.rm=TRUE)/sum(def$Action_Obligation_Then_Year,na.rm=TRUE)
sum(def$Action_Obligation_Then_Year[def$EffComp=="1 Offer"],na.rm=TRUE)/sum(def$Action_Obligation_Then_Year,na.rm=TRUE)
sum(def$Action_Obligation_Then_Year[def$EffComp=="2+ Offers"],na.rm=TRUE)/sum(def$Action_Obligation_Then_Year,na.rm=TRUE)
nrow(def[def$EffComp=="No Comp.",])/nrow(def)

sum(def$Action_Obligation_Then_Year[is.na(def$EffComp)],na.rm=TRUE)/sum(def$Action_Obligation_Then_Year,na.rm=TRUE)


# Effplot<-freq_discrete_plot(subset(def,"EffComp"))
# Effplot<-Effplot+labs(x="Effective Competition",y="Contract or Task Order Count")
# ggsave(Effplot,file="..//Output//EffFreq.png",width=5.5,height=5.5,dpi=600)

```


