---
title: "Entity ID quality checks"
author: "Gregory Sanders"
date: "2023-08-03"
output: html_document
---

```{r setup, include=FALSE}
library(readr)
library(tidyverse)

RU2duns<-read_tsv(file.path("..","data","semi_clean","Vendor.RecipientUEItopDunsnumber.txt"),na="NULL")
RUh2duns<-read_tsv(file.path("..","data","semi_clean","Vendor.RecipientUEIhistoryTopDunsnumber.txt"),na="NULL")
problems(RUh2duns)
```

## QA check



```{r cars}
RU2duns<-RU2duns %>% filter(!is.na(TotalCount))

if(any(RU2duns$TopDunsnumberCount>RU2duns$TotalCount))
  stop("Misaligned counts")

RU2duns <- RU2duns %>% mutate(
  pCount=TopDunsnumberCount/TotalCount,
  pDollar=TopDunsnumberAmount/totalamount,
  pMatch=ifelse(!is.nan(pDollar)&!is.na(pDollar),pDollar,pCount)
)

RUh2duns<-RUh2duns %>% filter(!is.na(TotalCount))

if(any(RUh2duns$TopDunsnumberCount>RUh2duns$TotalCount))
  stop("Misaligned counts")


RUh2duns <- RUh2duns %>% mutate(
  pCount=TopDunsnumberCount/TotalCount,
  pDollar=TopDunsnumberAmount/TotalAmount,
  pMatch=ifelse(!is.nan(pDollar)&!is.na(pDollar),pDollar,pCount)
)


```

## Recipient UEI alone

```{r ru}

nrow(RU2duns %>% filter(pMatch==1))/nrow(RU2duns)
sum((RU2duns %>% filter(pMatch==1))$TotalCount)/sum(RU2duns$TotalCount)
sum((RU2duns %>% filter(pMatch==1))$totalamount)/sum(RU2duns$totalamount)

nrow(RU2duns %>% filter(abs(pMatch-1)<0.1))/nrow(RU2duns)
sum((RU2duns %>% filter(abs(pMatch-1)<0.1))$TotalCount)/sum(RU2duns$TotalCount)
sum((RU2duns %>% filter(abs(pMatch-1)<0.1))$totalamount)/sum(RU2duns$totalamount)

ggplot(RU2duns %>% filter(pMatch<=1&pMatch>=0 ),aes(x=pMatch))+geom_histogram()+coord_cartesian(xlim=c(0,1))+
  scale_x_continuous(labels=scales::percent)#scale_y_log10(label=scales::comma)+


ggplot(RU2duns %>% filter(pMatch<=1&pMatch>=0 ),aes(x=pMatch,weight=TotalCount))+geom_histogram()+coord_cartesian(xlim=c(0,1))+
  scale_x_continuous(labels=scales::percent)#scale_y_log10(label=scales::comma)


ggplot(RU2duns %>% filter(pMatch<=1&pMatch>=0 ),aes(x=pMatch,weight=totalamount))+geom_histogram()+coord_cartesian(xlim=c(0,1))+
  scale_x_continuous(labels=scales::percent)#scale_y_log10(label=scales::comma)
```



## Recipient UEI and fiscal year

```{r ruh}

nrow(RUh2duns %>% filter(pMatch==1))/nrow(RUh2duns)
sum((RUh2duns %>% filter(pMatch==1))$TotalCount)/sum(RUh2duns$TotalCount)
sum((RUh2duns %>% filter(pMatch==1))$TotalAmount)/sum(RUh2duns$TotalAmount)

nrow(RUh2duns %>% filter(abs(pMatch-1)<0.1))/nrow(RUh2duns)
sum((RUh2duns %>% filter(abs(pMatch-1)<0.1))$TotalCount)/sum(RUh2duns$TotalCount)
sum((RUh2duns %>% filter(abs(pMatch-1)<0.1))$TotalAmount)/sum(RUh2duns$TotalAmount)

ggplot(RUh2duns %>% filter(pMatch<=1&pMatch>=0 ),aes(x=pMatch))+geom_histogram()+coord_cartesian(xlim=c(0,1))+
  scale_x_continuous(labels=scales::percent)#scale_y_log10(label=scales::comma)

ggplot(RUh2duns %>% filter(pMatch<=1&pMatch>=0 ),aes(x=pMatch))+geom_histogram()+coord_cartesian(xlim=c(0,1))+
  scale_x_continuous(labels=scales::percent)+facet_wrap(~Fiscal_Year)


ggplot(RUh2duns %>% filter(pMatch<=1&pMatch>=0 ),aes(x=pMatch,weight=TotalCount))+geom_histogram()+coord_cartesian(xlim=c(0,1))+
  scale_x_continuous(labels=scales::percent)#scale_y_log10(label=scales::comma)+


ggplot(RUh2duns %>% filter(pMatch<=1&pMatch>=0 ),aes(x=pMatch,weight=TotalCount))+geom_histogram()+coord_cartesian(xlim=c(0,1))+
  scale_x_continuous(labels=scales::percent)+facet_wrap(~Fiscal_Year)


ggplot(RUh2duns %>% filter(pMatch<=1&pMatch>=0 ),aes(x=pMatch,weight=TotalAmount))+geom_histogram()+coord_cartesian(xlim=c(0,1))+
 scale_x_continuous(labels=scales::percent)# scale_y_log10(label=scales::comma)+

ggplot(RUh2duns %>% filter(pMatch<=1&pMatch>=0 ),aes(x=pMatch,weight=TotalAmount))+geom_histogram()+coord_cartesian(xlim=c(0,1))+
 scale_x_continuous(labels=scales::percent)+facet_wrap(~Fiscal_Year)
```
