---
title: "UEI Graphing"
author: "Greg Sanders"
date: "November 21, 2025"
output: html_document
---
# Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(tidyverse)
library(ggplot2)
library(csis360)
library(readr)
load(file="../data/clean/FPDS_eid_fyear.rda")
load(file="../data//clean//defense_naics_vendor.Rdata")
load(file=file.path("..","data","clean","RecipientUEI.rda"))

load(file="../data//clean//TopVendorUAVHistoryPlatformCustomer.rda")


online_path<-file.path(get_local_sharepoint_path("DIIG Teamsite - Shared Documents"),"2024 - Acquisition Trends","Data and Figures")


# style_path<-"https://raw.githubusercontent.com/CSISdefense/Lookup-Tables/master/style/"
# style_path<-"K:\\Users\\Greg\\Repositories\\Lookup-Tables\\style\\"
style_path<-"C:\\Users\\gsand\\Repositories\\Lookup-Tables\\style\\"

eid_lc<-prepare_labels_and_colors(FPDS_eid_fyear)


summary(factor(FPDS_eid_fyear$IsEntityAbove2018constant10ThousandThreshold))

summary(factor(FPDS_eid_fyear$EntitySizeText))
summary(factor(FPDS_eid_fyear$EntitySizeGlitch))
summary(FPDS_eid_fyear$ObligatedAmountIsSmall)
summary(FPDS_eid_fyear$MajorityNotSmall)
FPDS_eid_fyear$count<-1
FPDS_eid_fyear<-csis360::read_and_join_experiment(FPDS_eid_fyear,
                        "EntitySizeCode.csv",
                        by=c("EntitySizeCode"),
                        add_var=c("EntitySmall"),
                        path="https://raw.githubusercontent.com/CSISdefense/Lookup-Tables/master/",
                        dir="vendor/"
)

FPDS_eid_fyear$EntitySmall[FPDS_eid_fyear$EntitySizeGlitch==TRUE |FPDS_eid_fyear$EntitySmall=="Unlabeled Vendor" ]<-"Unlabeled"
summary(factor(FPDS_eid_fyear$EntitySmall))
FPDS_eid_fyear$EntitySmall<-factor(FPDS_eid_fyear$EntitySmall,rev(c("Always Small Vendor","Sometimes Small Vendor","Other Than Small","Unlabeled")))

FPDS_eid_fyear<-csis360::read_and_join_experiment(FPDS_eid_fyear,
  "Vendor.EntityIDanyDefense.txt",
  by=c("fiscal_year","EntityID"),
  add_var="AnyDefenseCustomer",
  skip_check_var = "AnyDefenseCustomer",
  path="",
  
  dir=file.path("..","data","semi_clean")
)



ec<-read.delim(file.path("../Data/semi_clean/Vendor_sp_EntityCountHistoryCustomer.txt"), header=TRUE,  na.strings = c("", "NULL"))
ec<-remove_bom(ec)
ec<-standardize_variable_names(ec)
ec$dFYear<-as.Date(paste("1/1/",as.character(ec$Fiscal_Year),sep=""),"%m/%d/%Y")


ec<-csis360::read_and_join_experiment(ec,
  "EntitySizeCode.csv",
  by="EntitySizeCode",
  add_var="EntitySmall",
  path="https://raw.githubusercontent.com/CSISdefense/Lookup-Tables/master/",
  dir="vendor/"
)



# def_eid_fyear<-read.delim(file.path("../Data/semi_clean/Defense_Vendor.SP_EntityIDhistory.txt"), header=TRUE,  na.strings = c("", "NULL"))
# def_eid_fyear<-remove_bom(def_eid_fyear)
# def_eid_fyear$EntityCount<-1
# def_eid_fyear<-standardize_variable_names(def_eid_fyear)
# def_eid_fyear$dFYear<-as.Date(paste("1/1/",as.character(def_eid_fyear$Fiscal_Year),sep=""),"%m/%d/%Y")

# eid_lc<-prepare_labels_and_colors(ec,path="K:\\Users\\Greg\\Repositories\\Lookup-Tables\\style\\")
ec<-replace_nas_with_unlabeled(ec,"EntitySmall","Unlabeled Vendor")
ec<-replace_nas_with_unlabeled(ec,"EntitySizeText","Unlabeled Vendor")

eid_lc<-prepare_labels_and_colors(ec)




ecp<-read.delim(file.path("../Data/semi_clean/Defense_Vendor_sp_EntityCountHistoryPlatformCustomer.txt"), header=TRUE,  na.strings = c("", "NULL"))
ecp<-remove_bom(ecp)
ecp<-standardize_variable_names(ecp)
ecp$dFYear<-as.Date(paste("1/1/",as.character(ecp$Fiscal_Year),sep=""),"%m/%d/%Y")



ecp<-csis360::read_and_join(ecp,
  "EntitySizeCode.csv",
  by="EntitySizeCode",
  add_var="EntitySmall",
  path="../../Lookup-Tables/",
  # path="https://raw.githubusercontent.com/CSISdefense/Lookup-Tables/master/",
  dir="vendor/"
)
def_eid_fyear_plat<-read.delim(file.path("../Data/semi_clean/Defense_Vendor.SP_EntityIDhistoryPlatform.txt"),
                               header=TRUE,  na.strings = c("", "NULL"))
def_eid_fyear_plat<-remove_bom(def_eid_fyear_plat)
def_eid_fyear_plat<-standardize_variable_names(def_eid_fyear_plat)
def_eid_fyear_plat$EntityCount<-1
def_eid_fyear_plat$dFYear<-as.Date(paste("1/1/",as.character(def_eid_fyear_plat$Fiscal_Year),sep=""),"%m/%d/%Y")

ecp$EntitySizeText<-factor(ecp$EntitySizeText)
ecp$thresh<-factor(ecp$IsEntityAbove2016constantOneMillionThreshold,
                   levels=c(0,1), 
                   labels=c("Vendor only receives smaller contracts","Vendor receives contracts over $1 million in 2016 $"))


ecp<-replace_nas_with_unlabeled(ecp,"EntitySmall","Unlabeled Vendor")
ecp<-replace_nas_with_unlabeled(ecp,"EntitySizeText","Unlabeled Vendor")


# ecp_lc<-prepare_labels_and_colors(ecp,path="K:\\Users\\Greg\\Repositories\\Lookup-Tables\\style\\")
ecp_lc<-prepare_labels_and_colors(ecp)

ecp_ck<-get_column_key(ecp)




ecsub<-read.delim(file.path("../Data/semi_clean/Vendor_sp_EntityCountHistorySubCustomer.txt"), header=TRUE,  na.strings = c("", "NULL"))
ecsub<-remove_bom(ecsub)
ecsub<-standardize_variable_names(ecsub)
ecsub$dFYear<-as.Date(paste("1/1/",as.character(ecsub$Fiscal_Year),sep=""),"%m/%d/%Y")



ecsub<-csis360::read_and_join(ecsub,
  "EntitySizeCode.csv",
  by="EntitySizeCode",
  add_var="EntitySmall",
  path="https://raw.githubusercontent.com/CSISdefense/Lookup-Tables/master/",
  dir="vendor/"
)
eid_lc<-prepare_labels_and_colors(FPDS_eid_fyear)
eid_ck<-get_column_key(FPDS_eid_fyear)
ecp_lc<-prepare_labels_and_colors(defense_platform_vendor)
ecp_ck<-get_column_key(defense_platform_vendor)

```
## Join up new entrants
```{r setupnew}
entrant_lookup<-FPDS_eid_fyear %>% select(EntityID,fiscal_year,
                                          entrant,entrant_2018T,
                                          IsEntityAbove2018constant10ThousandThreshold) %>%
  standardize_variable_names()
# defense_platform_vendor <- defense_platform_vendor%>%select(-entrant,-entrant_2018T)
defense_platform_vendor<-defense_platform_vendor[,!colnames(defense_platform_vendor)%in% 
                                                   c("entrant","entrant_2018T",
                                                     "entrant.x","entrant_2018T/x",
                                                     "entrant.y","entrant_2018T.y",
                                                     "IsEntityAbove2018constant10ThousandThreshold",
                                                     "IsEntityAbove2018constant10ThousandThreshold.x",
                                                     "IsEntityAbove2018constant10ThousandThreshold.y")]
defense_platform_vendor<-left_join(defense_platform_vendor,entrant_lookup,
                                   by=c("Fiscal_Year","EntityID"))
defense_platform_vendor$count<-1
defense_platform_vendor<-apply_standard_lookups(defense_platform_vendor)
defense_platform_vendor<-replace_nas_with_unlabeled(defense_platform_vendor,"entrant_2018T")
defense_platform_vendor$entrant_2018T<-factor(defense_platform_vendor$entrant_2018T,
                                              levels=c("TRUE","FALSE","Unlabeled"),
                                              labels=c("New Entrant",
                                                       "Pre-established Vendor",
                                                       "Unlabeled"
                                                       ))

write_csv(defense_platform_vendor,file="../output/defense_platform_vendor.csv")

#Dates: dFYear

#Null Values: "Empty strings "",NULL, NA
#null values not "None"

# {"Action_Obligation_OMB25_GDP23":"double"}
summary(defense_platform_vendor)

```

# Defense Recipient_UEI

### Count by largest contract

```{r def_rpuh_uei}



  (
  all_10k_small_bar<-build_plot(
    data=def_rpuh %>% dplyr::filter(IsEntityAbove2018constantMTAthreshold==1
                                          & Fiscal_Year>=2007& Fiscal_Year<=2025), ##where is FPDS summary?
    chart_geom = "Bar Chart",
    share = FALSE,
    x_var="dFYear",alpha_var="YTD",
    y_var="count", #Name of variable to plot on y-axis
    color_var="LargestContract2018dollars",       # name of coloration variable, as string
    facet_var="AlwaysIsSmallLabel",        # name of facet variable, as string
    legend=TRUE, #Include a legend
    caption=TRUE, #Include a source caption
        labels_and_colors=rpuh_lc,
    column_key=rpuh_ck,
    format=TRUE,
    first_color_on_bottom = FALSE
  )+labs(y="Count of Vendors with\nContracts Above $10 K",x="Fiscal Year",
         title="DOD Contractor Count by Small Business Status\n and Size of Largest Federal Contract, FY 2007-FY 2025 YTD",
         caption="Note: Threshold values are adjusted for inflation (in 2018 $s).\nSource: FPDS Unique Entities (UEI) and CSIS analysis. YTD through 90 days prior to 8/8/2025.")+
    date_x_year_breaks(2007,2022,3,partial_year=2025,partial_label="\nYTD")+date_x_year_breaks(2007,2022,3,partial_year=2025,partial_label="\nYTD")
  )


log_plot(plot=all_10k_small_bar+theme(legend.position="right"), df=def_rpuh %>% dplyr::filter(IsEntityAbove2018constantMTAthreshold==1
                                          & Fiscal_Year>=2007& Fiscal_Year<=2025),#%>% filter(Fiscal_YQ<=2023.2)
                     filename="nps_fig09_def_vendor_count",xlsx="DoD_2025_NPS.xlsx",
                     sheet="9 DIB count",path="../output/AcqTrends/NPS2025/",
         second_path=online_path,
         height=2.5,
         csv_then_year=FALSE  ,excel_then_year=FALSE,excel_y_var=TRUE,
         excel_formulas = TRUE,
                     startRow=1,format=TRUE,#,var_list=c("SimpleArea","Competition.multisum"),
         output_doc_png = TRUE,output_slide_png = TRUE,suppress_doc_svg_text = "title",
         include_YTD = FALSE,
         num_format = "0.00,\"K\""
         )

(
  all_10k_small_line<-build_plot(
    data=def_rpuh %>% dplyr::filter(IsEntityAbove2018constantMTAthreshold==1
                                          & Fiscal_Year>=2007& Fiscal_Year<=2025), ##where is FPDS summary?
    chart_geom = "Line Chart",
    share = FALSE,
    x_var="dFYear",alpha_var="YTD",
    y_var="count", #Name of variable to plot on y-axis
    color_var="LargestContract2018dollars",       # name of coloration variable, as string
    facet_var="AlwaysIsSmallLabel",        # name of facet variable, as string
    legend=TRUE, #Include a legend
    caption=TRUE, #Include a source caption
    labels_and_colors=rpuh_lc,
    column_key=rpuh_ck,
    format=TRUE,
    first_color_on_bottom = FALSE
  )+labs(y="Count of Vendors with\nContracts Above $10 K, FY 2007-FY 2025 YTD",x="Fiscal Year",
         title="DOD Contractor Count by Small Business Status\n and Size of Largest Federal Contract",
         caption="Note: Threshold values are adjusted for inflation (in 2018 $s).\nSource: FPDS Unique Entities (UEI) and CSIS analysis. YTD through 90 days prior to 8/8/2025.")+date_x_year_breaks(2007,2022,3,partial_year=2025,partial_label="\nYTD")
  )


ggsave600dpi(all_10k_small_line+labs(title=NULL),file="nps_fig09a_def_vendor_count_line.svg",size=12,lineheight = 1.2,
             height=3,width=6.5, path="../output/AcqTrends/NPS2025/", 
         second_path=online_path)

def_rpuh %>% dplyr::filter( Fiscal_Year>=2007 & Fiscal_Year<=2025)  %>% group_by(LargestContract2018dollars) %>% summarise(DefenseObligated_OMB25_GDP23=sum(DefenseObligated_OMB25_GDP23))
  (
  all_10k_small_dollar<-build_plot(
    data=def_rpuh %>% dplyr::filter( Fiscal_Year>=2007 & Fiscal_Year<=2025), ##where is FPDS summary?
    chart_geom = "Bar Chart",
    share = FALSE,
    x_var="dFYear",alpha_var="YTD",
    y_var="DefenseObligated_OMB25_GDP23", #Name of variable to plot on y-axis
    color_var="LargestContract2018dollars",       # name of coloration variable, as string
    facet_var="AlwaysIsSmallLabel",        # name of facet variable, as string
    legend=TRUE, #Include a legend
    caption=TRUE, #Include a source caption
    labels_and_colors=rpuh_lc,
    column_key=rpuh_ck,
    format=TRUE,
    first_color_on_bottom = FALSE
  )+labs(y="Obligations (2023 $s)",x="Fiscal Year",
         title="DOD Contract Obligations by Small Business Status\nand Size of Largest Federal Contract, FY 2007-FY 2025 YTD",
         caption="Note: Threshold values are adjusted for inflation (in 2018 $s).\nSource: FPDS Unique Entities (UEI) and CSIS analysis. YTD through 90 days prior to 8/8/2025.")+date_x_year_breaks(2007,2022,3,partial_year=2025,partial_label="\nYTD")+
      theme(legend.position = "right")#guides(fill=guide_legend(nrow=2))
  )
  
log_plot(plot=all_10k_small_dollar, df=def_rpuh %>% dplyr::filter(IsEntityAbove2018constantMTAthreshold==1
                                                                  & Fiscal_Year>=2007& Fiscal_Year<=2025),#%>% filter(Fiscal_YQ<=2023.2)
         second_path=online_path,
         filename="nps_fig10_def_vendor_obl",xlsx="DoD_2025_NPS.xlsx",
         sheet="10 DIB dollars",path="../output/AcqTrends/NPS2025/", height=2.5,
         excel_formulas=TRUE,
         startRow=1,format=TRUE,#,var_list=c("SimpleArea","Competition.multisum"),
         output_slide_png = TRUE,suppress_doc_svg_text = "title"
)

```






# NTDC
### Using Parent UEI
```{r def_rpuh}

  (
  ntdc_count_bar<-build_plot(
    data=def_rpuh %>% dplyr::filter(IsEntityAbove2018constantMTAthreshold==1
                                          & Fiscal_Year>=2007& Fiscal_Year<=2025), ##where is FPDS summary?
    chart_geom = "Bar Chart",
    share = FALSE,
    x_var="dFYear",alpha_var="YTD",
    y_var="count", #Name of variable to plot on y-axis
    color_var="LargestContract2018dollars",       # name of coloration variable, as string
    facet_var="IsEntityTraditionalLabel",        # name of facet variable, as string
    legend=TRUE, #Include a legend
    caption=TRUE, #Include a source caption
        labels_and_colors=rpuh_lc,
    column_key=rpuh_ck,
    format=TRUE
  )+labs(y="Count of Vendors with\nContracts Above $10 K",x="Fiscal Year",
         title="DOD Contractor Count by Small Business Status\nand Size of Largest Federal Contract",
         caption="Note: Threshold values are adjusted for inflation (in 2018 $s).\nSource: FPDS Unique Entities (UEI) and CSIS analysis. YTD through 90 days prior to 8/8/2025.")+
    date_x_year_breaks(2007,2022,3,partial_year=2025,partial_label="\nYTD")+date_x_year_breaks(2007,2022,3,partial_year=2025,partial_label="\nYTD")+facet_wrap(~IsEntityTraditionalLabel, scales="free_y")
  )


  (
  ntdc_count_bar_tall<-build_plot(
    data=def_rpuh %>% dplyr::filter(IsEntityAbove2018constantMTAthreshold==1
                                          & Fiscal_Year>=2007& Fiscal_Year<=2025), ##where is FPDS summary?
    chart_geom = "Bar Chart",
    share = FALSE,
    x_var="dFYear",alpha_var="YTD",
    y_var="count", #Name of variable to plot on y-axis
    color_var="LargestContract2018dollars",       # name of coloration variable, as string
    facet_var="IsEntityTraditionalLabel",        # name of facet variable, as string
    legend=TRUE, #Include a legend
    caption=TRUE, #Include a source caption
        labels_and_colors=rpuh_lc,
    column_key=rpuh_ck,
    format=TRUE
  )+labs(y="Count of Vendors with\nContracts Above $10 K",x="Fiscal Year",
         title="DOD Contractor Count by Small Business Status\nand Size of Largest Federal Contract, FY 2007-FY 2025 YTD",
         caption="Note: Threshold values are adjusted for inflation (in 2018 $s).\nSource: FPDS Unique Entities (UEI) and CSIS analysis. YTD through 90 days prior to 8/8/2025.")+
    date_x_year_breaks(2007,2022,3,partial_year=2025,partial_label="\nYTD")+date_x_year_breaks(2007,2022,3,partial_year=2025,partial_label="\nYTD")+facet_wrap(~IsEntityTraditionalLabel, scales="free_y")+
      facet_grid(IsEntityTraditionalLabel~.,space="free_y",scale="free_y")+theme(strip.text.y = element_text(angle=0))
  )

# log_plot(plot=ntdc_count_bar, df=def_rpuh %>% dplyr::filter(IsEntityAbove2018constantMTAthreshold==1
#                                           & Fiscal_Year>=2007& Fiscal_Year<=2025),#%>% filter(Fiscal_YQ<=2023.2)
#                      filename="def_vendor_count",xlsx="DoD_2025_NPS.xlsx",
#                      sheet="DIB count",path="../output/AcqTrends/NPS2025/", 
#          second_path=online_path,
#          height=3.5,
#          csv_then_year=FALSE  ,excel_then_year=FALSE,excel_y_var=TRUE,
#            output_doc_png = TRUE,
#          excel_formulas = TRUE,
#                      startRow=1,format=TRUE,#,var_list=c("SimpleArea","Competition.multisum"),
#          output_doc_png = TRUE,
#          include_YTD = FALSE,
#          num_format = "0.00,\"K\""
#          )

(
  ntdc_count_line<-build_plot(
    data=def_rpuh %>% dplyr::filter(IsEntityAbove2018constantMTAthreshold==1
                                          & Fiscal_Year>=2007& Fiscal_Year<=2025), ##where is FPDS summary?
    chart_geom = "Line Chart",
    share = FALSE,
    x_var="dFYear",alpha_var="YTD",
    y_var="count", #Name of variable to plot on y-axis
    color_var="LargestContract2018dollars",       # name of coloration variable, as string
    facet_var="IsEntityTraditionalLabel",        # name of facet variable, as string
    legend=TRUE, #Include a legend
    caption=TRUE, #Include a source caption
    labels_and_colors=rpuh_lc,
    column_key=rpuh_ck,
    format=TRUE
  )+labs(y="Count of Vendors with\nContracts Above $10 K",x="Fiscal Year",
         title="DOD Contractor Count by Small Business Status\n and Size of Largest Federal Contract",
         caption="Note: Threshold values are adjusted for inflation (in 2018 $s).\nSource: FPDS Unique Entities (UEI) and CSIS analysis. YTD through 90 days prior to 8/8/2025.")+date_x_year_breaks(2007,2022,3,partial_year=2025,partial_label="\nYTD")
  )




  (
  all_10k_small_bar<-build_plot(
    data=def_rpuh %>% dplyr::filter(IsEntityAbove2018constantMTAthreshold==1
                                          & Fiscal_Year>=2007& Fiscal_Year<=2025), ##where is FPDS summary?
    chart_geom = "Bar Chart",
    share = FALSE,
    x_var="Fiscal_Year",
    y_var="count", #Name of variable to plot on y-axis
    color_var="LargestContract2018dollars",       # name of coloration variable, as string
    facet_var="AlwaysIsSmallLabel",        # name of facet variable, as string
    second_var="IsEntityTraditionalLabel",
    legend=TRUE, #Include a legend
    caption=TRUE, #Include a source caption
    labels_and_colors=rpuh_lc,
    column_key=rpuh_ck,
    format=TRUE
  )+labs(y="Count of vendors with contracts above $10k in 2018 $s",x="Fiscal Year")
  )



def_rpuh<-def_rpuh %>% mutate(
  ntdc_label=case_when(
    AlwaysIsSmall==1 | IsEntityAbove2018constantCommercialItem7500k==0
    ~ "Consistently Small or\nLargest Contract\nUnder $7.5 M",
    TRUE ~ "Variably Small / Larger\nand Largest Contract\nOver $7.5 M"
  )
)
summary(factor(def_rpuh$ntdc_label))

rpuh_lc<-prepare_labels_and_colors(def_rpuh)
rpuh_ck<-get_column_key(def_rpuh)


  (
  ntdc<-build_plot(
    data=def_rpuh %>% dplyr::filter( Fiscal_Year>=2007 & Fiscal_Year<=2025), ##where is FPDS summary?
    
    chart_geom = "Bar Chart",
    share = FALSE,
    x_var="Fiscal_Year",
    y_var="DefenseObligated_OMB25_GDP23", #Name of variable to plot on y-axis
    color_var="ntdc_label",       # name of coloration variable, as string
    facet_var="IsEntityTraditionalLabel",        # name of facet variable, as string
    # second_var="IsEntityTraditionalLabel",
    legend=TRUE, #Include a legend
    caption=TRUE, #Include a source caption
    labels_and_colors=rpuh_lc,
    column_key=rpuh_ck,
    format=TRUE
  )+labs(y="Obligations (2023 $s)",x="Fiscal Year")#+
      # facet_grid(IsEntityTraditionalLabel~ntdc_label)
  )



  # log_plot(plot=ntdc+labs(title=NULL)+theme(legend.position = "right"),
  #          df=def_rpuh %>% dplyr::filter(
  #                                           Fiscal_Year>=2007& Fiscal_Year<=2025),#%>% filter(Fiscal_YQ<=2023.2)
  #          second_path=online_path,
  #                      filename="nps_fig8_ntdc_obl",xlsx="DoD_2025_NPS.xlsx",
  #                      sheet="8 NTDC",path="../output/AcqTrends/NPS2025/",
  #          height=3.5,
  #          excel_formulas=TRUE,
  #                      startRow=1,format=TRUE,#,var_list=c("SimpleArea","Competition.multisum"),
  #          output_doc_png = TRUE
  #          )
```


### Using CAU
#### NTDC investigting CAS
```{r NTDCcheck}
  (
  build_plot(
    data=cas, #%>% dplyr::filter(IsEntityAbove2018constantMTAthreshold==1
                                          # & Fiscal_Year>=2007& Fiscal_Year<=2025), ##where is FPDS summary?
    chart_geom = "Bar Chart",
    share = FALSE,
    x_var="Fiscal_Year",
    y_var="Action_Obligation_OMB25_GDP23", #Name of variable to plot on y-axis
    color_var="costorpricingdata",       # name of coloration variable, as string
    facet_var="CostAccountingStandardsClause",        # name of facet variable, as string
    # second_var="CASexemption",
    legend=TRUE, #Include a legend
    caption=TRUE, #Include a source caption
    # labels_and_colors=rpuh_lc,
    # column_key=rpuh_ck,
    format=TRUE,
    first_color_on_bottom=FALSE
  ))+labs(title="costorpricingdata")+facet_wrap(~CostAccountingStandardsClause,scale="free_y")


colnames(cas)

  (
  build_plot(
    data=cas, #%>% dplyr::filter(IsEntityAbove2018constantMTAthreshold==1
                                          # & Fiscal_Year>=2007& Fiscal_Year<=2025), ##where is FPDS summary?
    chart_geom = "Bar Chart",
    share = FALSE,
    x_var="Fiscal_Year",
    y_var="Action_Obligation_OMB25_GDP23", #Name of variable to plot on y-axis
    color_var="AlwaysCAUisCASexemptOrWaived",       # name of coloration variable, as string
    facet_var="CostAccountingStandardsClause",        # name of facet variable, as string
    # second_var="CASexemption",
    legend=TRUE, #Include a legend
    caption=TRUE, #Include a source caption
    # labels_and_colors=rpuh_lc,
    # column_key=rpuh_ck,
    format=TRUE,
    first_color_on_bottom=FALSE
  ))+labs(title="AlwaysCAUisCASexemptOrWaived")+facet_wrap(~CostAccountingStandardsClause,scale="free_y")


  (
  build_plot(
    data=cas, #%>% dplyr::filter(IsEntityAbove2018constantMTAthreshold==1
                                          # & Fiscal_Year>=2007& Fiscal_Year<=2025), ##where is FPDS summary?
    chart_geom = "Bar Chart",
    share = FALSE,
    x_var="Fiscal_Year",
    y_var="Action_Obligation_OMB25_GDP23", #Name of variable to plot on y-axis
    color_var="AlwaysIsSmall",       # name of coloration variable, as string
    facet_var="CostAccountingStandardsClause",        # name of facet variable, as string
    # second_var="CASexemption",
    legend=TRUE, #Include a legend
    caption=TRUE, #Include a source caption
    # labels_and_colors=rpuh_lc,
    # column_key=rpuh_ck,
    format=TRUE,
    first_color_on_bottom=FALSE
  ))+labs(title="AlwaysIsSmall")+facet_wrap(~CostAccountingStandardsClause,scale="free_y")


  (
  build_plot(
    data=cas, #%>% dplyr::filter(IsEntityAbove2018constantMTAthreshold==1
                                          # & Fiscal_Year>=2007& Fiscal_Year<=2025), ##where is FPDS summary?
    chart_geom = "Bar Chart",
    share = FALSE,
    x_var="Fiscal_Year",
    y_var="Action_Obligation_OMB25_GDP23", #Name of variable to plot on y-axis
    color_var="IsAbove2018constantCostAccounting2000kThreshold",       # name of coloration variable, as string
    facet_var="CostAccountingStandardsClause",        # name of facet variable, as string
    # second_var="CASexemption",
    legend=TRUE, #Include a legend
    caption=TRUE, #Include a source caption
    # labels_and_colors=rpuh_lc,
    # column_key=rpuh_ck,
    format=TRUE,
    first_color_on_bottom=FALSE
  ))+labs(title="IsAbove2018constantCostAccounting2000kThreshold")+facet_wrap(~CostAccountingStandardsClause,scale="free_y")


```

#### NTDC confident
```{r NTDCcheck}
  
  (
  build_plot(
    data=cas, #%>% dplyr::filter(IsEntityAbove2018constantMTAthreshold==1
                                          # & Fiscal_Year>=2007& Fiscal_Year<=2025), ##where is FPDS summary?
    chart_geom = "Bar Chart",
    share = FALSE,
    x_var="Fiscal_Year",
    y_var="Action_Obligation_OMB25_GDP23", #Name of variable to plot on y-axis
    color_var="isforeigngovernment",       # name of coloration variable, as string
    facet_var="CostAccountingStandardsClause",        # name of facet variable, as string
    # second_var="CASexemption",
    legend=TRUE, #Include a legend
    caption=TRUE, #Include a source caption
    # labels_and_colors=rpuh_lc,
    # column_key=rpuh_ck,
    format=TRUE,
    first_color_on_bottom=FALSE
  ))+labs(title="isforeigngovernment")



  (
  build_plot(
    data=cas, #%>% dplyr::filter(IsEntityAbove2018constantMTAthreshold==1
                                          # & Fiscal_Year>=2007& Fiscal_Year<=2025), ##where is FPDS summary?
    chart_geom = "Bar Chart",
    share = FALSE,
    x_var="Fiscal_Year",
    y_var="Action_Obligation_OMB25_GDP23", #Name of variable to plot on y-axis
    color_var="IsSealedBid",       # name of coloration variable, as string
    facet_var="CostAccountingStandardsClause",        # name of facet variable, as string
    # second_var="CASexemption",
    legend=TRUE, #Include a legend
    caption=TRUE, #Include a source caption
    # labels_and_colors=rpuh_lc,
    # column_key=rpuh_ck,
    format=TRUE,
    first_color_on_bottom=FALSE
  ))+labs(title="IsSealedBid")



  (
  build_plot(
    data=cas, #%>% dplyr::filter(IsEntityAbove2018constantMTAthreshold==1
                                          # & Fiscal_Year>=2007& Fiscal_Year<=2025), ##where is FPDS summary?
    chart_geom = "Bar Chart",
    share = FALSE,
    x_var="Fiscal_Year",
    y_var="Action_Obligation_OMB25_GDP23", #Name of variable to plot on y-axis
    color_var="IsAbove2018constantCommercialItem7500k",       # name of coloration variable, as string
    facet_var="CostAccountingStandardsClause",        # name of facet variable, as string
    # second_var="CASexemption",
    legend=TRUE, #Include a legend
    caption=TRUE, #Include a source caption
    # labels_and_colors=rpuh_lc,
    # column_key=rpuh_ck,
    format=TRUE,
    first_color_on_bottom=FALSE
  ))+labs(title="IsAbove2018constantCommercialItem7500k")

  (
  build_plot(
    data=cas, #%>% dplyr::filter(IsEntityAbove2018constantMTAthreshold==1
                                          # & Fiscal_Year>=2007& Fiscal_Year<=2025), ##where is FPDS summary?
    chart_geom = "Bar Chart",
    share = FALSE,
    x_var="Fiscal_Year",
    y_var="Action_Obligation_OMB25_GDP23", #Name of variable to plot on y-axis
    color_var="FixedPriceEffective",       # name of coloration variable, as string
    facet_var="CostAccountingStandardsClause",        # name of facet variable, as string
    # second_var="CASexemption",
    legend=TRUE, #Include a legend
    caption=TRUE, #Include a source caption
    # labels_and_colors=rpuh_lc,
    # column_key=rpuh_ck,
    format=TRUE,
    first_color_on_bottom=FALSE
  ))+labs(title="FixedPriceEffective")



colnames(cas)

  (
  build_plot(
    data=cas, #%>% dplyr::filter(IsEntityAbove2018constantMTAthreshold==1
                                          # & Fiscal_Year>=2007& Fiscal_Year<=2025), ##where is FPDS summary?
    chart_geom = "Bar Chart",
    share = FALSE,
    x_var="Fiscal_Year",
    y_var="Action_Obligation_OMB25_GDP23", #Name of variable to plot on y-axis
    color_var="IsCommercialitemacquisitionprocedures",       # name of coloration variable, as string
    facet_var="CostAccountingStandardsClause",        # name of facet variable, as string
    # second_var="CASexemption",
    legend=TRUE, #Include a legend
    caption=TRUE, #Include a source caption
    # labels_and_colors=rpuh_lc,
    # column_key=rpuh_ck,
    format=TRUE,
    first_color_on_bottom=FALSE
  ))+labs(title="IsCommercialitemacquisitionprocedures")


```

#### NTDC label
```{r NTDClabel}

(
  ntdc_size_label<-build_plot(
    data=cas %>% filter (Fiscal_Year>=2007& Fiscal_Year<=2025), #%>% dplyr::filter(IsEntityAbove2018constantMTAthreshold==1
                                          # & Fiscal_Year>=2007& Fiscal_Year<=2025), ##where is FPDS summary?
    chart_geom = "Bar Chart",
    share = FALSE,
    x_var="dFYear",alpha_var="YTD",
    y_var="Action_Obligation_OMB25_GDP23", #Name of variable to plot on y-axis
    color_var="cas_label",       # name of coloration variable, as string
    facet_var="ntdc_label",        # name of facet variable, as string
    second_var="IsEntityTraditionalLabel",
    legend=TRUE, #Include a legend
    caption=TRUE, #Include a source caption
    labels_and_colors=cas_lc,
    column_key=cas_ck,
    format=TRUE,
    first_color_on_bottom=FALSE
  )+date_x_year_breaks(2007,2022,3,partial_year=2025,partial_label="\nYTD")+
    theme(legend.position = "right")+
      facet_grid(IsEntityTraditionalLabel~ntdc_label)+
  labs(title="AlwaysCAUisCASexemptOrWaived",
                                          y="Obligations (2023 $s)",x="Fiscal Year"))



(
  ntdc_label<-build_plot(
    data=cas %>% filter (Fiscal_Year>=2007& Fiscal_Year<=2025), #%>% dplyr::filter(IsEntityAbove2018constantMTAthreshold==1
                                          # & Fiscal_Year>=2007& Fiscal_Year<=2025), ##where is FPDS summary?
    chart_geom = "Bar Chart",
    share = FALSE,
    x_var="dFYear",alpha_var="YTD",
    y_var="Action_Obligation_OMB25_GDP23", #Name of variable to plot on y-axis
    color_var="cas_label",       # name of coloration variable, as string
    facet_var="IsEntityTraditionalLabel",        # name of facet variable, as string
    # second_var="ntdc_label",
    legend=TRUE, #Include a legend
    caption=TRUE, #Include a source caption
    labels_and_colors=cas_lc,
    column_key=cas_ck,
    format=TRUE,
    first_color_on_bottom=FALSE
  )+theme(legend.position = "right")+
  labs(title="DOD Contract Obligations by Non-Traditional Status and\nCost Accounting Standards Exemption, FY 2007-FY 2025 YTD",y="Obligations (2023 $s)",x="Fiscal Year")+date_x_year_breaks(2007,2022,3,partial_year=2025,partial_label="\nYTD"))



  log_plot(plot=ntdc_label+theme(legend.position = "right"),
           df=cas %>% dplyr::filter(
                                            Fiscal_Year>=2007& Fiscal_Year<=2025),#%>% filter(Fiscal_YQ<=2023.2)
           second_path=online_path,
                       filename="nps_fig11_ntdc_obl",xlsx="DoD_2025_NPS.xlsx",
                       sheet="11 NTDC",path="../output/AcqTrends/NPS2025/",
           height=3.5,
           excel_formulas=TRUE,excel_y_var = TRUE,
           
             suppress_doc_svg_text="title",output_slide_png=TRUE,
                       startRow=1,format=TRUE,#,var_list=c("SimpleArea","Competition.multisum"),
           output_doc_png = TRUE
           )
  
if(nrow(cas %>% filter((IsEntityTraditional==0) & CostAccountingStandardsClause=="Y"))>0){
  View(cas %>% filter(IsEntityTraditional==0 & CostAccountingStandardsClause=="Y"))
  stop("CAS contraction, CAS applied to non-traditional")
}
  
  
    

```

## Overall HHI
```{r def_rpuh_hhi}



  (
  def_rpuh_hhi<-build_plot(
    data=def_rpuh %>% dplyr::filter( Fiscal_Year>=2007& Fiscal_Year<=2025), ##where is FPDS summary?
    chart_geom = "Line Chart",
    share = FALSE,
    x_var="Fiscal_Year",
    y_var="hhi", #Name of variable to plot on y-axis
    # color_var="IsEntityAbove2018constantSimplifedAcquisition250kThreshold",       # name of coloration variable, as string
    # facet_var="AlwaysIsSmallLabel",        # name of facet variable, as string
    legend=TRUE, #Include a legend
    caption=TRUE, #Include a source caption
    # labels_and_colors=eid_lc,
    column_key=NULL,
    format=TRUE,
    first_color_on_bottom=FALSE
  )+labs(y="Herfindahl-\nHirschman\nIndex (HHI)",x="Fiscal Year")
  )


  log_plot(plot=def_rpuh_hhi+labs(title=NULL),
           df=def_rpuh %>% dplyr::filter(
                                            Fiscal_Year>=2007& Fiscal_Year<=2025),#%>% filter(Fiscal_YQ<=2023.2)
           second_path=online_path,
                       filename="nps_figXX_hhi",xlsx="DoD_2025_NPS.xlsx",
                       sheet="XX hhi",path="../output/AcqTrends/NPS2025/",
           height=2,
           excel_formulas=FALSE,excel_then_year = FALSE,csv_then_year=FALSE,
             suppress_doc_svg_text="title",output_slide_png=TRUE,
                       startRow=1,format=TRUE,#,var_list=c("SimpleArea","Competition.multisum"),
           output_doc_png = TRUE
           )

```
