---
title: "JADC2"
author: "Greg Sanders"
date: "2022-10-29"
output: html_document
---


# Setup
First we load the data. The dataset used is a U.S. Defense Contracting dataset derived from FPDS.

```{r Libraries, echo = FALSE}
library(csis360)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(scales)

axis.text.size<-10
strip.text.size<-10
legend.text.size<-8
# table.text.size<-5.75
title.text.size<-12
geom.text.size<-12

main.text.size<-1
note.text.size<-1.40
if(!exists("full_data"))
  load(file="FPDS_chart_maker//unaggregated_FPDS.Rda")

load(file="../data/clean/platpscintl_FPDS.Rda")
load(file="../data/clean/sw_FPDS.Rda")
load(file="../data/clean/jadc2.Rda")

load(file=file.path("..","data","clean","defense_naics_vendor.rdata"))
# detail_lc<-prepare_labels_and_colors(platpscintldef)#,path="K:\\Users\\Greg\\Repositories\\Lookup-Tables\\style\\")
# detail_ck<-get_column_key(platpscintldef)#,path="K:\\Users\\Greg\\Repositories\\Lookup-Tables\\style\\")
# column_key<-get_column_key(platpscintldef,path="K:\\Users\\Greg\\Repositories\\Lookup-Tables\\style\\")
# detail_lc<-prepare_labels_and_colors(platpscintldef,path="K:\\Users\\Greg\\Repositories\\Lookup-Tables\\style\\")
# detail_ck<-get_column_key(platpscintldef,path="K:\\Users\\Greg\\Repositories\\Lookup-Tables\\style\\")
```

#JADC2

## DoD Component 
```{r DoDsoftware}
summary(factor(jadc2$ProjectName))
(
cec_jsubcust<-build_plot(
  data=jadc2, #%>% filter(Fiscal_Year>=2000 & Customer=="Defense")  ,
  chart_geom = "Bar Chart",
  share = FALSE,
  # labels_and_colors=sw_lc,
  # NA, #VAR.ncol
  x_var="Fiscal_Year", #x_var
  y_var="Action_Obligation_OMB20_GDP20", #VAR.y.variable
  color_var="SubCustomer", #color_var
  facet_var="ProjectName", #facet_var
  # column_key=sw_ck,
  format=TRUE,
  ytextposition=FALSE
)+
  # theme(strip.text.y = element_text(angle=0))+
 # theme(axis.text.x = element_text(angle=90))+
 #    scale_y_continuous("Percent of Obligations", labels = percent_format(accuracy=1))+
 #      facet_grid(.~Competition.sum ,scales="free_x", space="free_x"
 #             )+labs(title=NULL,
  # x="Fiscal Year",
  # y="Percent of Obligations",
  # color="Competition")+
  theme(legend.position = "right")+
  labs(y="Obligations (Constant 2021 $s)",caption="Note: Unlabeled not shown. Source: FPDS; CSIS analysis.")#+
    # facet_wrap(~ContractingAgencyTextSwr,ncol=4)
)


(
jsubcust<-build_plot(
  data=jadc2 %>% filter(ProjectName %in% c("ABMS","JADC2","Convergence"))  ,
  chart_geom = "Bar Chart",
  share = FALSE,
  # labels_and_colors=sw_lc,
  # NA, #VAR.ncol
  x_var="Fiscal_Year", #x_var
  y_var="Action_Obligation_OMB20_GDP20", #VAR.y.variable
  color_var="SubCustomer", #color_var
  facet_var="ProjectName", #facet_var
  # column_key=sw_ck,
  format=TRUE,
  ytextposition=FALSE
)+
  # theme(strip.text.y = element_text(angle=0))+
 # theme(axis.text.x = element_text(angle=90))+
 #    scale_y_continuous("Percent of Obligations", labels = percent_format(accuracy=1))+
 #      facet_grid(.~Competition.sum ,scales="free_x", space="free_x"
 #             )+labs(title=NULL,
  # x="Fiscal Year",
  # y="Percent of Obligations",
  # color="Competition")+
  theme(legend.position = "right")+
  labs(y="Obligations (Constant 2021 $s)",caption="Note: Unlabeled not shown. Source: FPDS; CSIS analysis.")#+
    # facet_wrap(~ContractingAgencyTextSwr,ncol=4)
)


(
jsubcust_no_facet<-build_plot(
  data=jadc2 %>% filter(ProjectName %in% c("ABMS","JADC2","Convergence"))  ,
  chart_geom = "Bar Chart",
  share = FALSE,
  # labels_and_colors=sw_lc,
  # NA, #VAR.ncol
  x_var="Fiscal_Year", #x_var
  y_var="Action_Obligation_OMB20_GDP20", #VAR.y.variable
  color_var="SubCustomer", #color_var
  # facet_var="ProjectName", #facet_var
  # column_key=sw_ck,
  format=TRUE,
  ytextposition=FALSE
)+
  # theme(strip.text.y = element_text(angle=0))+
 # theme(axis.text.x = element_text(angle=90))+
 #    scale_y_continuous("Percent of Obligations", labels = percent_format(accuracy=1))+
 #      facet_grid(.~Competition.sum ,scales="free_x", space="free_x"
 #             )+labs(title=NULL,
  # x="Fiscal Year",
  # y="Percent of Obligations",
  # color="Competition")+
  theme(legend.position = "right")+
  labs(y="Obligations (Constant 2021 $s)",caption="Note: Unlabeled not shown. Source: FPDS; CSIS analysis.")#+
    # facet_wrap(~ContractingAgencyTextSwr,ncol=4)
)

ggsave600dpi(cec_jsubcust,file="..//output//Deep_Dives//Jadc2//cec_jadc2_subcust.png",  
             width=6.5, height= 3, units="in",size=8, lineheight=1.2
             )


ggsave600dpi(jsubcust,file="..//output//Deep_Dives//Jadc2//jadc2_subcust.png",  
             width=6.5, height= 3, units="in",size=8, lineheight=1.2
             )

ggsave600dpi(jsubcust_no_facet,file="..//output//Deep_Dives//Jadc2//jadc2_no_facet_subcust.png",  
             width=6.5, height= 3, units="in",size=8, lineheight=1.2
             )

ggsave600dpi(jsubcust,file="..//output//Deep_Dives//Jadc2//jadc2_subcust.eps",  
             width=6.5, height= 3, units="in",size=16, lineheight=1.2
             )

write.csv(file="..//Output//Deep_Dives//Jadc2//jadc2_subcust.csv",row.names = FALSE,na = "",
          jsubcust$data %>% mutate(#Fiscal_Year=lubridate::year(dFYear),
                                bAction_Obligation_OMB20_GDP20=Action_Obligation_OMB20_GDP20/1000000000)%>%
            arrange(Fiscal_Year)%>%
          pivot_wider(id_cols=c(SubCustomer,ProjectName),
                      names_from=Fiscal_Year,values_from=bAction_Obligation_OMB20_GDP20)%>%
            arrange(SubCustomer,ProjectName))

write.csv(jadc2,file="..//Output//Deep_Dives//Jadc2//jadc2.csv",row.names = FALSE,na = "")

```