---
title: "Defense Acquisition Trends"
output:
  html_document:
    keep_md: yes
    toc: yes
date: "Wednesday, October 6, 2021"
---

# Setup
First we load the data. The dataset used is a U.S. Defense Contracting dataset derived from FPDS.

```{r Libraries, echo = FALSE}
library(csis360)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(scales)
library(openxlsx)
axis.text.size<-10
strip.text.size<-10
legend.text.size<-8
# table.text.size<-5.75
title.text.size<-12
geom.text.size<-12

main.text.size<-1
note.text.size<-1.40
if(!exists("platpscintldef"))
  load(file="../data/clean/platpscintl_FPDS.Rda")


if(!exists("platpscdefcd"))
  load(file="../data/clean/platpscdefcd.Rda")

if(!exists("munition"))
  load(file=file.path("data","semi_clean","munition_transaction.rda"))

# save.image("../.RData")
```

# Preprocessing 
## Ukraine cut
```{r Location}
colnames(platpscdefcd)

ukraine_list<-c("1320","1305",
"2350","1410",
"1377","1055",
"1336","1440",
"1390","1337",
"1338","1420",
"1425","1427",
"1430","1450")

if(!"UkraineDIBrelevant" %in% colnames(platpscdefcd))
  platpscdefcd<-read_and_join_experiment(platpscdefcd, "ProjectIDUkraineDIBrelevant.csv",
                                           dir="..\\data\\semi_clean\\",path="",
                                         by="ProjectID",
                                           add_var=c("Project.Name","UkraineDIBrelevant"),
                                           skip_check_var=c("Project.Name","UkraineDIBrelevant"))

ukrplatpsc<-platpscdefcd %>% filter((ProductOrServiceCode %in% ukraine_list
                                      | UkraineDIBrelevant =="Always") & Fiscal_Year>=2022 &
                                        (is.na(UkraineDIBrelevant) | UkraineDIBrelevant !="Never"))
  # summarise(Action_Obligation_OMB24_GDP22=sum(Action_Obligation_OMB24_GDP22))





```

## Project
```{r PreprocessProject}

summary(factor(platpscintldef$ProjectPlatform))

colnames(platpscintldef)[colnames(platpscintldef)=="Action_Obligation_Then_Year_Then_Year"]<-
  "Action_Obligation_Then_Year"

colnames(platpscintldef)[colnames(platpscintldef)=="Action_Obligation_Then_Year_OMB23_GDP21"]<-
  "Action_Obligation_OMB24_GDP22"

topplat<-platpscintldef %>% group_by (Project.Name,PlatformPortfolio) %>%
  summarise(Action_Obligation_OMB24_GDP22=sum(Action_Obligation_OMB24_GDP22),
            Action_Obligation_2020=sum(ifelse(Fiscal_Year==2020,Action_Obligation_OMB24_GDP22,0)))%>%
              group_by (PlatformPortfolio) %>%
    mutate(rank_total=rank(desc(Action_Obligation_OMB24_GDP22)),
                        rank_2020=rank(desc(Action_Obligation_2020)))
topplat %>% arrange(desc(Action_Obligation_OMB24_GDP22))


topplat$TopProject<-
  ifelse(topplat$rank_2020<=7 | topplat$rank_total<=7,topplat$Project.Name,NA)

platpscintldef<-left_join(platpscintldef,topplat %>% select(-Action_Obligation_OMB24_GDP22,Action_Obligation_2020),
          by=c("Project.Name","PlatformPortfolio"))

platpscintldef$TopProject[is.na(platpscintldef$TopProject) & !is.na(platpscintldef$Project.Name)]<-
  "Other Labeled Project"


summary(factor(platpscintldef$TopProject))


```
## PSC
```{r PreprocessPSC}

summary(factor(platpscintldef$ProjectPlatform))

topPSC<-platpscintldef %>% group_by (ProductOrServiceCode,ProductOrServiceCodeText,PlatformPortfolio) %>%
  summarise(Action_Obligation_OMB24_GDP22=sum(Action_Obligation_OMB24_GDP22),
            Action_Obligation_2020=sum(ifelse(Fiscal_Year==2020,Action_Obligation_OMB24_GDP22,0)))%>%
              group_by (PlatformPortfolio) %>%
    mutate(rank_total=rank(desc(Action_Obligation_OMB24_GDP22)),
                        rank_2020=rank(desc(Action_Obligation_2020)))
topPSC %>% arrange(desc(Action_Obligation_OMB24_GDP22))

topPSC$TopPScode<-
  ifelse(topPSC$rank_2020<=7 | topPSC$rank_total<=7,topPSC$ProductOrServiceCode,NA)
topPSC$TopPStext<-
  ifelse(topPSC$rank_2020<=7 | topPSC$rank_total<=7,topPSC$ProductOrServiceCodeText,NA)


platpscintldef<-left_join(platpscintldef,topPSC %>% select(-Action_Obligation_OMB24_GDP22,Action_Obligation_2020),
          by=c("ProductOrServiceCode","PlatformPortfolio"))

platpscintldef$TopPScode[is.na(platpscintldef$TopPScode) & !is.na(platpscintldef$ProductOrServiceCode)]<-
  "Other Labeled PSC"
platpscintldef$TopPStext[is.na(platpscintldef$TopPStext) & !is.na(platpscintldef$ProductOrServiceCode)]<-
  "Other Labeled PSC"

platpscintldef$TopPStext<-factor_wrap(platpscintldef$TopPStext)

summary(factor(platpscintldef$TopPStext))


```

## Place State
```{r PreprocessState}

# platpscintldef$pop_isna<-is.na(platpscintldef$pop_state_code)
# platpscintldef$sc_isna<-is.na(platpscintldef$PlaceStateCode)
# platpscintldef %>% group_by(Fiscal_Year,pop_isna,sc_isna) %>%
#   summarise(n=length(Fiscal_Year))

# summary(factor(platpscintldef$CrisisProductOrServiceArea))

topState<-platpscintldef %>% group_by (pop_state_code,CrisisProductOrServiceArea) %>%
  summarise(Action_Obligation_OMB24_GDP22=sum(Action_Obligation_OMB24_GDP22),
            Action_Obligation_2020=sum(ifelse(Fiscal_Year==2020,Action_Obligation_OMB24_GDP22,0)))%>%
              group_by (CrisisProductOrServiceArea) %>%
    mutate(rank_total=rank(desc(Action_Obligation_OMB24_GDP22)),
                        rank_2020=rank(desc(Action_Obligation_2020)))
topState %>% arrange(desc(Action_Obligation_OMB24_GDP22))

topState$TopStateAbbr<-
  ifelse(topState$rank_2020<=25 | topState$rank_total<=25,topState$pop_state_code,NA)
# topState$TopStateName<-
#   ifelse(topState$rank_2020<=7 | topState$rank_total<=7,topState$PlaceStateCodeText,NA)
platpscintldef<-platpscintldef[,!colnames(platpscintldef) %in% c("Action_Obligation_OMB24_GDP22.x","Action_Obligation_OMB24_GDP22.y",
                                   "Action_Obligation_2020.x","Action_Obligation_2020.y",
  "rank_total.y","rank_total.x","rank_2020.y","rank_2020.x","TopStateAbbr.x","TopStateAbbr.y")]

platpscintldef<-left_join(platpscintldef,topState %>% select(-Action_Obligation_OMB24_GDP22,Action_Obligation_2020),
          by=c("pop_state_code","CrisisProductOrServiceArea"))

platpscintldef$TopStateAbbr[is.na(platpscintldef$TopStateAbbr) & !is.na(platpscintldef$pop_state_code)]<-
  "Other Labeled State"
# platpscintldef$TopStateName[is.na(platpscintldef$TopStateName) & !is.na(platpscintldef$pop_state_code)]<-
#   "Other Labeled State"


# summary(factor(platpscintldef$TopStateName))


```

## Place Country
```{r PreprocessCountry}

# summary(factor(platpscintldef$CrisisProductOrServiceArea))
colnames(platpscintldef)[colnames(platpscintldef)=="Fiscal_Year"]<-"Fiscal_Year"
topCountry<-platpscintldef %>% group_by (PlaceISOalpha3,CrisisProductOrServiceArea) %>%
  summarise(Action_Obligation_OMB24_GDP22=sum(Action_Obligation_OMB24_GDP22),
            Action_Obligation_2020=sum(ifelse(Fiscal_Year==2020,Action_Obligation_OMB24_GDP22,0)))%>%
              group_by (CrisisProductOrServiceArea) %>%
    mutate(rank_total=rank(desc(Action_Obligation_OMB24_GDP22)),
                        rank_2020=rank(desc(Action_Obligation_2020)))
topCountry %>% arrange(desc(Action_Obligation_OMB24_GDP22))

topCountry$TopCountryISO<-
  ifelse(topCountry$rank_2020<=7 | topCountry$rank_total<=7,topCountry$PlaceISOalpha3,NA)
# topCountry$TopCountryName<-
#   ifelse(topCountry$rank_2020<=7 | topCountry$rank_total<=7,topCountry$PlaceCountryCodeText,NA)


platpscintldef<-left_join(platpscintldef,topCountry %>% select(-Action_Obligation_OMB24_GDP22,Action_Obligation_2020),
          by=c("PlaceISOalpha3","CrisisProductOrServiceArea"))

platpscintldef$TopCountryISO[is.na(platpscintldef$TopCountryISO) & !is.na(platpscintldef$PlaceISOalpha3)]<-
  "Other Labeled Country"
# platpscintldef$TopCountryName[is.na(platpscintldef$TopCountryName) & !is.na(platpscintldef$PlaceISOalpha3)]<-
#   "Other Labeled Country"


# summary(factor(platpscintldef$TopCountryName))


```

# Ukraine
## ProdServ
```{r ukr_psc}

wb <- loadWorkbook("..//Output//Munitions//Weapons_Systems_in_Ukr_Supp.xlsx")
writeData(wb, sheet = "PSC", startRow = 2, startCol = 1,
          ukrplatpsc %>% group_by(
            ProductServiceOrRnDarea,ProductOrServiceCode,ProductOrServiceCodeText)%>%
            # arrange(ProductServiceOrRnDarea,ProductOrServiceCode,ProductOrServiceCodeText))%>%
  summarise(Action_Obligation_OMB24_GDP22=sum(Action_Obligation_OMB24_GDP22)))
saveWorkbook(wb,file="..//Output//Munitions//Weapons_Systems_in_Ukr_Supp.xlsx",overwrite = TRUE)


```

## Platform and Project
```{r ukr_psc}
ukrplatpsc$Project.Name[ukrplatpsc$ProjectID==466]<-"PIM"

ukrplatpsc$ProjPSC<-ifelse(is.na(ukrplatpsc$Project.Name),
                           paste(ukrplatpsc$ProductOrServiceCode,ukrplatpsc$ProductOrServiceCodeText,sep="-"),
                           ukrplatpsc$Project.Name)

wb <- loadWorkbook("..//Output//Munitions//Weapons_Systems_in_Ukr_Supp.xlsx")
writeData(wb, sheet = "Plat", startRow = 1, startCol = 1,
          ukrplatpsc %>% group_by(
            PlatformPortfolio,ProjectID,Project.Name)%>%
  summarise(Action_Obligation_OMB24_GDP22=sum(Action_Obligation_OMB24_GDP22)))
saveWorkbook(wb,file="..//Output//Munitions//Weapons_Systems_in_Ukr_Supp.xlsx",overwrite = TRUE)


wb <- loadWorkbook("..//Output//Munitions//Weapons_Systems_in_Ukr_Supp.xlsx")
writeData(wb, sheet = "Plat", startRow = 1, startCol = 6,
          ukrplatpsc %>% group_by(
            PlatformPortfolio,ProjectID,ProjPSC)%>%
  summarise(Action_Obligation_OMB24_GDP22=sum(Action_Obligation_OMB24_GDP22)))
saveWorkbook(wb,file="..//Output//Munitions//Weapons_Systems_in_Ukr_Supp.xlsx",overwrite = TRUE)


```

## Vendor CD
```{r ukr_vendor_CD}

wb <- loadWorkbook("..//Output//Munitions//Weapons_Systems_in_Ukr_Supp.xlsx")
writeData(wb, sheet = "State", startRow = 2, startCol = 1,
          ukrplatpsc %>% group_by(
            VendorIsForeign,VendorStateCode)%>%
            # arrange(ProductServiceOrRnDarea,ProductOrServiceCode,ProductOrServiceCodeText))%>%
  summarise(Action_Obligation_OMB24_GDP22=sum(Action_Obligation_OMB24_GDP22)))
saveWorkbook(wb,file="..//Output//Munitions//Weapons_Systems_in_Ukr_Supp.xlsx",overwrite = TRUE)

ukrplatpsc$VendorCD<-ifelse(nchar(ukrplatpsc$prime_award_transaction_recipient_cd_current)<=2 &
                              ukrplatpsc$VendorIsForeign==0,
                            paste(ukrplatpsc$VendorStateCode,ukrplatpsc$prime_award_transaction_recipient_cd_current,sep="-"),
                                  ukrplatpsc$prime_award_transaction_recipient_cd_current)

wb <- loadWorkbook("..//Output//Munitions//Weapons_Systems_in_Ukr_Supp.xlsx")
writeData(wb, sheet = "State", startRow = 2, startCol = 5,
          ukrplatpsc %>% group_by(
            VendorIsForeign,VendorStateCode,VendorCD)%>%
            # arrange(ProductServiceOrRnDarea,ProductOrServiceCode,ProductOrServiceCodeText))%>%
  summarise(Action_Obligation_OMB24_GDP22=sum(Action_Obligation_OMB24_GDP22)))
saveWorkbook(wb,file="..//Output//Munitions//Weapons_Systems_in_Ukr_Supp.xlsx",overwrite = TRUE)


```

## Place CD
```{r ukr_place_CD}


wb <- loadWorkbook("..//Output//Munitions//Weapons_Systems_in_Ukr_Supp.xlsx")
writeData(wb, sheet = "Place", startRow = 2, startCol = 1,
          ukrplatpsc %>% group_by(
            PlaceIsForeign,pop_state_code)%>%
  summarise(Action_Obligation_OMB24_GDP22=sum(Action_Obligation_OMB24_GDP22)))
saveWorkbook(wb,file="..//Output//Munitions//Weapons_Systems_in_Ukr_Supp.xlsx",overwrite = TRUE)

ukrplatpsc$VendorCD<-ifelse(nchar(ukrplatpsc$prime_award_transaction_place_of_performance_cd_current)<=2 &
                              ukrplatpsc$PlaceIsForeign==0,
                            paste(ukrplatpsc$pop_state_code,ukrplatpsc$prime_award_transaction_place_of_performance_cd_current,sep="-"),
                                  ukrplatpsc$prime_award_transaction_place_of_performance_cd_current)

wb <- loadWorkbook("..//Output//Munitions//Weapons_Systems_in_Ukr_Supp.xlsx")
writeData(wb, sheet = "Place", startRow = 2, startCol = 5,
          ukrplatpsc %>% group_by(
            PlaceIsForeign,pop_state_code,VendorCD)%>%
  summarise(Action_Obligation_OMB24_GDP22=sum(Action_Obligation_OMB24_GDP22)))
saveWorkbook(wb,file="..//Output//Munitions//Weapons_Systems_in_Ukr_Supp.xlsx",overwrite = TRUE)


```



### Project Customer Breakout
```{r ProjPlatBreakout} 
# summary(platpscdefcd$fiscal_quarter)
  log_plot(plot=NULL, df=platpscdefcd %>% filter((ProductOrServiceCode %in% ukraine_list
                                      | UkraineDIBrelevant =="Always") & #Fiscal_YQ<=2023.2
                                        (is.na(UkraineDIBrelevant) | UkraineDIBrelevant !="Never")),
           filename=paste("Ukraine_related_DIB","all_poroject",sep="_"),xlsx="Weapons_Systems_in_Ukr_Supp.xlsx",
           x_var="Fiscal_Year",y_var="Action_Obligation_OMB24_GDP22",
           sheet="AllProj",path=file.path("../output/Munitions/"),
            csv_then_year=TRUE,excel_then_year = FALSE, excel_y_var=TRUE,excel_formula=TRUE,
           format=TRUE,var_list=c("PlatformPortfolio","Project.Name","ProjectID"),
           output_doc_png=FALSE, output_doc_svg = FALSE
           )

```


### PSC Customer Breakout
```{r PSCcustBreakout} 

  log_plot(plot=NULL, df=platpscdefcd %>% filter((ProductOrServiceCode %in% ukraine_list
                                      | UkraineDIBrelevant =="Always") &# Fiscal_YQ<=2023.2 &
                                        (is.na(UkraineDIBrelevant) | UkraineDIBrelevant !="Never")),
           filename=paste("Ukraine_related_DIB","all_psc",sep="_"),xlsx="Weapons_Systems_in_Ukr_Supp.xlsx",
           x_var="Fiscal_Year",y_var="Action_Obligation_OMB24_GDP22",
           sheet="AllPSC",path=file.path("../output/Munitions/"),
           csv_then_year=TRUE,excel_then_year = FALSE, excel_y_var=TRUE,excel_formulas = TRUE,
           format=TRUE,var_list=c("ProductOrServiceArea","ProductOrServiceCode","ProductOrServiceCodeText"),
           output_doc_png=FALSE, output_doc_svg = FALSE
           )


```

## NAICS look
```{r MunitionsNAICS}
bottleneck_list<-c("1320",#AMMUNITION, OVER 125 MM
                #"1305",#AMMUNITION, THROUGH 30 MM
#"2350", COMBAT ASSAULT & TACTICAL VEH
"1410", #GUIDED MISSILES
"1377", #CARTRIDGE & PROPELLANT DEVICES
"1055", #LAUNCHERS, ROCKET AND PYROTECHNI
"1336", #GUIDED MISSILE WARHEADS AND EXPLOSIVE COMPONENTS
"1440", #LAUNCHERS, GUIDED MISSILE
"1390", #	FUZES AND PRIMERS
"1337", # GUIDED MISSILE AND SPACE VEHICLE EXPLOSIVE PROPULSION UNITS, SOLID FUEL; AND COMPONENTS
"1338", #GUIDED MISSILE AND SPACE VEHICLE INERT PROPULSION UNITS, SOLID FUEL; AND COMPONENTS
"1420", #GUIDED MISSILE COMPONENTS
"1425", #GUIDED MISSILE SYSTEMS, COMPLETE
"1427", #	GUIDED MISSILE SUBSYSTEMS
"1430", #	GUIDED MISSILE REMOTE CONT SYSTEMS
"1450" #GUIDED MISSILE HANDLING AND SERVICING EQUIPMENT
) 

pscnaics %>% filter(ProductOrServiceCode %in% ukraine_list)  %>%
  group_by(ProductOrServiceCode,ProductOrServiceCodeText) %>%
  summarise(Action_Obligation=sum(Action_Obligation,na.rm=TRUE)) %>%
  arrange(ProductOrServiceCode)

ukrnaics<-pscnaics %>% filter(ProductOrServiceCode %in% bottleneck_list)  %>%
  group_by(principalnaicscode,principalnaicscodeText) %>%
  summarise(Action_Obligation=sum(Action_Obligation,na.rm=TRUE)) %>%
  arrange(-Action_Obligation)

levels(pscnaics$PlatformPortfolio)
ukrnaicsplat<-pscnaics %>% filter(PlatformPortfolio %in% c("Ordnance and Missiles","Missile Defense"))  %>%
  group_by(principalnaicscode,principalnaicscodeText) %>%
  summarise(Action_Obligation=sum(Action_Obligation,na.rm=TRUE)) %>%
  arrange(-Action_Obligation)


  bottleneck_naics<-c(336414,336419,332993,325920,332995)
  
  ukrnaicsplat<-pscnaics %>% filter(principalnaicscode %in% bottleneck_naics)  %>%
  group_by(principalnaicscode,principalnaicscodeText) %>%
  summarise(Action_Obligation=sum(Action_Obligation,na.rm=TRUE)) %>%
  arrange(principalnaicscode)


```

### 155mm production
```{r}
artillery<-read.csv(file.path("..","data_raw","USA_Artillery_Production.csv")) %>%filter(!is.na(Monthly.Production))

artillery$Aproximate.Date<-as.Date(artillery$Aproximate.Date,"%m/%d/%Y")
artillery$Monthly.Production<-text_to_number(artillery$Monthly.Production)

(prod155mm<-
  build_plot(artillery %>% filter(Series!="A&S Sept. 2022 Targets"),
           chart_geom = "Line Chart",
           x_var="Aproximate.Date",
           y_var="Monthly.Production",
           alpha_var="Type",
           color_var="Series")+geom_point(aes(x=Aproximate.Date,
                                              y=Monthly.Production,
                                              color=Series),
                                          size=3,
                                          data=
                                            artillery %>% filter(Series!="A&S Sept. 2022 Targets"&
                                                                   Duplicate.Actuals==FALSE)
                                          )+scale_linetype(guide="none")+
  labs(x="Reporting Date or Target Deadline", y="Monthly Production\nof 155mm Ammunition",
       title="Army 155mm Ammunition Production Rates and Targets",
       caption="Sources: Bryan Bender and Lara Seligman, Politico, Dec., 4, 2022;
       Jen Judson, DefenseNews, Mar. 28, 2023; Noah Robertson, DefenseNews, Sept. 15, 2023; 
       Sam Skove, Defense One, Nov. 27, 2023; initial chart by Govini; and CSIS analysis.")+
    scale_x_date(date_breaks = "6 months",date_labels = "'%y\n%b")+
    geom_line(aes(x=Aproximate.Date,
                                              y=Monthly.Production,
                                              color=Series,
                  linetype=Type),linewidth=1.5)+
    theme(legend.position="bottom")
    #,labels = "%Y-%m"
)
ggsave600dpi(prod155mm,file=file.path("..","Output","Munitions","prod155.png"),width=11,height=4,
             size=14,lineheight=1)
ggsave600dpi(prod155mm,file=file.path("..","Output","Munitions","prod155.svg"),width=11,height=4,
             size=14,lineheight=1)
```


## HIMARS

```{r}

(
HimarsPSR<-build_plot(
  data=platpscintldef %>% filter(Project.Name=='MLRS'),
  chart_geom = "Bar Chart",
  share = FALSE,
  labels_and_colors=labels_and_colors,
  # NA, #VAR.ncol
  x_var="Fiscal_Year", #x_var
  y_var="Action_Obligation_OMB24_GDP22", #VAR.y.variable
  color_var="Shiny.VendorSize", #color_var
  # facet_var="Competition.sum", #facet_var
  column_key=column_key,
  format=TRUE,
  ytextposition=FALSE
)+
  # theme(strip.text.y = element_text(angle=0))+
 # theme(axis.text.x = element_text(angle=90))+
 #    scale_y_continuous("Percent of Obligations", labels = percent_format(accuracy=1))+
 #      facet_grid(.~Competition.sum ,scales="free_x", space="free_x"
 #             )+labs(title=NULL,
  # x="Fiscal Year",
  # y="Percent of Obligations",
  # color="Competition")+
  theme(legend.position = "right")+
  labs(y="Obligations (Constant 2021 $s)")
)

ggsave600dpi("..//Output//Deep_Dives//Himars//Himars_psr.png", HimarsPSR, 
             width=12, height= 6, units="in",size=12, lineheight=1.2
             )

ggsave600dpi("..//Output//Deep_Dives//Himars//Himars_psr.emf", HimarsPSR, 
             width=6.5, height= 3, units="in",size=11, lineheight=1.2
             )

output_TY<-platpscintldef %>% group_by(Shiny.VendorSize,Fiscal_Year,Project.Name)%>% filter(Project.Name=='MLRS') %>%
            dplyr::summarize(Action_Obligation_Then_Year=sum(Action_Obligation_Then_Year,na.rm=TRUE))%>%
  arrange(Fiscal_Year) %>%
          pivot_wider(id_cols=c(Project.Name,Shiny.VendorSize),
                      names_from=Fiscal_Year,values_from=Action_Obligation_Then_Year)
write.csv(file="..//Output//Deep_Dives//Himars//Himars_psr.csv",row.names = FALSE, na = "",
          output_TY)



# wb <- loadWorkbook("..//Output//DoD_Acq_Trends_Contracts.xlsx", create = TRUE)
# addWorksheet(wb, name = "Area")
#  writeData(wb, output_TY, sheet = "Area", startRow = 14, startCol = 14)
# saveWorkbook(wb)


```

