---
title: "UAS and Drones"
author: "Greg Sanders"
date: '2022-06-24'
output: html_document
---
#Drones
## Preprocess
```{r PreprocessProjectDrone}

platpscintldef<-csis360::read_and_join_experiment(platpscintldef,
                                             "ProjectID.txt",
                                             by=c("ProjectID"),
                                             add_var="IsRemotelyOperated",
                                             path="https://raw.githubusercontent.com/CSISdefense/Lookup-Tables/master/",
                                             dir="project/",
                                             skip_check_var = "IsRemotelyOperated"
)

colnames(platpscintldef)[colnames(platpscintldef)=='Action_Obligation_Then_Year_OMB23_GDP21']<-"Action_Obligation_OMB23_GDP21"
colnames(platpscintldef)[colnames(platpscintldef)=='Action_Obligation_Then_Year_Then_Year']<-"Action_Obligation_Then_Year"

summary(platpscintldef$PlatformPortfolio)
attritable<-platpscintldef %>%  filter(ProductOrServiceCode==1550 | IsRemotelyOperated==1 | PlatformPortfolio=="Ordnance and Missiles")
attritable$PlatformPortfolio.Remote<-as.character(attritable$PlatformPortfolio)
attritable$PlatformPortfolio.Remote[attritable$ProductOrServiceCode==1550 | attritable$IsRemotelyOperated==1]<-"Remotely Crewed"


summary(factor(drone$ProjectName))
colnames(drone)[colnames(drone)=='Action_Obligation_Then_Year_OMB23_GDP21']<-"Action_Obligation_OMB23_GDP21"

droneplat<-drone %>% group_by(ProjectName) %>%
  dplyr::summarise(Action_Obligation_OMB23_GDP21=sum(Action_Obligation_OMB23_GDP21),
            Action_Obligation_2020=sum(ifelse(Fiscal_Year==2020,Action_Obligation_OMB23_GDP21,0)))%>%
              group_by () %>%#PlatformPortfolio
    mutate(rank_total=rank(desc(Action_Obligation_OMB23_GDP21)),
                        rank_2020=rank(desc(Action_Obligation_2020)))
droneplat %>% arrange(desc(Action_Obligation_OMB23_GDP21))


droneplat$TopProject<-
  ifelse(droneplat$rank_2020<=7 | droneplat$rank_total<=7,droneplat$ProjectName,NA)

drone<-left_join(drone,droneplat %>% select(-Action_Obligation_OMB23_GDP21,Action_Obligation_2020),
          by=c("ProjectName"))

drone$TopProject[is.na(drone$TopProject) & !is.na(drone$ProjectName)]<-
  "Other Labeled Project"


summary(factor(drone$TopProject))


summary(factor(platpscintldef$ProjectPlatform))

dronePSC<-drone %>% group_by (ProductOrServiceCode,ProductOrServiceCodeText) %>%
  summarise(Action_Obligation_OMB23_GDP21=sum(Action_Obligation_OMB23_GDP21),
            Action_Obligation_2020=sum(ifelse(Fiscal_Year==2020,Action_Obligation_OMB23_GDP21,0)))%>%
              group_by () %>%
    mutate(rank_total=rank(desc(Action_Obligation_OMB23_GDP21)),
                        rank_2020=rank(desc(Action_Obligation_2020)))
dronePSC %>% arrange(desc(Action_Obligation_OMB23_GDP21))

dronePSC$dronePSCode<-
  ifelse(dronePSC$rank_2020<=5 | dronePSC$rank_total<=5,dronePSC$ProductOrServiceCode,NA)
dronePSC$TopPStext<-
  ifelse(dronePSC$rank_2020<=5 | dronePSC$rank_total<=5,dronePSC$ProductOrServiceCodeText,NA)


drone<-left_join(drone,dronePSC %>% select(-Action_Obligation_OMB23_GDP21,Action_Obligation_2020),
          by=c("ProductOrServiceCode"))

drone$dronePSCode[is.na(drone$dronePSCode) & !is.na(drone$ProductOrServiceCode)]<-
  "Other Labeled PSC"
drone$TopPStext[is.na(drone$TopPStext) & !is.na(drone$ProductOrServiceCode)]<-
  "Other Labeled PSC"

drone$TopPStext<-factor_wrap(drone$TopPStext)

summary(factor(drone$TopPStext))

drone %>% dplyr::group_by(ProjectName, IsRemotelyOperated)  %>% dplyr::summarise(Action_Obligation_2020.x=sum(Action_Obligation_2020.x))

```


## Simple 
```{r drone_customer}

(
rc_psr<-build_plot(
  data=drone  ,
  chart_geom = "Bar Chart",
  share = FALSE,
  # labels_and_colors=drone_lc,
  # NA, #VAR.ncol
  x_var="Fiscal_Year", #x_var
  y_var="Action_Obligation_OMB23_GDP21", #VAR.y.variable
  color_var="SimpleArea", #color_var
  facet_var="SimpleArea", #facet_var
  # column_key=drone_ck,
  format=TRUE,
  ytextposition=FALSE
)+
  # theme(strip.text.y = element_text(angle=0))+
 # theme(axis.text.x = element_text(angle=90))+
 #    scale_y_continuous("Percent of Obligations", labels = percent_format(accuracy=1))+
 #      facet_grid(.~Competition.sum ,scales="free_x", space="free_x"
 #             )+labs(title=NULL,
  # x="Fiscal Year",
  # y="Percent of Obligations",
  # color="Competition")+
  theme(legend.position = "right")+
  labs(caption="Note: Unlabeled not shown. Source: FPDS; CSIS analysis.")#+
    # facet_wrap(~ContractingAgencyTextSwr,ncol=4)
)

ggsave600dpi(rc_psr,file="..//output//Deep_Dives//Remotely_Crewed//Remotely_Crewed_psr.png",  
             width=13, height= 6, units="in",size=8, lineheight=1.2
             )
ggsave600dpi(rc_psr,file="..//output//Deep_Dives//Remotely_Crewed//Remotely_Crewed_psr.eps",  
             width=13, height= 6, units="in",size=16, lineheight=1.2
             )

write.csv(file="..//Output//Deep_Dives//Remotely_Crewed//Remotely_Crewed_crewed_psr.csv",row.names = FALSE,na = "",
          rc_psr$data %>% mutate(#Fiscal_Year=lubridate::year(dFYear),
                                bAction_Obligation_OMB23_GDP21=Action_Obligation_OMB23_GDP21/1000000000)%>%
            arrange(Fiscal_Year)%>%
          pivot_wider(id_cols=c(SimpleArea),
                      names_from=Fiscal_Year,values_from=bAction_Obligation_OMB23_GDP21)%>%
            arrange(SimpleArea))

```

## Customer 
```{r drone_customer}

# drone %>% group_by(claimantprogramcode,ClaimantProgramCodeText) %>% 
#   summarise(Action_Obligation_OMB23_GDP21=sum(Action_Obligation_OMB23_GDP21))
# drone$SubCustomer
(
rc_customer<-build_plot(
  data=drone %>% filter(Fiscal_Year>=2005) ,
  chart_geom = "Bar Chart",
  share = FALSE,
  labels_and_colors=intl_lc,
  # NA, #VAR.ncol
  x_var="Fiscal_Year", #x_var
  y_var="Action_Obligation_OMB23_GDP21", #VAR.y.variable
  color_var="SubCustomer.sum", #color_var
  facet_var="SubCustomer.sum", #facet_var
  column_key=intl_ck,
  format=TRUE,
  ytextposition=FALSE
)+
  # theme(strip.text.y = element_text(angle=0))+
 # theme(axis.text.x = element_text(angle=90))+
 #    scale_y_continuous("Percent of Obligations", labels = percent_format(accuracy=1))+
 #      facet_grid(.~Competition.sum ,scales="free_x", space="free_x"
 #             )+labs(title=NULL,
  # x="Fiscal Year",
  # y="Percent of Obligations",
  # color="Competition")+
  theme(legend.position = "right")+
  labs(y="Obligations (Constant 2021 $s)",caption="Note: Unlabeled not shown. Source: FPDS; CSIS analysis.")#+
    # facet_wrap(~ContractingAgencyTextSwr,ncol=4)
)

ggsave600dpi(rc_customer,file="..//output//Deep_Dives//Remotely_Crewed//Remotely_Crewed_Customer.png",  
             width=6.5, height= 3.5, units="in",size=11, lineheight=1.2
             )
ggsave600dpi(rc_customer,file="..//output//Deep_Dives//Remotely_Crewed//Remotely_Crewed_Customer.svg",  
             width=6.5, height= 3.5, units="in",size=11, lineheight=1.2
             )
ggsave600dpi(rc_customer,file="..//output//Deep_Dives//Remotely_Crewed//Remotely_Crewed_Customer.emf",  
             width=6.5, height= 3.5, units="in",size=11, lineheight=1.2
             )

write.csv(file="..//Output//Deep_Dives//Remotely_Crewed//Remotely_Crewed_crewed_Customer.csv",row.names = FALSE,na = "",
          rc_customer$data %>% mutate(#Fiscal_Year=lubridate::year(dFYear),
                                bAction_Obligation_OMB23_GDP21=Action_Obligation_OMB23_GDP21/1000000000)%>%
            arrange(Fiscal_Year)%>%
          pivot_wider(id_cols=c(SubCustomer.sum),
                      names_from=Fiscal_Year,values_from=bAction_Obligation_OMB23_GDP21)%>%
            arrange(SubCustomer.sum))



output_TY<-drone %>%   group_by(SubCustomer.sum,Fiscal_Year)%>%
            dplyr::summarize(Action_Obligation_Then_Year=sum(Action_Obligation_Then_Year,na.rm=TRUE))%>%
  arrange(Fiscal_Year) %>%
          pivot_wider(id_cols=c(SubCustomer.sum),
                      names_from=Fiscal_Year,values_from=Action_Obligation_Then_Year) %>%
  arrange(SubCustomer.sum)
write.csv(file="..//Output//Deep_Dives//Remotely_Crewed//Remotely_Crewed_crewed_Customer_cur.csv",row.names = FALSE, na = "",
          output_TY)

```


## Vendor Size
```{r ToplineVendor}


(
RCVendor<-build_plot(
  data=attritable %>% filter(Fiscal_Year<=2020),
  chart_geom = "Bar Chart",
  share = FALSE,
  labels_and_colors=labels_and_colors,
  # NA, #VAR.ncol
  x_var="dFYear", #x_var
  y_var="Action_Obligation_OMB23_GDP21", #VAR.y.variable
  color_var="Shiny.VendorSize", #color_var
  facet_var="PlatformPortfolio.Remote", #facet_var
  column_key=column_key,
  format=TRUE,
  ytextposition=FALSE
)+scale_x_date("Fiscal Year",labels = date_format("'%y"))+
  # theme(strip.text.y = element_text(angle=0))+
 # theme(axis.text.x = element_text(angle=90))+
    scale_y_continuous("Contract Dollars Obligated\n(Constant 2021 $s, Variable Scale)")+
      facet_grid(PlatformPortfolio.Remote~. ,scales="free_y")+
 #             )+labs(title=NULL,
  # x="Fiscal Year",
  # y="Percent of Obligations",
  # color="Competition")+
  theme(legend.position = "right")+
  labs(
       caption="Source: FPDS; CSIS Analysis.\nNote: The merger of Raytheon and United Technologies took place in April of 2020 and thus did not make the cutoff for inclusion in FY2020.")
)

ggsave600dpi("..//Output//Deep_Dives//Remotely_Crewed//remotely_crewed_vendor_square.png", RCVendor+
  labs(caption="Source: FPDS; CSIS Analysis.\nNote: The merger of Raytheon and United Technologies is took place in \nApril of 2020 and thus did not make the cutoff for inclusion in FY2020."), 
             width=6.5, height= 4, units="in",size=12,lineheight=1
             )



```

## Commercial
```{r UAScomm}

(
RCcomm<-build_plot(
  data=attritable %>% filter(Fiscal_Year<=2021 & Fiscal_Year>=2000 ),
  chart_geom = "Bar Chart",
  share = FALSE,
  labels_and_colors=labels_and_colors,
  # NA, #VAR.ncol
  x_var="dFYear", #x_var
  y_var="Action_Obligation_OMB23_GDP21", #VAR.y.variable
  color_var="AnyCommercial", #color_var
  facet_var="PlatformPortfolio.Remote", #facet_var
  column_key=column_key,
  format=TRUE,
  ytextposition=FALSE
)+scale_x_date("Fiscal Year",labels = date_format("'%y"))+
  # theme(strip.text.y = element_text(angle=0))+
 # theme(axis.text.x = element_text(angle=90))+
    scale_y_continuous("Contract Dollars Obligated\n(Constant 2021 $s, Variable Scale)")+
      facet_grid(PlatformPortfolio.Remote~. ,scales="free_y")+
 #             )+labs(title=NULL,
  # x="Fiscal Year",
  # y="Percent of Obligations",
  # color="Competition")+
  theme(legend.position = "right")
)


ggsave600dpi("..//Output//Deep_Dives//Remotely_Crewed//remotely_crewed_comm.png", RCcomm, 
             width=6, height= 5, units="in",size=12,lineheight=1
             )



```


## Vendor International
```{r ToplineVendor}


(
RCVendorIntl<-build_plot(
  data=drone %>% filter(Fiscal_Year<=2020),
  chart_geom = "Bar Chart",
  share = FALSE,
  labels_and_colors=labels_and_colors,
  # NA, #VAR.ncol
  x_var="dFYear", #x_var
  y_var="Action_Obligation_OMB23_GDP21", #VAR.y.variable
  color_var="VendorSize_Intl", #color_var
  # facet_var="Competition.sum", #facet_var
  column_key=column_key,
  format=TRUE,
  ytextposition=FALSE
)+scale_x_date("Fiscal Year",labels = date_format("'%y"))+
  # theme(strip.text.y = element_text(angle=0))+
 # theme(axis.text.x = element_text(angle=90))+
 #    scale_y_continuous("Percent of Obligations", labels = percent_format(accuracy=1))+
 #      facet_grid(.~Competition.sum ,scales="free_x", space="free_x"
 #             )+labs(title=NULL,
  # x="Fiscal Year",
  # y="Percent of Obligations",
  # color="Competition")+
  theme(legend.position = "right")+
  labs(
       caption="Source: FPDS; CSIS Analysis.\nNote: The merger of Raytheon and United Technologies took place in April of 2020 and thus did not make the cutoff for inclusion in FY2020.")
)

ggsave600dpi("..//Output//Deep_Dives//Remotely_Crewed//remotely_crewed_vendor_intl_square.png", RCVendorIntl+
  labs(caption="Source: FPDS; CSIS Analysis.\nNote: The merger of Raytheon and United Technologies is took place in \nApril of 2020 and thus did not make the cutoff for inclusion in FY2020."), 
             width=6, height= 5, units="in",size=12,lineheight=1
             )



```

###FMS identification
```{r contract_identification}

(rc_contract_IsFMS <-  build_plot(data=attritable %>% filter(ContractingCustomer=="Defense",
                                                                      Fiscal_Year>=2011),
                            chart_geom="Bar Chart",
                            share=FALSE,
                            x_var="Fiscal_Year",
                            y_var="Action_Obligation_OMB23_GDP21",
                            color_var="IsFMS",
                            facet_var="PlatformPortfolio.Remote",
                            # second_var="PlatformPortfolio.Remote",
                            labels_and_colors=intl_lc,
                            column_key=intl_ck,
                            legend=TRUE,
                            caption=FALSE,
                        format=TRUE)+
    # facet_grid(  IsFMS~., scales="free_y")+
scale_y_continuous("Contract Dollars Obligated\n(Constant 2021 $s, Variable Scale)")+
      facet_grid(PlatformPortfolio.Remote~. ,scales="free_y")+
     # labs(#x="Year of Delivery (Calendar or Fiscal Varies by Source)",
     #   y="Constant 2020 $ Obligated",
     #   caption="Source: FPDS; CSIS analysis.")+
    guides(fill=guide_legend(ncol=3)))



# undebug(build_plot)

(rc_contract_identification <-  build_plot(data=attritable %>% filter(ContractingCustomer=="Defense",
                                                                      Fiscal_Year>=2015),
                            chart_geom="Bar Chart",
                            share=FALSE,
                            x_var="Fiscal_Year",
                            y_var="Action_Obligation_OMB23_GDP21",
                            color_var="foreign_funding_description",
                            facet_var="PlatformPortfolio.Remote",
                            # second_var="PlatformPortfolio.Remote",
                            labels_and_colors=intl_lc,
                            column_key=intl_ck,
                            legend=TRUE,
                            caption=FALSE,
                        format=TRUE)+
    # facet_grid(  IsFMS~., scales="free_y")+
scale_y_continuous("Contract Dollars Obligated\n(Constant 2021 $s, Variable Scale)")+
      facet_grid(PlatformPortfolio.Remote~. ,scales="free_y")+
     # labs(#x="Year of Delivery (Calendar or Fiscal Varies by Source)",
     #   y="Constant 2020 $ Obligated",
     #   caption="Source: FPDS; CSIS analysis.")+
    guides(fill=guide_legend(ncol=3)))

ggsave600dpi(rc_contract_identification,file="../output//Deep_Dives//Remotely_Crewed//figure_03_contract_identification.png",
             size=12,lineheight=1, height =4, width=6.5)



```


### FMS Vendor Size/Intl and Place No JSF
```{r FPDS_vendor_Intl}

summary(factor(platpscintldef$Shiny.VendorSize[platpscintldef$VendorIsForeign==1]))
summary(platpscintldef$VendorSize_Intl)

# undebug(format_data_for_plot)
(fpds_vendor_intl_place_noJSF <-  build_plot(data=drone ,
                                       #IsFMS==TRUE 
                                       chart_geom="Bar Chart",
                            x_var="Fiscal_Year",
                            y_var="Action_Obligation_OMB23_GDP21",
                            color_var="VendorSize_Intl",
                            # facet_var="PlaceIsForeign",
                            second_var="IsFMS",
                            labels_and_colors=intl_lc,
                            column_key=intl_ck,
                            legend=TRUE,
                            caption=FALSE,
                            format=TRUE)+theme(legend.position = "right")+
    facet_grid( .~IsFMS )+labs(title="FMS or Performed Internationally, No JSF")#, scales="free_y"
  )


# platpscintldef$Shiny.VendorSize
(rc_vendor_place_fms <-  build_plot(data=drone %>% filter((PlaceIsForeign==1|IsFMS==TRUE)&!is.na(PlaceIsForeign)&
                                                            !is.na(IsFMS)&Fiscal_Year>2011&Fiscal_Year<=2020),#IsFMS==TRUE  
                            chart_geom="Bar Chart",
                            x_var="Fiscal_Year",
                            y_var="Action_Obligation_OMB23_GDP21",
                            color_var="VendorSize_Intl",
                            facet_var="PlaceIsForeign",
                            second_var="IsFMS",
                            labels_and_colors=intl_lc,
                            column_key=intl_ck,
                            legend=TRUE,
                            caption=FALSE,
                            format=TRUE)+theme(legend.position = "right")+
    facet_grid( .~IsFMS+PlaceIsForeign )+labs(title="FMS or Performed Internationally, No JSF")#, scales="free_y"#, scales="free_y"
  )


write.csv(file="..//output//Deep_Dives//Remotely_Crewed//rc_vendor_place_FMS.csv",row.names = FALSE,na = "",
          rc_vendor_place_fms$data%>%# mutate(dFYear=lubridate::year(dFYear))%>%
            pivot_wider(id_cols=c(VendorSize_Intl,IsFMS, PlaceIsForeign),
                        names_from=Fiscal_Year,values_from=Action_Obligation_OMB23_GDP21)%>% arrange(PlaceIsForeign,IsFMS,VendorSize_Intl))

ggsave600dpi(rc_vendor_place_fms,file="../output/Deep_Dives//Remotely_Crewed//rc_vendor_place_FMS.png",
             size = 12, lineheight=1, height =4.5, width=9)



```

## Project
```{r Land}
summary(factor(drone$ProjectPlatform))
# drone$Fiscal_Year
# 
# topplat<-drone %>% filter(PlatformPortfolio=="Ships & Submarines") %>% group_by (ProjectName) %>%
#   summarise(Action_Obligation_OMB23_GDP21=sum(Action_Obligation_OMB23_GDP21),
#             Action_Obligation_2020=sum(ifelse(Fiscal_Year==2020,Action_Obligation_OMB23_GDP21,0))
#             )%>% mutate(rank_total=rank(desc(Action_Obligation_OMB23_GDP21)),
#                         rank_2020=rank(desc(Action_Obligation_2020)))
# topplat %>% arrange(desc(Action_Obligation_OMB23_GDP21))
# 
# drone$TopShipProject<-
#   ifelse(drone$ProjectName %in% topplat$ProjectName[topplat$rank_2020<=7 | topplat$rank_total<=7],
#          drone$ProjectName,NA)
# drone$TopShipProject[is.na(drone$TopShipProject) & !is.na(drone$ProjectName)]<-
#   "Other Labeled Project"
# summary(factor(drone$TopShipProject))


(
Platform<-build_plot(
  data=drone ,
  chart_geom = "Line Chart",
  share = FALSE,
  # labels_and_colors=labels_and_colors,
  # NA, #VAR.ncol
  x_var="dFYear", #x_var
  y_var="Action_Obligation_OMB23_GDP21", #VAR.y.variable
  color_var="TopProject", #color_var
  facet_var="TopProject", #facet_var
  # column_key=column_key,
  format=TRUE,
  ytextposition=FALSE
)+scale_x_date("Fiscal Year",labels = date_format("'%y"))+
  # theme(strip.text.y = element_text(angle=0))+
 # theme(axis.text.x = element_text(angle=90))+
 #    scale_y_continuous("Percent of Obligations", labels = percent_format(accuracy=1))+
 #      facet_grid(.~Competition.sum ,scales="free_x", space="free_x"
 #             )+labs(title=NULL,
  # x="Fiscal Year",
  # y="Percent of Obligations",
  # color="Competition")+
  theme(legend.position = "none")+
  labs(y="Obligations (Constant 2021 $s)")
)
# 
# 
(
PSC<-build_plot(
  data=drone,
  chart_geom = "Line Chart",
  share = FALSE,
  # labels_and_colors=labels_and_colors,
  # NA, #VAR.ncol
  x_var="dFYear", #x_var
  y_var="Action_Obligation_OMB23_GDP21", #VAR.y.variable
  color_var="TopPStext", #color_var
  facet_var="TopPStext", #facet_var
  # column_key=column_key,
  format=TRUE,
  ytextposition=FALSE
)+scale_x_date("Fiscal Year",labels = date_format("'%y"))+
  # theme(strip.text.y = element_text(angle=0))+
 # theme(axis.text.x = element_text(angle=90))+
 #    scale_y_continuous("Percent of Obligations", labels = percent_format(accuracy=1))+
 #      facet_grid(.~Competition.sum ,scales="free_x", space="free_x"
 #             )+labs(title=NULL,
  # x="Fiscal Year",
  # y="Percent of Obligations",
  # color="Competition")+
  theme(legend.position = "none")+
  labs(y="Obligations (Constant 2021 $s)")
)

```
